Halide: test/runtime/common.h File Reference
common.h File Reference
#include <cstddef>
#include <cstdint>
#include "HalideRuntime.h"
#include "msan_stubs.cpp"
#include "runtime_internal.h"
#include "to_string.cpp"
#include "printer.h"
Functions
int printf (const char *format,...)
void halide_print (void *user_context, const char *str)
Print a message to stderr.
void halide_error (void *user_context, const char *msg)
Halide calls this function on runtime errors (for example bounds checking failures).
void halide_profiler_report (void *user_context)
Print out timing statistics for everything run since the last reset.
void halide_profiler_reset ()
Reset profiler state cheaply.
Function Documentation
printf()
int printf (const char * format, ...)
Examples
tutorial/lesson_01_basics.cpp, tutorial/lesson_02_input_image.cpp, tutorial/lesson_03_debugging_1.cpp, tutorial/lesson_04_debugging_2.cpp, tutorial/lesson_05_scheduling_1.cpp, tutorial/lesson_06_realizing_over_shifted_domains.cpp, tutorial/lesson_07_multi_stage_pipelines.cpp, tutorial/lesson_08_scheduling_2.cpp, tutorial/lesson_09_update_definitions.cpp, tutorial/lesson_10_aot_compilation_generate.cpp, tutorial/lesson_10_aot_compilation_run.cpp, tutorial/lesson_11_cross_compilation.cpp, tutorial/lesson_12_using_the_gpu.cpp, tutorial/lesson_13_tuples.cpp, and tutorial/lesson_14_types.cpp.
Referenced by check_call_graphs(), and Halide::Internal::GpuObjectLifetimeTracker::validate_gpu_object_lifetime().
halide_print()
void halide_print (void * user_context, const char * str)
Print a message to stderr.
Main use is to support tracing functionality, print, and print_when calls. Also called by the default halide_error. This function can be replaced in JITed code by using halide_custom_print and providing an implementation of halide_print in AOT code. See Func::set_custom_print.
Definition at line 13 of file common.h.
halide_error()
void halide_error (void * user_context, const char * msg)
Halide calls this function on runtime errors (for example bounds checking failures).
This function can be replaced in JITed code by using Func::set_error_handler, or in AOT code by calling halide_set_error_handler. In AOT code on platforms that support weak linking (i.e. not Windows), you can also override it by simply defining your own halide_error.
Definition at line 17 of file common.h.
Referenced by halide_set_num_threads().
halide_profiler_report()
void halide_profiler_report (void * user_context)
Print out timing statistics for everything run since the last reset.
Also happens at process exit.
Definition at line 21 of file common.h.
halide_profiler_reset()
void halide_profiler_reset ()
Reset profiler state cheaply.
May leave threads running or some memory allocated but all accumluated statistics are reset. WARNING: Do NOT call this method while any halide pipeline is running; halide_profiler_memory_allocate/free and halide_profiler_stack_peak_update update the profiler pipeline's state without grabbing the global profiler state's lock.
Definition at line 24 of file common.h.