Halide: Halide::Internal::ScheduleParamBase Class Reference
Halide::Internal::ScheduleParamBase Class Reference abstract
#include <ScheduleParam.h>
Inherited by Halide::ScheduleParam< T >.
Public Member Functions
const std::string & name () const
bool is_looplevel_param () const
const Type & scalar_type () const
operator Expr () const
operator LoopLevel () const
Protected Member Functions
EXPORT ScheduleParamBase (const Type &t, const std::string &name, bool is_explicit_name)
virtual EXPORT ~ScheduleParamBase ()
virtual void set_from_string (const std::string &new_value_string)=0
EXPORT ScheduleParamBase (const ScheduleParamBase &)
EXPORT ScheduleParamBase & operator= (const ScheduleParamBase &)
Protected Attributes
std::string sp_name
Type type
Internal::Parameter scalar_parameter
Expr scalar_expr
LoopLevel loop_level
Detailed Description
Definition at line 20 of file ScheduleParam.h.
Constructor & Destructor Documentation
EXPORT Halide::Internal::ScheduleParamBase::ScheduleParamBase (const Type & t, const std::string & name, bool is_explicit_name) protected
virtual EXPORT Halide::Internal::ScheduleParamBase::~ScheduleParamBase () protected virtual
EXPORT Halide::Internal::ScheduleParamBase::ScheduleParamBase (const ScheduleParamBase &) explicit protected
Member Function Documentation
const std::string& Halide::Internal::ScheduleParamBase::name () const inline
Definition at line 22 of file ScheduleParam.h.
References sp_name.
bool Halide::Internal::ScheduleParamBase::is_looplevel_param () const inline
Definition at line 26 of file ScheduleParam.h.
References Halide::Handle(), and type.
Referenced by operator Expr(), operator LoopLevel(), and scalar_type().
const Type& Halide::Internal::ScheduleParamBase::scalar_type () const inline
Definition at line 30 of file ScheduleParam.h.
References internal_assert, is_looplevel_param(), and type.
Halide::Internal::ScheduleParamBase::operator Expr () const inline
Definition at line 35 of file ScheduleParam.h.
References is_looplevel_param(), scalar_expr, and user_assert.
Halide::Internal::ScheduleParamBase::operator LoopLevel () const inline
Definition at line 40 of file ScheduleParam.h.
References is_looplevel_param(), loop_level, and user_assert.
virtual void Halide::Internal::ScheduleParamBase::set_from_string (const std::string & new_value_string) protected pure virtual
Implemented in Halide::ScheduleParam< T >.
EXPORT ScheduleParamBase& Halide::Internal::ScheduleParamBase::operator= (const ScheduleParamBase &) protected
Member Data Documentation
std::string Halide::Internal::ScheduleParamBase::sp_name protected
Definition at line 72 of file ScheduleParam.h.
Referenced by name().
Type Halide::Internal::ScheduleParamBase::type protected
Definition at line 73 of file ScheduleParam.h.
Referenced by is_looplevel_param(), and scalar_type().
Internal::Parameter Halide::Internal::ScheduleParamBase::scalar_parameter protected
Definition at line 74 of file ScheduleParam.h.
Expr Halide::Internal::ScheduleParamBase::scalar_expr protected
Definition at line 75 of file ScheduleParam.h.
Referenced by operator Expr().
LoopLevel Halide::Internal::ScheduleParamBase::loop_level protected
Definition at line 76 of file ScheduleParam.h.
Referenced by operator LoopLevel().
The documentation for this class was generated from the following file:
ScheduleParam.h