Halide: Halide::Internal::GeneratorInput_Scalar< T > Class Template Reference
Halide::Internal::GeneratorInput_Scalar< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorInputImpl< T, Expr >.
Inherited by Halide::Internal::GeneratorInput_Arithmetic< T >.
Public Member Functions
GeneratorInput_Scalar (const std::string &name, const TBase &def=static_cast< TBase >(0))
def_ (def)
GeneratorInput_Scalar (size_t array_size, const std::string &name, const TBase &def=static_cast< TBase >(0))
def_ (def)
operator Expr () const
You can use this Input as an expression in a halide function definition.
operator ExternFuncArgument () const
Using an Input as the argument to an external stage treats it as an Expr.
Public Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
size_t size () const
const Expr & operator[] (size_t i) const
const Expr & at (size_t i) const
std::vector< Expr >::const_iterator begin () const
std::vector< Expr >::const_iterator end () const
Public Member Functions inherited from Halide::Internal::GIOBase
EXPORT bool array_size_defined () const
EXPORT size_t array_size () const
EXPORT const std::string & name () const
EXPORT IOKind kind () const
EXPORT bool types_defined () const
EXPORT const std::vector< Type > & types () const
EXPORT Type type () const
EXPORT bool dimensions_defined () const
EXPORT int dimensions () const
EXPORT const std::vector< Func > & funcs () const
EXPORT const std::vector< Expr > & exprs () const
Protected Types
using TBase = typename Super::TBase
Protected Types inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
using TBase = typename std::remove_all_extents< T >::type
Protected Member Functions
void set_def_min_max () override
std::string get_c_type () const override
Protected Member Functions inherited from Halide::Internal::GeneratorInputImpl< T, Expr >
bool is_array () const override
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
GeneratorInputImpl (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Protected Member Functions inherited from Halide::Internal::GeneratorInputBase
EXPORT GeneratorInputBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
EXPORT GeneratorInputBase (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
EXPORT ~GeneratorInputBase () override
EXPORT void init_internals ()
EXPORT void set_inputs (const std::vector< StubInput > &inputs)
EXPORT void verify_internals () const override
EXPORT void check_value_writable () const override
Protected Member Functions inherited from Halide::Internal::GIOBase
EXPORT GIOBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &types, int dimensions)
virtual EXPORT ~GIOBase ()
EXPORT std::string array_name (size_t i) const
EXPORT void check_matching_array_size (size_t size)
EXPORT void check_matching_type_and_dim (const std::vector< Type > &t, int d)
template<typename ElemType >
const std::vector< ElemType > & get_values () const
virtual bool allow_synthetic_generator_params () const
virtual Parameter parameter () const
template<>
const std::vector< Expr > & get_values () const
template<>
const std::vector< Func > & get_values () const
Protected Attributes
const TBase def_ {TBase()}
Protected Attributes inherited from Halide::Internal::GeneratorInputBase
std::vector< Parameter > parameters_
Protected Attributes inherited from Halide::Internal::GIOBase
int array_size_
const std::string name_
const IOKind kind_
std::vector< Type > types_
int dimensions_
std::vector< Func > funcs_
std::vector< Expr > exprs_
GeneratorBase * generator {nullptr}
Detailed Description
template<typename T>
class Halide::Internal::GeneratorInput_Scalar< T >
Definition at line 1402 of file Generator.h.
Member Typedef Documentation
template<typename T > using Halide::Internal::GeneratorInput_Scalar< T >::TBase = typename Super::TBase protected
Definition at line 1406 of file Generator.h.
Constructor & Destructor Documentation
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (const std::string & name, const TBase & def = static_cast<TBase>(0)) inline explicit
Definition at line 1422 of file Generator.h.
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::GeneratorInput_Scalar (size_t array_size, const std::string & name, const TBase & def = static_cast<TBase>(0)) inline
Definition at line 1427 of file Generator.h.
Member Function Documentation
template<typename T > void Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max () inline override protected virtual
Reimplemented from Halide::Internal::GeneratorInputBase.
Reimplemented in Halide::Internal::GeneratorInput_Arithmetic< T >.
Definition at line 1411 of file Generator.h.
References Halide::Internal::GeneratorInput_Scalar< T >::def_, Halide::Internal::GeneratorInputBase::parameters_, and Halide::Internal::Parameter::set_scalar().
Referenced by Halide::Internal::GeneratorInput_Arithmetic< T >::set_def_min_max().
template<typename T > std::string Halide::Internal::GeneratorInput_Scalar< T >::get_c_type () const inline override protected virtual
Implements Halide::Internal::GeneratorInputBase.
Definition at line 1417 of file Generator.h.
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::def_ (def) inline
Definition at line 1424 of file Generator.h.
References Halide::Internal::GeneratorInput_Scalar< T >::def_().
Referenced by Halide::Internal::GeneratorInput_Scalar< T >::def_().
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::def_ (def) inline
Definition at line 1430 of file Generator.h.
References Halide::Internal::GeneratorInput_Scalar< T >::def_().
Referenced by Halide::Internal::GeneratorInput_Scalar< T >::def_().
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::operator Expr () const inline
You can use this Input as an expression in a halide function definition.
Definition at line 1435 of file Generator.h.
References Halide::Internal::GIOBase::exprs().
template<typename T > Halide::Internal::GeneratorInput_Scalar< T >::operator ExternFuncArgument () const inline
Using an Input as the argument to an external stage treats it as an Expr.
Definition at line 1441 of file Generator.h.
References Halide::Internal::GeneratorInputImpl< T, Expr >::at(), and Halide::Internal::GIOBase::exprs().
Member Data Documentation
template<typename T > const TBase Halide::Internal::GeneratorInput_Scalar< T >::def_ {TBase()} protected
Definition at line 1408 of file Generator.h.
Referenced by Halide::Internal::GeneratorInput_Scalar< T >::set_def_min_max().
The documentation for this class was generated from the following file:
Generator.h