Halide: Halide::Internal::Autoscheduler::Span Class Reference
Halide::Internal::Autoscheduler::Span Class Reference
#include <FunctionDAG.h>
Public Member Functions
int64_t min () const
int64_t max () const
int64_t extent () const
bool constant_extent () const
void union_with (const Span &other)
void set_extent (int64_t e)
void translate (int64_t x)
Span (int64_t a, int64_t b, bool c)
Span ()=default
Span (const Span &other)=default
int64_t min () const
int64_t max () const
int64_t extent () const
bool constant_extent () const
void union_with (const Span &other)
void set_extent (int64_t e)
void translate (int64_t x)
Span (int64_t a, int64_t b, bool c)
Span ()=default
Span (const Span &other)=default
Static Public Member Functions
static Span empty_span ()
static Span empty_span ()
Detailed Description
Definition at line 255 of file FunctionDAG.h.
Constructor & Destructor Documentation
Span() [1/6]
Halide::Internal::Autoscheduler::Span::Span (int64_t a, int64_t b, bool c) inline
Definition at line 260 of file FunctionDAG.h.
Span() [2/6]
Halide::Internal::Autoscheduler::Span::Span () default
Referenced by empty_span().
Span() [3/6]
Halide::Internal::Autoscheduler::Span::Span (const Span & other) default
Span() [4/6]
Halide::Internal::Autoscheduler::Span::Span (int64_t a, int64_t b, bool c) inline
Definition at line 288 of file FunctionDAG.h.
Span() [5/6]
Halide::Internal::Autoscheduler::Span::Span () default
Span() [6/6]
Halide::Internal::Autoscheduler::Span::Span (const Span & other) default
Member Function Documentation
min() [1/2]
int64_t Halide::Internal::Autoscheduler::Span::min () const inline
Definition at line 232 of file FunctionDAG.h.
Referenced by union_with().
max() [1/2]
int64_t Halide::Internal::Autoscheduler::Span::max () const inline
Definition at line 235 of file FunctionDAG.h.
Referenced by union_with().
extent() [1/2]
int64_t Halide::Internal::Autoscheduler::Span::extent () const inline
Definition at line 238 of file FunctionDAG.h.
constant_extent() [1/2]
bool Halide::Internal::Autoscheduler::Span::constant_extent () const inline
Definition at line 241 of file FunctionDAG.h.
Referenced by union_with().
union_with() [1/2]
void Halide::Internal::Autoscheduler::Span::union_with (const Span & other) inline
Definition at line 245 of file FunctionDAG.h.
References constant_extent(), max(), and min().
set_extent() [1/2]
void Halide::Internal::Autoscheduler::Span::set_extent (int64_t e) inline
Definition at line 251 of file FunctionDAG.h.
translate() [1/2]
void Halide::Internal::Autoscheduler::Span::translate (int64_t x) inline
Definition at line 255 of file FunctionDAG.h.
empty_span() [1/2]
static Span Halide::Internal::Autoscheduler::Span::empty_span () inline static
Definition at line 265 of file FunctionDAG.h.
References Span().
min() [2/2]
int64_t Halide::Internal::Autoscheduler::Span::min () const inline
Definition at line 260 of file FunctionDAG.h.
max() [2/2]
int64_t Halide::Internal::Autoscheduler::Span::max () const inline
Definition at line 263 of file FunctionDAG.h.
extent() [2/2]
int64_t Halide::Internal::Autoscheduler::Span::extent () const inline
Definition at line 266 of file FunctionDAG.h.
constant_extent() [2/2]
bool Halide::Internal::Autoscheduler::Span::constant_extent () const inline
Definition at line 269 of file FunctionDAG.h.
union_with() [2/2]
void Halide::Internal::Autoscheduler::Span::union_with (const Span & other) inline
Definition at line 273 of file FunctionDAG.h.
References constant_extent(), max(), and min().
set_extent() [2/2]
void Halide::Internal::Autoscheduler::Span::set_extent (int64_t e) inline
Definition at line 279 of file FunctionDAG.h.
translate() [2/2]
void Halide::Internal::Autoscheduler::Span::translate (int64_t x) inline
Definition at line 283 of file FunctionDAG.h.
empty_span() [2/2]
static Span Halide::Internal::Autoscheduler::Span::empty_span () inline static
Definition at line 295 of file FunctionDAG.h.
References Span().
The documentation for this class was generated from the following files:
/Users/areinking/dev/Halide/src/autoschedulers/adams2019/FunctionDAG.h
/Users/areinking/dev/Halide/src/autoschedulers/anderson2021/FunctionDAG.h