Halide: Halide::Runtime::Internal::Synchronization::fast_cond Class Reference
Halide::Runtime::Internal::Synchronization::fast_cond Class Reference
#include <synchronization_common.h>
Public Member Functions
__attribute__ ((always_inline)) fast_cond()
__attribute__ ((always_inline)) void signal()
__attribute__ ((always_inline)) void broadcast()
__attribute__ ((always_inline)) void wait(fast_mutex *mutex)
Detailed Description
Definition at line 1052 of file synchronization_common.h.
Member Function Documentation
__attribute__() [1/4]
Halide::Runtime::Internal::Synchronization::fast_cond::__attribute__ ((always_inline)) inline
Definition at line 1056 of file synchronization_common.h.
__attribute__() [2/4]
Halide::Runtime::Internal::Synchronization::fast_cond::__attribute__ ((always_inline)) inline
Definition at line 1058 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::unpark_one().
__attribute__() [3/4]
Halide::Runtime::Internal::Synchronization::fast_cond::__attribute__ ((always_inline)) inline
Definition at line 1072 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::unpark_requeue().
__attribute__() [4/4]
Halide::Runtime::Internal::Synchronization::fast_cond::__attribute__ ((always_inline)) inline
Definition at line 1085 of file synchronization_common.h.
References halide_assert, NULL, and Halide::Runtime::Internal::Synchronization::park().
The documentation for this class was generated from the following file:
synchronization_common.h