Halide: Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C Class Reference
Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C Class Reference
#include <CodeGen_OpenCL_Dev.h>
Inherits Halide::Internal::CodeGen_C.
Public Member Functions
CodeGen_OpenCL_C (std::ostream &s, Target t)
void add_kernel (Stmt stmt, const std::string &name, const std::vector< DeviceArgument > &args)
Public Member Functions inherited from Halide::Internal::CodeGen_C
CodeGen_C (std::ostream &dest, Target target, OutputKind output_kind=CImplementation, const std::string &include_guard="")
Initialize a C code generator pointing at a particular output stream (e.g.
~CodeGen_C () override
void compile (const Module &module)
Emit the declarations contained in the module as C code.
const Target & get_target () const
The target we're generating code for.
void add_common_macros (std::ostream &dest)
Add common macros to be shared across all backends.
Public Member Functions inherited from Halide::Internal::IRPrinter
virtual ~IRPrinter ()
IRPrinter (std::ostream &)
Construct an IRPrinter pointed at a given output stream (e.g.
void print (Expr)
emit an expression on the output stream
void print (Stmt)
emit a statement on the output stream
void print_list (const std::vector< Expr > &exprs)
emit a comma delimited list of exprs, without any leading or trailing punctuation.
Public Member Functions inherited from Halide::Internal::IRVisitor
IRVisitor ()
virtual ~IRVisitor ()
Protected Member Functions
std::string print_type (Type type, AppendSpaceIfNeeded append_space=DoNotAppendSpace) override
Emit the C name for a halide type.
std::string print_reinterpret (Type type, Expr e) override
Emit a statement to reinterpret an expression as another type.
std::string print_extern_call (const Call *op) override
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
void add_vector_typedefs (const std::set< Type > &vector_types) override
Add typedefs for vector types.
std::string get_memory_space (const std::string &)
void visit (const For *) override
void visit (const Ramp *op) override
void visit (const Broadcast *op) override
void visit (const Call *op) override
void visit (const Load *op) override
void visit (const Store *op) override
void visit (const Cast *op) override
void visit (const Select *op) override
void visit (const EQ *) override
void visit (const NE *) override
void visit (const LT *) override
void visit (const LE *) override
void visit (const GT *) override
void visit (const GE *) override
void visit (const Allocate *op) override
void visit (const Free *op) override
void visit (const AssertStmt *op) override
void visit (const Shuffle *op) override
void visit (const Min *op) override
void visit (const Max *op) override
Protected Member Functions inherited from Halide::Internal::CodeGen_C
std::string print_expr (Expr)
Emit an expression as an assignment, then return the id of the resulting var.
std::string print_cast_expr (const Type &, Expr)
Like print_expr, but cast the Expr to the given Type.
void print_stmt (Stmt)
Emit a statement.
void create_assertion (const std::string &id_cond, const std::string &id_msg)
void create_assertion (const std::string &id_cond, Expr message)
void create_assertion (Expr cond, Expr message)
virtual std::string print_name (const std::string &)
Emit a version of a string that is a valid identifier in C (.
std::string print_scalarized_expr (Expr e)
Convert a vector Expr into a series of scalar Exprs, then reassemble into vector of original type.
virtual std::string print_assignment (Type t, const std::string &rhs)
Emit an SSA-style assignment, and set id to the freshly generated name.
bool is_header ()
Return true if only generating an interface, which may be extern "C" or C++.
bool is_c_plus_plus_interface ()
Return true if generating C++ linkage.
void open_scope ()
Open a new C scope (i.e.
void close_scope (const std::string &comment)
Close a C scope (i.e.
void forward_declare_type_if_needed (const Type &t)
If the Type is a handle type, emit a forward-declaration for it if we haven't already.
void set_name_mangling_mode (NameMangling mode)
void visit (const Variable *) override
void visit (const IntImm *) override
void visit (const UIntImm *) override
void visit (const StringImm *) override
void visit (const FloatImm *) override
void visit (const Add *) override
void visit (const Sub *) override
void visit (const Mul *) override
void visit (const Div *) override
void visit (const Mod *) override
void visit (const And *) override
void visit (const Or *) override
void visit (const Not *) override
void visit (const Let *) override
void visit (const LetStmt *) override
void visit (const ProducerConsumer *) override
void visit (const Provide *) override
void visit (const Realize *) override
void visit (const IfThenElse *) override
void visit (const Evaluate *) override
void visit (const Prefetch *) override
void visit (const Fork *) override
void visit (const Acquire *) override
void visit_binop (Type t, Expr a, Expr b, const char *op)
virtual void compile (const LoweredFunc &func)
Emit a declaration.
virtual void compile (const Buffer<> &buffer)
Emit a declaration.
Protected Member Functions inherited from Halide::Internal::IRPrinter
void do_indent ()
Emit spaces according to the current indentation level.
void visit (const IntImm *) override
void visit (const UIntImm *) override
void visit (const FloatImm *) override
void visit (const StringImm *) override
void visit (const Cast *) override
void visit (const Variable *) override
void visit (const Add *) override
void visit (const Sub *) override
void visit (const Mul *) override
void visit (const Div *) override
void visit (const Mod *) override
void visit (const Min *) override
void visit (const Max *) override
void visit (const EQ *) override
void visit (const NE *) override
void visit (const LT *) override
void visit (const LE *) override
void visit (const GT *) override
void visit (const GE *) override
void visit (const And *) override
void visit (const Or *) override
void visit (const Not *) override
void visit (const Select *) override
void visit (const Load *) override
void visit (const Ramp *) override
void visit (const Broadcast *) override
void visit (const Call *) override
void visit (const Let *) override
void visit (const LetStmt *) override
void visit (const AssertStmt *) override
void visit (const ProducerConsumer *) override
void visit (const For *) override
void visit (const Acquire *) override
void visit (const Store *) override
void visit (const Provide *) override
void visit (const Allocate *) override
void visit (const Free *) override
void visit (const Realize *) override
void visit (const Block *) override
void visit (const Fork *) override
void visit (const IfThenElse *) override
void visit (const Evaluate *) override
void visit (const Shuffle *) override
void visit (const Prefetch *) override
Additional Inherited Members
Public Types inherited from Halide::Internal::CodeGen_C
enum OutputKind { CHeader, CPlusPlusHeader, CImplementation, CPlusPlusImplementation }
Static Public Member Functions inherited from Halide::Internal::CodeGen_C
static void test ()
Static Public Member Functions inherited from Halide::Internal::IRPrinter
static void test ()
Protected Types inherited from Halide::Internal::CodeGen_C
enum AppendSpaceIfNeeded { DoNotAppendSpace, AppendSpace }
Static Protected Member Functions inherited from Halide::Internal::CodeGen_C
template<typename T >
static std::string with_sep (const std::vector< T > &v, const std::string &sep)
template<typename T >
static std::string with_commas (const std::vector< T > &v)
Protected Attributes inherited from Halide::Internal::CodeGen_C
std::string id
An ID for the most recently generated ssa variable.
Target target
The target being generated for.
OutputKind output_kind
Controls whether this instance is generating declarations or definitions and whether the interface us extern "C" or C++.
std::map< std::string, std::string > cache
A cache of generated values in scope.
Scope< Allocation > allocations
Track the types of allocations to avoid unnecessary casts.
Scope heap_allocations
Track which allocations actually went on the heap.
bool have_user_context
True if there is a void * __user_context parameter in the arguments.
bool extern_c_open
Track current calling convention scope.
bool uses_gpu_for_loops
True if at least one gpu-based for loop is used.
std::set< const halide_handle_cplusplus_type * > forward_declared
Track which handle types have been forward-declared already.
Protected Attributes inherited from Halide::Internal::IRPrinter
std::ostream & stream
The stream we're outputting on.
int indent
The current indentation level, useful for pretty-printing statements.
Detailed Description
Definition at line 45 of file CodeGen_OpenCL_Dev.h.
Constructor & Destructor Documentation
CodeGen_OpenCL_C()
Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::CodeGen_OpenCL_C (std::ostream & s, Target t) inline
Definition at line 47 of file CodeGen_OpenCL_Dev.h.
References add_kernel(), add_vector_typedefs(), Halide::Internal::CodeGen_C::DoNotAppendSpace, get_memory_space(), print_extern_call(), print_reinterpret(), print_type(), visit(), and Halide::Internal::CodeGen_C::visit().
Member Function Documentation
add_kernel()
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::add_kernel (Stmt stmt, const std::string & name, const std::vector< DeviceArgument > & args)
Referenced by CodeGen_OpenCL_C().
print_type()
std::string Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::print_type (Type , AppendSpaceIfNeeded space_option = DoNotAppendSpace) override protected virtual
Emit the C name for a halide type.
If space_option is AppendSpace, and there should be a space between the type and the next token, one is appended. (This allows both "int foo" and "Foo *foo" to be formatted correctly. Otherwise the latter is "Foo * foo".)
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_OpenCL_C().
print_reinterpret()
std::string Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::print_reinterpret (Type , Expr) override protected virtual
Emit a statement to reinterpret an expression as another type.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_OpenCL_C().
print_extern_call()
std::string Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::print_extern_call (const Call * op) override protected virtual
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_OpenCL_C().
add_vector_typedefs()
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::add_vector_typedefs (const std::set< Type > & vector_types) override protected virtual
Add typedefs for vector types.
Not needed for OpenCL, might use different syntax for other C-like languages.
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_OpenCL_C().
get_memory_space()
std::string Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::get_memory_space (const std::string &) protected
Referenced by CodeGen_OpenCL_C().
visit() [1/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const For *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
Referenced by CodeGen_OpenCL_C().
visit() [2/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Ramp * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [3/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Broadcast * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [4/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Call * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [5/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Load * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [6/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Store * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [7/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Cast * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [8/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Select * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [9/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const EQ *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [10/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const NE *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [11/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const LT *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [12/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const LE *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [13/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const GT *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [14/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const GE *) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [15/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Allocate * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [16/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Free * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [17/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const AssertStmt * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [18/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Shuffle * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [19/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Min * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
visit() [20/20]
void Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::visit (const Max * op) override protected virtual
Reimplemented from Halide::Internal::CodeGen_C.
The documentation for this class was generated from the following file:
CodeGen_OpenCL_Dev.h