Halide: Halide::Runtime::Internal::Printer< type, length > Class Template Reference
Halide::Runtime::Internal::Printer< type, length > Class Template Reference
#include <runtime_internal.h>
Public Member Functions
Printer (void *ctx)
Printer & operator<< (const char *arg)
Printer & operator<< (int64_t arg)
Printer & operator<< (int32_t arg)
Printer & operator<< (uint64_t arg)
Printer & operator<< (uint32_t arg)
Printer & operator<< (double arg)
Printer & operator<< (float arg)
Printer & operator<< (const void *arg)
const char * str ()
uint64_t size () const
~Printer ()
Public Attributes
char buf [length]
char * dst
char * end
void * user_context
Detailed Description
template<int type, uint64_t length = 1024>
class Halide::Runtime::Internal::Printer< type, length >
Definition at line 113 of file runtime_internal.h.
Constructor & Destructor Documentation
template<int type, uint64_t length = 1024> Halide::Runtime::Internal::Printer< type, length >::Printer (void * ctx) inline
Definition at line 119 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::end.
template<int type, uint64_t length = 1024> Halide::Runtime::Internal::Printer< type, length >::~Printer () inline
Definition at line 173 of file runtime_internal.h.
References Halide::Runtime::Internal::BasicPrinter, Halide::Runtime::Internal::Printer< type, length >::buf, Halide::Runtime::Internal::ErrorPrinter, halide_error(), halide_print(), and Halide::Runtime::Internal::Printer< type, length >::user_context.
Member Function Documentation
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (const char * arg) inline
Definition at line 123 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_string_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (int64_t arg) inline
Definition at line 128 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_int64_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (int32_t arg) inline
Definition at line 133 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_int64_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (uint64_t arg) inline
Definition at line 138 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_uint64_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (uint32_t arg) inline
Definition at line 143 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_uint64_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (double arg) inline
Definition at line 148 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_double_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (float arg) inline
Definition at line 153 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_double_to_string().
template<int type, uint64_t length = 1024> Printer& Halide::Runtime::Internal::Printer< type, length >::operator<< (const void * arg) inline
Definition at line 158 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, Halide::Runtime::Internal::Printer< type, length >::end, and halide_pointer_to_string().
template<int type, uint64_t length = 1024> const char* Halide::Runtime::Internal::Printer< type, length >::str () inline
Definition at line 164 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::buf.
template<int type, uint64_t length = 1024> uint64_t Halide::Runtime::Internal::Printer< type, length >::size () const inline
Definition at line 169 of file runtime_internal.h.
References Halide::Runtime::Internal::Printer< type, length >::dst, and Halide::Runtime::Internal::Printer< type, length >::end.
Member Data Documentation
template<int type, uint64_t length = 1024> char Halide::Runtime::Internal::Printer< type, length >::buf[length]
Definition at line 115 of file runtime_internal.h.
Referenced by Halide::Runtime::Internal::Printer< type, length >::str(), and Halide::Runtime::Internal::Printer< type, length >::~Printer().
template<int type, uint64_t length = 1024> char* Halide::Runtime::Internal::Printer< type, length >::dst
Definition at line 116 of file runtime_internal.h.
Referenced by Halide::Runtime::Internal::Printer< type, length >::operator<<(), and Halide::Runtime::Internal::Printer< type, length >::size().
template<int type, uint64_t length = 1024> char * Halide::Runtime::Internal::Printer< type, length >::end
Definition at line 116 of file runtime_internal.h.
Referenced by Halide::Runtime::Internal::Printer< type, length >::operator<<(), Halide::Runtime::Internal::Printer< type, length >::Printer(), and Halide::Runtime::Internal::Printer< type, length >::size().
template<int type, uint64_t length = 1024> void* Halide::Runtime::Internal::Printer< type, length >::user_context
Definition at line 117 of file runtime_internal.h.
Referenced by Halide::Runtime::Internal::Printer< type, length >::~Printer().
The documentation for this class was generated from the following file:
runtime_internal.h