Halide: Halide::Internal::SmallArray< T, elements_on_stack > Class Template Reference
Halide::Internal::SmallArray< T, elements_on_stack > Class Template Reference
#include <SmallArray.h>
Public Member Functions
SmallArray ()
SmallArray (size_t size)
~SmallArray ()
template<int N>
SmallArray (const SmallArray< T, N > &other)
SmallArray (const std::vector< T > &vec)
SmallArray< T,
elements_on_stack > & operator= (const SmallArray< T, elements_on_stack > &other)
size_t size () const
T & operator[] (size_t x)
const T & operator[] (size_t x) const
const T * begin () const
const T * end () const
bool empty () const
void push_back (const T &x)
operator std::vector< T > () const
Detailed Description
template<typename T, int elements_on_stack = 4>
class Halide::Internal::SmallArray< T, elements_on_stack >
Definition at line 10 of file SmallArray.h.
Constructor & Destructor Documentation
template<typename T, int elements_on_stack = 4> Halide::Internal::SmallArray< T, elements_on_stack >::SmallArray () [inline]
Definition at line 16 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> Halide::Internal::SmallArray< T, elements_on_stack >::SmallArray (size_t size) [inline]
Definition at line 18 of file SmallArray.h.
References Halide::Internal::SmallArray< T, elements_on_stack >::size().
template<typename T, int elements_on_stack = 4> Halide::Internal::SmallArray< T, elements_on_stack >::~SmallArray () [inline]
Definition at line 24 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> template<int N> Halide::Internal::SmallArray< T, elements_on_stack >::SmallArray (const SmallArray< T, N > & other) [inline]
Definition at line 29 of file SmallArray.h.
References Halide::Internal::SmallArray< T, elements_on_stack >::size().
template<typename T, int elements_on_stack = 4> Halide::Internal::SmallArray< T, elements_on_stack >::SmallArray (const std::vector< T > & vec) [inline]
Definition at line 56 of file SmallArray.h.
Member Function Documentation
template<typename T, int elements_on_stack = 4> SmallArray<T, elements_on_stack>& Halide::Internal::SmallArray< T, elements_on_stack >::operator= (const SmallArray< T, elements_on_stack > & other) [inline]
Definition at line 70 of file SmallArray.h.
References NULL.
template<typename T, int elements_on_stack = 4> size_t Halide::Internal::SmallArray< T, elements_on_stack >::size () const [inline]
Definition at line 101 of file SmallArray.h.
Referenced by Halide::Internal::SmallArray< T, elements_on_stack >::operator std::vector< T >(), and Halide::Internal::SmallArray< T, elements_on_stack >::SmallArray().
template<typename T, int elements_on_stack = 4> T& Halide::Internal::SmallArray< T, elements_on_stack >::operator[] (size_t x) [inline]
Definition at line 105 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> const T& Halide::Internal::SmallArray< T, elements_on_stack >::operator[] (size_t x) const [inline]
Definition at line 110 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> const T* Halide::Internal::SmallArray< T, elements_on_stack >::begin () const [inline]
Definition at line 115 of file SmallArray.h.
Referenced by Halide::Internal::SmallArray< T, elements_on_stack >::end().
template<typename T, int elements_on_stack = 4> const T* Halide::Internal::SmallArray< T, elements_on_stack >::end () const [inline]
Definition at line 120 of file SmallArray.h.
References Halide::Internal::SmallArray< T, elements_on_stack >::begin().
template<typename T, int elements_on_stack = 4> bool Halide::Internal::SmallArray< T, elements_on_stack >::empty () const [inline]
Definition at line 124 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> void Halide::Internal::SmallArray< T, elements_on_stack >::push_back (const T & x) [inline]
Definition at line 128 of file SmallArray.h.
template<typename T, int elements_on_stack = 4> Halide::Internal::SmallArray< T, elements_on_stack >::operator std::vector< T > () const [inline]
Definition at line 158 of file SmallArray.h.
References Halide::Internal::SmallArray< T, elements_on_stack >::size().
The documentation for this class was generated from the following file:
SmallArray.h