Halide: Halide::Internal::GeneratorStub Class Reference
Halide::Internal::GeneratorStub Class Reference
#include <Generator.h>
Inherits Halide::NamesInterface.
Public Member Functions
GeneratorStub ()=default
GeneratorStub (GeneratorStub &&that)
GeneratorStub & operator= (GeneratorStub &&that)
Target get_target () const
template<typename T >
GeneratorStub & set_schedule_param (const std::string &name, const T &value)
GeneratorStub & schedule ()
operator Func () const
template<typename... Args>
FuncRef operator() (Args &&...args) const
template<typename ExprOrVar >
FuncRef operator() (std::vector< ExprOrVar > args) const
Realization realize (std::vector< int32_t > sizes)
template<typename... Args, typename std::enable_if< NoRealizations< Args...>::value >::type * = nullptr>
Realization realize (Args &&...args)
void realize (Realization r)
virtual ~GeneratorStub ()
Protected Types
typedef std::function
< std::unique_ptr
< GeneratorBase >const
GeneratorContext &, const
std::map< std::string,
std::string > &)> GeneratorFactory
Protected Types inherited from Halide::NamesInterface
using Expr = Halide::Expr
using ExternFuncArgument = Halide::ExternFuncArgument
using Func = Halide::Func
using GeneratorContext = Halide::GeneratorContext
using ImageParam = Halide::ImageParam
using LoopLevel = Halide::LoopLevel
using Pipeline = Halide::Pipeline
using RDom = Halide::RDom
using TailStrategy = Halide::TailStrategy
using Target = Halide::Target
using Tuple = Halide::Tuple
using Type = Halide::Type
using Var = Halide::Var
using NameMangling = Halide::NameMangling
template<typename T >
using GeneratorParam = Halide::GeneratorParam< T >
template<typename T >
using ScheduleParam = Halide::ScheduleParam< T >
template<typename T = void>
using Buffer = Halide::Buffer< T >
template<typename T >
using Param = Halide::Param< T >
Protected Member Functions
EXPORT GeneratorStub (const GeneratorContext &context, GeneratorFactory generator_factory, const std::map< std::string, std::string > &generator_params, const std::vector< std::vector< Internal::StubInput >> &inputs)
ScheduleParamBase & get_schedule_param (const std::string &n) const
Func get_output (const std::string &n) const
template<typename T2 >
T2 get_output_buffer (const std::string &n) const
std::vector< Func > get_output_vector (const std::string &n) const
bool has_generator () const
EXPORT void verify_same_funcs (const Func &a, const Func &b)
EXPORT void verify_same_funcs (const std::vector< Func > &a, const std::vector< Func > &b)
template<typename T2 >
void verify_same_funcs (const StubOutputBuffer< T2 > &a, const StubOutputBuffer< T2 > &b)
Static Protected Member Functions
template<typename Ratio >
static double ratio_to_double ()
static std::vector< StubInput > to_stub_input_vector (const Expr &e)
static std::vector< StubInput > to_stub_input_vector (const Func &f)
template<typename T = void>
static std::vector< StubInput > to_stub_input_vector (const StubInputBuffer< T > &b)
template<typename T >
static std::vector< StubInput > to_stub_input_vector (const std::vector< T > &v)
Static Protected Member Functions inherited from Halide::NamesInterface
template<typename T >
static Expr cast (Expr e)
static Expr cast (Halide::Type t, Expr e)
static Type Bool (int lanes=1)
static Type Float (int bits, int lanes=1)
static Type Int (int bits, int lanes=1)
static Type UInt (int bits, int lanes=1)
Detailed Description
Definition at line 2791 of file Generator.h.
Member Typedef Documentation
typedef std::function<std::unique_ptr<GeneratorBase>const GeneratorContext&, const std::map<std::string, std::string>&)> Halide::Internal::GeneratorStub::GeneratorFactory protected
Definition at line 2851 of file Generator.h.
Constructor & Destructor Documentation
Halide::Internal::GeneratorStub::GeneratorStub () default
Halide::Internal::GeneratorStub::GeneratorStub (GeneratorStub && that) inline
Definition at line 2797 of file Generator.h.
virtual Halide::Internal::GeneratorStub::~GeneratorStub () inline virtual
Definition at line 2848 of file Generator.h.
EXPORT Halide::Internal::GeneratorStub::GeneratorStub (const GeneratorContext & context, GeneratorFactory generator_factory, const std::map< std::string, std::string > & generator_params, const std::vector< std::vector< Internal::StubInput >> & inputs) protected
Member Function Documentation
GeneratorStub& Halide::Internal::GeneratorStub::operator= (GeneratorStub && that) inline
Definition at line 2800 of file Generator.h.
References Halide::Internal::GIOBase::generator.
Target Halide::Internal::GeneratorStub::get_target () const inline
Definition at line 2805 of file Generator.h.
References Halide::Internal::GIOBase::generator, and Halide::Internal::GeneratorBase::get_target().
template<typename T > GeneratorStub& Halide::Internal::GeneratorStub::set_schedule_param (const std::string & name, const T & value) inline
Definition at line 2808 of file Generator.h.
References Halide::Internal::GIOBase::generator, and Halide::Internal::GeneratorBase::set_schedule_param().
GeneratorStub& Halide::Internal::GeneratorStub::schedule () inline
Definition at line 2813 of file Generator.h.
References Halide::Internal::GeneratorBase::call_schedule(), and Halide::Internal::GIOBase::generator.
Halide::Internal::GeneratorStub::operator Func () const inline
Definition at line 2819 of file Generator.h.
template<typename... Args> FuncRef Halide::Internal::GeneratorStub::operator() (Args &&... args) const inline
Definition at line 2824 of file Generator.h.
template<typename ExprOrVar > FuncRef Halide::Internal::GeneratorStub::operator() (std::vector< ExprOrVar > args) const inline
Definition at line 2829 of file Generator.h.
Realization Halide::Internal::GeneratorStub::realize (std::vector< int32_t > sizes) inline
Definition at line 2833 of file Generator.h.
References Halide::Internal::GIOBase::generator, and Halide::Internal::GeneratorBase::realize().
template<typename... Args, typename std::enable_if< NoRealizations< Args...>::value >::type * = nullptr> Realization Halide::Internal::GeneratorStub::realize (Args &&... args) inline
Definition at line 2840 of file Generator.h.
References Halide::Internal::GIOBase::generator, and Halide::Internal::GeneratorBase::realize().
void Halide::Internal::GeneratorStub::realize (Realization r) inline
Definition at line 2844 of file Generator.h.
References Halide::Internal::GIOBase::generator, and Halide::Internal::GeneratorBase::realize().
ScheduleParamBase& Halide::Internal::GeneratorStub::get_schedule_param (const std::string & n) const inline protected
Definition at line 2858 of file Generator.h.
References Halide::Internal::GIOBase::generator.
Func Halide::Internal::GeneratorStub::get_output (const std::string & n) const inline protected
Definition at line 2864 of file Generator.h.
References Halide::Internal::GIOBase::generator.
template<typename T2 > T2 Halide::Internal::GeneratorStub::get_output_buffer (const std::string & n) const inline protected
Definition at line 2869 of file Generator.h.
References Halide::Internal::GIOBase::generator.
std::vector<Func> Halide::Internal::GeneratorStub::get_output_vector (const std::string & n) const inline protected
Definition at line 2873 of file Generator.h.
References Halide::Internal::GIOBase::generator.
bool Halide::Internal::GeneratorStub::has_generator () const inline protected
Definition at line 2877 of file Generator.h.
References Halide::Internal::GIOBase::generator.
template<typename Ratio > static double Halide::Internal::GeneratorStub::ratio_to_double () inline static protected
Definition at line 2882 of file Generator.h.
static std::vector<StubInput> Halide::Internal::GeneratorStub::to_stub_input_vector (const Expr & e) inline static protected
Definition at line 2886 of file Generator.h.
static std::vector<StubInput> Halide::Internal::GeneratorStub::to_stub_input_vector (const Func & f) inline static protected
Definition at line 2890 of file Generator.h.
template<typename T = void> static std::vector<StubInput> Halide::Internal::GeneratorStub::to_stub_input_vector (const StubInputBuffer< T > & b) inline static protected
Definition at line 2895 of file Generator.h.
template<typename T > static std::vector<StubInput> Halide::Internal::GeneratorStub::to_stub_input_vector (const std::vector< T > & v) inline static protected
Definition at line 2900 of file Generator.h.
EXPORT void Halide::Internal::GeneratorStub::verify_same_funcs (const Func & a, const Func & b) protected
EXPORT void Halide::Internal::GeneratorStub::verify_same_funcs (const std::vector< Func > & a, const std::vector< Func > & b) protected
template<typename T2 > void Halide::Internal::GeneratorStub::verify_same_funcs (const StubOutputBuffer< T2 > & a, const StubOutputBuffer< T2 > & b) inline protected
Definition at line 2910 of file Generator.h.
References Halide::Internal::StubOutputBufferBase::f.
The documentation for this class was generated from the following file:
Generator.h