Halide: Halide::Buffer< T, D >::Dimension Class Reference
Halide::Buffer< T, D >::Dimension Class Reference
Read-only access to the shape.
#include <HalideBuffer.h>
Classes
struct iterator
An iterator class, so that you can iterate over coordinates in a dimensions using a range-based for loop.
Public Member Functions
ALWAYS_INLINE int min () const
The lowest coordinate in this dimension.
ALWAYS_INLINE int stride () const
The number of elements in memory you have to step over to increment this coordinate by one.
ALWAYS_INLINE int extent () const
The extent of the image along this dimension.
ALWAYS_INLINE int max () const
The highest coordinate in this dimension.
ALWAYS_INLINE iterator begin () const
An iterator that points to the min coordinate.
ALWAYS_INLINE iterator end () const
An iterator that points to one past the max coordinate.
Dimension (const buffer_t &buf, int idx)
Detailed Description
template<typename T, int D>
class Halide::Buffer< T, D >::Dimension
Read-only access to the shape.
Definition at line 284 of file HalideBuffer.h.
Constructor & Destructor Documentation
template<typename T, int D> Halide::Buffer< T, D >::Dimension::Dimension (const buffer_t & buf, int idx) inline
Definition at line 328 of file HalideBuffer.h.
Member Function Documentation
template<typename T, int D> ALWAYS_INLINE int Halide::Buffer< T, D >::Dimension::min () const inline
The lowest coordinate in this dimension.
Definition at line 289 of file HalideBuffer.h.
References buffer_t::min.
Referenced by Halide::Buffer< T, D >::Dimension::begin(), Halide::Buffer< T, D >::copy(), Halide::Buffer< T, D >::crop(), Halide::Buffer< T, D >::Dimension::end(), Halide::Buffer< T, D >::left(), Halide::Buffer< T, D >::Dimension::max(), Halide::Buffer< T, D >::min(), Halide::Buffer< T, D >::slice(), and Halide::Buffer< T, D >::top().
template<typename T, int D> ALWAYS_INLINE int Halide::Buffer< T, D >::Dimension::stride () const inline
The number of elements in memory you have to step over to increment this coordinate by one.
Definition at line 295 of file HalideBuffer.h.
References buffer_t::stride.
Referenced by Halide::Buffer< T, D >::begin(), Halide::Buffer< T, D >::copy(), Halide::Buffer< T, D >::crop(), Halide::Buffer< T, D >::end(), Halide::Buffer< T, D >::slice(), and Halide::Buffer< T, D >::stride().
template<typename T, int D> ALWAYS_INLINE int Halide::Buffer< T, D >::Dimension::extent () const inline
The extent of the image along this dimension.
Definition at line 300 of file HalideBuffer.h.
References buffer_t::extent.
Referenced by Halide::Buffer< T, D >::begin(), Halide::Buffer< T, D >::channels(), Halide::Buffer< T, D >::check_overflow(), Halide::Buffer< T, D >::Dimension::end(), Halide::Buffer< T, D >::end(), Halide::Buffer< T, D >::extent(), Halide::Buffer< T, D >::height(), Halide::Buffer< T, D >::Dimension::max(), Halide::Buffer< T, D >::number_of_elements(), and Halide::Buffer< T, D >::width().
template<typename T, int D> ALWAYS_INLINE int Halide::Buffer< T, D >::Dimension::max () const inline
The highest coordinate in this dimension.
Definition at line 305 of file HalideBuffer.h.
References Halide::Buffer< T, D >::Dimension::extent(), and Halide::Buffer< T, D >::Dimension::min().
Referenced by Halide::Buffer< T, D >::bottom(), and Halide::Buffer< T, D >::right().
template<typename T, int D> ALWAYS_INLINE iterator Halide::Buffer< T, D >::Dimension::begin () const inline
An iterator that points to the min coordinate.
Definition at line 319 of file HalideBuffer.h.
References Halide::Buffer< T, D >::Dimension::min().
template<typename T, int D> ALWAYS_INLINE iterator Halide::Buffer< T, D >::Dimension::end () const inline
An iterator that points to one past the max coordinate.
Definition at line 324 of file HalideBuffer.h.
References Halide::Buffer< T, D >::Dimension::extent(), and Halide::Buffer< T, D >::Dimension::min().
The documentation for this class was generated from the following file:
HalideBuffer.h