Halide: Halide::Internal::GeneratorParam_Type< T > Class Template Reference
Halide::Internal::GeneratorParam_Type< T > Class Template Reference
#include <Generator.h>
Inherits Halide::Internal::GeneratorParam_Enum< T >.
Public Member Functions
GeneratorParam_Type (const std::string &name, const T &value)
std::string call_to_string (const std::string &v) const override
std::string get_c_type () const override
std::string get_template_type () const override
std::string get_template_value () const override
std::string get_default_value () const override
std::string get_type_decls () const override
Public Member Functions inherited from Halide::Internal::GeneratorParam_Enum< T >
GeneratorParam_Enum (const std::string &name, const T &value, const std::map< std::string, T > &enum_map)
void set_from_string (const std::string &new_value_string) override
std::string to_string () const override
Public Member Functions inherited from Halide::Internal::GeneratorParamImpl< T >
GeneratorParamImpl (const std::string &name, const T &value)
T value () const
operator T () const
operator Expr () const
Public Member Functions inherited from Halide::Internal::GeneratorParamBase
EXPORT GeneratorParamBase (const std::string &name)
virtual EXPORT ~GeneratorParamBase ()
void set (const std::string &new_value)
void set (const char *new_value)
Additional Inherited Members
Public Types inherited from Halide::Internal::GeneratorParamImpl< T >
using type = T
Public Attributes inherited from Halide::Internal::GeneratorParamBase
const std::string name
Protected Member Functions inherited from Halide::Internal::GeneratorParamImpl< T >
virtual void set_impl (const T &new_value)
Protected Member Functions inherited from Halide::Internal::GeneratorParamBase
EXPORT void check_value_readable () const
EXPORT void check_value_writable () const
virtual bool is_synthetic_param () const
EXPORT void fail_wrong_type (const char *type)
Detailed Description
template<typename T>
class Halide::Internal::GeneratorParam_Type< T >
Definition at line 652 of file Generator.h.
Constructor & Destructor Documentation
template<typename T > Halide::Internal::GeneratorParam_Type< T >::GeneratorParam_Type (const std::string & name, const T & value) inline
Definition at line 654 of file Generator.h.
Member Function Documentation
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::call_to_string (const std::string & v) const inline override virtual
Reimplemented from Halide::Internal::GeneratorParam_Enum< T >.
Definition at line 657 of file Generator.h.
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::get_c_type () const inline override virtual
Reimplemented from Halide::Internal::GeneratorParam_Enum< T >.
Definition at line 661 of file Generator.h.
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::get_template_type () const inline override virtual
Reimplemented from Halide::Internal::GeneratorParamBase.
Definition at line 665 of file Generator.h.
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::get_template_value () const inline override virtual
Reimplemented from Halide::Internal::GeneratorParamBase.
Definition at line 669 of file Generator.h.
References Halide::Internal::halide_type_to_c_type(), and Halide::Internal::GeneratorParamImpl< T >::value().
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::get_default_value () const inline override virtual
Reimplemented from Halide::Internal::GeneratorParam_Enum< T >.
Definition at line 673 of file Generator.h.
References Halide::Internal::halide_type_to_c_source(), and Halide::Internal::GeneratorParamImpl< T >::value().
template<typename T > std::string Halide::Internal::GeneratorParam_Type< T >::get_type_decls () const inline override virtual
Reimplemented from Halide::Internal::GeneratorParam_Enum< T >.
Definition at line 677 of file Generator.h.
The documentation for this class was generated from the following file:
Generator.h