Halide: Halide::Runtime::Internal::Synchronization::fast_mutex Class Reference
Halide::Runtime::Internal::Synchronization::fast_mutex Class Reference
#include <synchronization_common.h>
Public Member Functions
ALWAYS_INLINE void lock ()
ALWAYS_INLINE void unlock ()
ALWAYS_INLINE bool make_parked_if_locked ()
ALWAYS_INLINE void make_parked ()
Detailed Description
Definition at line 880 of file synchronization_common.h.
Member Function Documentation
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_mutex::lock () inline
Definition at line 939 of file synchronization_common.h.
References lock_bit.
Referenced by halide_mutex_lock().
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_mutex::unlock () inline
Definition at line 948 of file synchronization_common.h.
References lock_bit.
Referenced by halide_mutex_unlock(), and Halide::Runtime::Internal::Synchronization::wait_parking_control_before_sleep().
ALWAYS_INLINE bool Halide::Runtime::Internal::Synchronization::fast_mutex::make_parked_if_locked () inline
Definition at line 957 of file synchronization_common.h.
References parked_bit.
Referenced by Halide::Runtime::Internal::Synchronization::broadcast_parking_control_validate().
ALWAYS_INLINE void Halide::Runtime::Internal::Synchronization::fast_mutex::make_parked () inline
Definition at line 972 of file synchronization_common.h.
References Halide::Runtime::Internal::Synchronization::signal_parking_control_unpark(), and WEAK.
Referenced by Halide::Runtime::Internal::Synchronization::broadcast_parking_control_requeue_callback().
The documentation for this class was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/runtime/synchronization_common.h