Halide: Halide::Internal::GeneratorOutputBase Class Reference
Halide::Internal::GeneratorOutputBase Class Reference
#include <Generator.h>
Inherits Halide::Internal::GIOBase.
Inherited by Halide::Internal::GeneratorOutputImpl< T >.
EXPORT GeneratorOutputBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Forward schedule-related methods to the underlying Func.
EXPORT GeneratorOutputBase (const std::string &name, IOKind kind, const std::vector< Type > &t, int d)
Forward schedule-related methods to the underlying Func.
EXPORT ~GeneratorOutputBase () override
Forward schedule-related methods to the underlying Func.
EXPORT void init_internals ()
Forward schedule-related methods to the underlying Func.
EXPORT void resize (size_t size)
Forward schedule-related methods to the underlying Func.
virtual std::string get_c_type () const
Forward schedule-related methods to the underlying Func.
EXPORT void check_value_writable () const override
Forward schedule-related methods to the underlying Func.
NO_INLINE Func & get_func_ref ()
Forward schedule-related methods to the underlying Func.
NO_INLINE const Func & get_func_ref () const
Forward schedule-related methods to the underlying Func.
Additional Inherited Members
Public Member Functions inherited from Halide::Internal::GIOBase
EXPORT bool array_size_defined () const
EXPORT size_t array_size () const
virtual EXPORT bool is_array () const
EXPORT const std::string & name () const
EXPORT IOKind kind () const
EXPORT bool types_defined () const
EXPORT const std::vector< Type > & types () const
EXPORT Type type () const
EXPORT bool dimensions_defined () const
EXPORT int dimensions () const
EXPORT const std::vector< Func > & funcs () const
EXPORT const std::vector< Expr > & exprs () const
Protected Member Functions inherited from Halide::Internal::GIOBase
EXPORT GIOBase (size_t array_size, const std::string &name, IOKind kind, const std::vector< Type > &types, int dimensions)
virtual EXPORT ~GIOBase ()
EXPORT std::string array_name (size_t i) const
virtual EXPORT void verify_internals () const
EXPORT void check_matching_array_size (size_t size)
EXPORT void check_matching_type_and_dim (const std::vector< Type > &t, int d)
template<typename ElemType >
const std::vector< ElemType > & get_values () const
virtual bool allow_synthetic_generator_params () const
virtual Parameter parameter () const
template<>
const std::vector< Expr > & get_values () const
template<>
const std::vector< Func > & get_values () const
Protected Attributes inherited from Halide::Internal::GIOBase
int array_size_
const std::string name_
const IOKind kind_
std::vector< Type > types_
int dimensions_
std::vector< Func > funcs_
std::vector< Expr > exprs_
GeneratorBase * generator {nullptr}
Detailed Description
Definition at line 1593 of file Generator.h.
Constructor & Destructor Documentation
EXPORT Halide::Internal::GeneratorOutputBase::GeneratorOutputBase (size_t array_size, const std::string & name, IOKind kind, const std::vector< Type > & t, int d) protected
Forward schedule-related methods to the underlying Func.
EXPORT Halide::Internal::GeneratorOutputBase::GeneratorOutputBase (const std::string & name, IOKind kind, const std::vector< Type > & t, int d) protected
Forward schedule-related methods to the underlying Func.
EXPORT Halide::Internal::GeneratorOutputBase::~GeneratorOutputBase () override protected
Forward schedule-related methods to the underlying Func.
Member Function Documentation
EXPORT void Halide::Internal::GeneratorOutputBase::init_internals () protected
Forward schedule-related methods to the underlying Func.
EXPORT void Halide::Internal::GeneratorOutputBase::resize (size_t size) protected
Forward schedule-related methods to the underlying Func.
Referenced by Halide::Internal::GeneratorOutputImpl< T >::resize().
virtual std::string Halide::Internal::GeneratorOutputBase::get_c_type () const inline protected virtual
Forward schedule-related methods to the underlying Func.
Definition at line 1681 of file Generator.h.
EXPORT void Halide::Internal::GeneratorOutputBase::check_value_writable () const override protected virtual
Forward schedule-related methods to the underlying Func.
Implements Halide::Internal::GIOBase.
NO_INLINE Func& Halide::Internal::GeneratorOutputBase::get_func_ref () inline protected
Forward schedule-related methods to the underlying Func.
Definition at line 1687 of file Generator.h.
References Halide::Internal::GIOBase::array_size(), Halide::Internal::GIOBase::exprs_, Halide::Internal::GIOBase::funcs_, internal_assert, Halide::Internal::GIOBase::kind(), and Halide::Internal::Scalar.
NO_INLINE const Func& Halide::Internal::GeneratorOutputBase::get_func_ref () const inline protected
Forward schedule-related methods to the underlying Func.
Definition at line 1693 of file Generator.h.
References Halide::Internal::GIOBase::array_size(), Halide::Internal::GIOBase::exprs_, Halide::Internal::GIOBase::funcs_, internal_assert, Halide::Internal::GIOBase::kind(), and Halide::Internal::Scalar.
The documentation for this class was generated from the following file:
Generator.h