Halide: Halide::Internal::Definition Class Reference
Halide::Internal::Definition Class Reference
A Function definition which can either represent a init or an update definition.
#include <Definition.h>
Public Member Functions
EXPORT Definition (const IntrusivePtr< DefinitionContents > &)
Construct a Definition from an existing DefinitionContents pointer.
EXPORT Definition (const std::vector< Expr > &args, const std::vector< Expr > &values, const ReductionDomain &rdom, bool is_init)
Construct a Definition with the supplied args, values, and reduction domain.
EXPORT Definition ()
Construct an empty Definition.
EXPORT Definition get_copy () const
Return a copy of this Definition.
bool same_as (const Definition &other) const
Equality of identity.
EXPORT bool is_init () const
Is this an init definition; otherwise it's an update definition.
EXPORT void accept (IRVisitor *) const
Pass an IRVisitor through to all Exprs referenced in the definition.
EXPORT void mutate (IRMutator2 *)
Pass an IRMutator2 through to all Exprs referenced in the definition.
EXPORT std::vector< Expr > split_predicate () const
Split predicate into vector of ANDs.
EXPORT const std::vector< Expr > & args () const
Get the default (no-specialization) arguments (left-hand-side) of the definition.
EXPORT std::vector< Expr > & args ()
Get the default (no-specialization) arguments (left-hand-side) of the definition.
EXPORT const std::vector< Expr > & values () const
Get the default (no-specialization) right-hand-side of the definition.
EXPORT std::vector< Expr > & values ()
Get the default (no-specialization) right-hand-side of the definition.
EXPORT const Expr & predicate () const
Get the predicate on the definition.
EXPORT Expr & predicate ()
Get the predicate on the definition.
EXPORT const StageSchedule & schedule () const
Get the default (no-specialization) stage-specific schedule associated with this definition.
EXPORT StageSchedule & schedule ()
Get the default (no-specialization) stage-specific schedule associated with this definition.
EXPORT const std::vector< Specialization > & specializations () const
You may create several specialized versions of a func with different stage-specific schedules.
EXPORT std::vector< Specialization > & specializations ()
You may create several specialized versions of a func with different stage-specific schedules.
EXPORT const Specialization & add_specialization (Expr condition)
You may create several specialized versions of a func with different stage-specific schedules.
Detailed Description
A Function definition which can either represent a init or an update definition.
A function may have different definitions due to specialization, which are stored in 'specializations' (Not possible from the front-end, but some scheduling directives may potentially cause this divergence to occur). Although init definition may have multiple values (RHS) per specialization, it must have the same LHS (i.e. same pure dimension variables). The update definition, on the other hand, may have different LHS/RHS per specialization. Note that, while the Expr in LHS/RHS may be different across specializations, they must have the same number of dimensions and the same pure dimensions.
Definition at line 38 of file Definition.h.
Constructor & Destructor Documentation
Definition() [1/3]
EXPORT Halide::Internal::Definition::Definition (const IntrusivePtr< DefinitionContents > &) explicit
Construct a Definition from an existing DefinitionContents pointer.
Must be non-null
Definition() [2/3]
EXPORT Halide::Internal::Definition::Definition (const std::vector< Expr > & args, const std::vector< Expr > & values, const ReductionDomain & rdom, bool is_init)
Construct a Definition with the supplied args, values, and reduction domain.
Definition() [3/3]
EXPORT Halide::Internal::Definition::Definition ()
Construct an empty Definition.
By default, it is a init definition.
Member Function Documentation
get_copy()
EXPORT Definition Halide::Internal::Definition::get_copy () const
Return a copy of this Definition.
same_as()
bool Halide::Internal::Definition::same_as (const Definition & other) const inline
Equality of identity.
Definition at line 57 of file Definition.h.
References EXPORT, and Halide::Internal::IntrusivePtr< T >::same_as().
is_init()
EXPORT bool Halide::Internal::Definition::is_init () const
Is this an init definition; otherwise it's an update definition.
accept()
EXPORT void Halide::Internal::Definition::accept (IRVisitor *) const
Pass an IRVisitor through to all Exprs referenced in the definition.
mutate()
EXPORT void Halide::Internal::Definition::mutate (IRMutator2 *)
Pass an IRMutator2 through to all Exprs referenced in the definition.
args() [1/2]
EXPORT const std::vector<Expr>& Halide::Internal::Definition::args () const
Get the default (no-specialization) arguments (left-hand-side) of the definition.
Referenced by Halide::Stage::Stage().
args() [2/2]
EXPORT std::vector<Expr>& Halide::Internal::Definition::args ()
Get the default (no-specialization) arguments (left-hand-side) of the definition.
values() [1/2]
EXPORT const std::vector<Expr>& Halide::Internal::Definition::values () const
Get the default (no-specialization) right-hand-side of the definition.
values() [2/2]
EXPORT std::vector<Expr>& Halide::Internal::Definition::values ()
Get the default (no-specialization) right-hand-side of the definition.
predicate() [1/2]
EXPORT const Expr& Halide::Internal::Definition::predicate () const
Get the predicate on the definition.
predicate() [2/2]
EXPORT Expr& Halide::Internal::Definition::predicate ()
Get the predicate on the definition.
split_predicate()
EXPORT std::vector<Expr> Halide::Internal::Definition::split_predicate () const
Split predicate into vector of ANDs.
If there is no predicate (i.e. this definition is always valid), this returns an empty vector.
schedule() [1/2]
EXPORT const StageSchedule& Halide::Internal::Definition::schedule () const
Get the default (no-specialization) stage-specific schedule associated with this definition.
Referenced by Halide::Stage::get_schedule(), and Halide::Stage::Stage().
schedule() [2/2]
EXPORT StageSchedule& Halide::Internal::Definition::schedule ()
Get the default (no-specialization) stage-specific schedule associated with this definition.
specializations() [1/2]
EXPORT const std::vector<Specialization>& Halide::Internal::Definition::specializations () const
You may create several specialized versions of a func with different stage-specific schedules.
They trigger when the condition is true. See Func::specialize
specializations() [2/2]
EXPORT std::vector<Specialization>& Halide::Internal::Definition::specializations ()
You may create several specialized versions of a func with different stage-specific schedules.
They trigger when the condition is true. See Func::specialize
add_specialization()
EXPORT const Specialization& Halide::Internal::Definition::add_specialization (Expr condition)
You may create several specialized versions of a func with different stage-specific schedules.
They trigger when the condition is true. See Func::specialize
The documentation for this class was generated from the following file:
Definition.h