Halide: Halide::OutputImageParam Class Reference
Halide::OutputImageParam Class Reference
A handle on the output buffer of a pipeline.
#include <OutputImageParam.h>
Inherited by Halide::ImageParam.
Classes
struct Dimension
Public Member Functions
OutputImageParam ()
Construct a null image parameter handle.
EXPORT OutputImageParam (const Internal::Parameter &p, Argument::Kind k)
Construct an OutputImageParam that wraps an Internal Parameter object.
EXPORT const std::string & name () const
Get the name of this Param.
EXPORT Type type () const
Get the type of the image data this Param refers to.
EXPORT bool defined () const
Is this parameter handle non-nullptr.
EXPORT Dimension dim (int i)
Get a handle on one of the dimensions for the purposes of inspecting or constraining its min, extent, or stride.
EXPORT const Dimension dim (int i) const
Get a handle on one of the dimensions for the purposes of inspecting its min, extent, or stride.
EXPORT int host_alignment () const
Get the alignment of the host pointer in bytes.
EXPORT OutputImageParam & set_host_alignment (int)
Set the expected alignment of the host pointer in bytes.
EXPORT int dimensions () const
Get the dimensionality of this image parameter.
EXPORT Expr left () const
Get an expression giving the minimum coordinate in dimension 0, which by convention is the coordinate of the left edge of the image.
EXPORT Expr right () const
Get an expression giving the maximum coordinate in dimension 0, which by convention is the coordinate of the right edge of the image.
EXPORT Expr top () const
Get an expression giving the minimum coordinate in dimension 1, which by convention is the top of the image.
EXPORT Expr bottom () const
Get an expression giving the maximum coordinate in dimension 1, which by convention is the bottom of the image.
EXPORT Expr width () const
Get an expression giving the extent in dimension 0, which by convention is the width of the image.
EXPORT Expr height () const
Get an expression giving the extent in dimension 1, which by convention is the height of the image.
EXPORT Expr channels () const
Get an expression giving the extent in dimension 2, which by convention is the channel-count of the image.
EXPORT Internal::Parameter parameter () const
Get at the internal parameter object representing this ImageParam.
EXPORT operator Argument () const
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
EXPORT operator ExternFuncArgument () const
Using a param as the argument to an external stage treats it as an Expr.
OutputImageParam set_min (int i, Expr e)
Get or constrain the shape of the dimensions.
OutputImageParam set_extent (int i, Expr e)
Get or constrain the shape of the dimensions.
OutputImageParam set_bounds (int i, Expr a, Expr b)
Get or constrain the shape of the dimensions.
OutputImageParam set_stride (int i, Expr e)
Get or constrain the shape of the dimensions.
Expr min (int i) const
Get or constrain the shape of the dimensions.
Expr extent (int i) const
Get or constrain the shape of the dimensions.
Expr stride (int i) const
Get or constrain the shape of the dimensions.
Protected Member Functions
void add_implicit_args_if_placeholder (std::vector< Expr > &args, Expr last_arg, int total_args, bool *placeholder_seen) const
Protected Attributes
Internal::Parameter param
A reference-counted handle on the internal parameter object.
Argument::Kind kind
Is this an input or an output? OutputImageParam is the base class for both.
Detailed Description
A handle on the output buffer of a pipeline.
Used to make static promises about the output size and stride.
Definition at line 16 of file OutputImageParam.h.
Constructor & Destructor Documentation
Halide::OutputImageParam::OutputImageParam () inline
Construct a null image parameter handle.
Definition at line 107 of file OutputImageParam.h.
EXPORT Halide::OutputImageParam::OutputImageParam (const Internal::Parameter & p, Argument::Kind k)
Construct an OutputImageParam that wraps an Internal Parameter object.
Member Function Documentation
void Halide::OutputImageParam::add_implicit_args_if_placeholder (std::vector< Expr > & args, Expr last_arg, int total_args, bool * placeholder_seen) const protected
EXPORT const std::string& Halide::OutputImageParam::name () const
Get the name of this Param.
EXPORT Type Halide::OutputImageParam::type () const
Get the type of the image data this Param refers to.
EXPORT bool Halide::OutputImageParam::defined () const
Is this parameter handle non-nullptr.
EXPORT Dimension Halide::OutputImageParam::dim (int i)
Get a handle on one of the dimensions for the purposes of inspecting or constraining its min, extent, or stride.
Referenced by extent(), min(), set_bounds(), set_extent(), set_min(), set_stride(), and stride().
EXPORT const Dimension Halide::OutputImageParam::dim (int i) const
Get a handle on one of the dimensions for the purposes of inspecting its min, extent, or stride.
OutputImageParam Halide::OutputImageParam::set_min (int i, Expr e) inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 132 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::set_min().
OutputImageParam Halide::OutputImageParam::set_extent (int i, Expr e) inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 133 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::set_extent().
OutputImageParam Halide::OutputImageParam::set_bounds (int i, Expr a, Expr b) inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 134 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::set_bounds().
OutputImageParam Halide::OutputImageParam::set_stride (int i, Expr e) inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 135 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::set_stride().
Expr Halide::OutputImageParam::min (int i) const inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 136 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::min().
Expr Halide::OutputImageParam::extent (int i) const inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 137 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::extent().
Expr Halide::OutputImageParam::stride (int i) const inline
Get or constrain the shape of the dimensions.
Soon to be deprecated. Do not use.
Definition at line 138 of file OutputImageParam.h.
References dim(), and Halide::OutputImageParam::Dimension::stride().
EXPORT int Halide::OutputImageParam::host_alignment () const
Get the alignment of the host pointer in bytes.
Defaults to the size of type.
EXPORT OutputImageParam& Halide::OutputImageParam::set_host_alignment (int)
Set the expected alignment of the host pointer in bytes.
EXPORT int Halide::OutputImageParam::dimensions () const
Get the dimensionality of this image parameter.
EXPORT Expr Halide::OutputImageParam::left () const
Get an expression giving the minimum coordinate in dimension 0, which by convention is the coordinate of the left edge of the image.
EXPORT Expr Halide::OutputImageParam::right () const
Get an expression giving the maximum coordinate in dimension 0, which by convention is the coordinate of the right edge of the image.
EXPORT Expr Halide::OutputImageParam::top () const
Get an expression giving the minimum coordinate in dimension 1, which by convention is the top of the image.
EXPORT Expr Halide::OutputImageParam::bottom () const
Get an expression giving the maximum coordinate in dimension 1, which by convention is the bottom of the image.
EXPORT Expr Halide::OutputImageParam::width () const
Get an expression giving the extent in dimension 0, which by convention is the width of the image.
EXPORT Expr Halide::OutputImageParam::height () const
Get an expression giving the extent in dimension 1, which by convention is the height of the image.
EXPORT Expr Halide::OutputImageParam::channels () const
Get an expression giving the extent in dimension 2, which by convention is the channel-count of the image.
EXPORT Internal::Parameter Halide::OutputImageParam::parameter () const
Get at the internal parameter object representing this ImageParam.
EXPORT Halide::OutputImageParam::operator Argument () const
Construct the appropriate argument matching this parameter, for the purpose of generating the right type signature when statically compiling halide pipelines.
EXPORT Halide::OutputImageParam::operator ExternFuncArgument () const
Using a param as the argument to an external stage treats it as an Expr.
Member Data Documentation
Internal::Parameter Halide::OutputImageParam::param protected
A reference-counted handle on the internal parameter object.
Definition at line 19 of file OutputImageParam.h.
Argument::Kind Halide::OutputImageParam::kind protected
Is this an input or an output? OutputImageParam is the base class for both.
Definition at line 22 of file OutputImageParam.h.
The documentation for this class was generated from the following file:
OutputImageParam.h