Halide: Halide::Internal::CodeGen_PyTorch Class Reference
Halide::Internal::CodeGen_PyTorch Class Reference
This class emits C++ code to wrap a Halide pipeline so that it can be used as a C++ extension operator in PyTorch.
#include <CodeGen_PyTorch.h>
Inherits Halide::Internal::IRPrinter.
Public Member Functions
CodeGen_PyTorch (std::ostream &dest, Target target, std::string name)
~CodeGen_PyTorch ()=default
void compile (const Module &module)
Emit the PyTorch C++ wrapper for the Halide pipeline.
const Target & get_target () const
The target we're generating code for.
Public Member Functions inherited from Halide::Internal::IRPrinter
virtual ~IRPrinter ()
IRPrinter (std::ostream &)
Construct an IRPrinter pointed at a given output stream (e.g.
void print (Expr)
emit an expression on the output stream
void print (Stmt)
emit a statement on the output stream
void print_list (const std::vector< Expr > &exprs)
emit a comma delimited list of exprs, without any leading or trailing punctuation.
Public Member Functions inherited from Halide::Internal::IRVisitor
IRVisitor ()
virtual ~IRVisitor ()
Static Public Member Functions
static void test ()
Static Public Member Functions inherited from Halide::Internal::IRPrinter
static void test ()
Protected Member Functions
virtual void compile (const LoweredFunc &func, bool is_cuda)
Protected Member Functions inherited from Halide::Internal::IRPrinter
void do_indent ()
Emit spaces according to the current indentation level.
void visit (const IntImm *) override
void visit (const UIntImm *) override
void visit (const FloatImm *) override
void visit (const StringImm *) override
void visit (const Cast *) override
void visit (const Variable *) override
void visit (const Add *) override
void visit (const Sub *) override
void visit (const Mul *) override
void visit (const Div *) override
void visit (const Mod *) override
void visit (const Min *) override
void visit (const Max *) override
void visit (const EQ *) override
void visit (const NE *) override
void visit (const LT *) override
void visit (const LE *) override
void visit (const GT *) override
void visit (const GE *) override
void visit (const And *) override
void visit (const Or *) override
void visit (const Not *) override
void visit (const Select *) override
void visit (const Load *) override
void visit (const Ramp *) override
void visit (const Broadcast *) override
void visit (const Call *) override
void visit (const Let *) override
void visit (const LetStmt *) override
void visit (const AssertStmt *) override
void visit (const ProducerConsumer *) override
void visit (const For *) override
void visit (const Acquire *) override
void visit (const Store *) override
void visit (const Provide *) override
void visit (const Allocate *) override
void visit (const Free *) override
void visit (const Realize *) override
void visit (const Block *) override
void visit (const Fork *) override
void visit (const IfThenElse *) override
void visit (const Evaluate *) override
void visit (const Shuffle *) override
void visit (const Prefetch *) override
Protected Attributes
Target target
The target being generated for.
std::string cpp_header
Protected Attributes inherited from Halide::Internal::IRPrinter
std::ostream & stream
The stream we're outputting on.
int indent
The current indentation level, useful for pretty-printing statements.
Detailed Description
This class emits C++ code to wrap a Halide pipeline so that it can be used as a C++ extension operator in PyTorch.
Definition at line 29 of file CodeGen_PyTorch.h.
Constructor & Destructor Documentation
CodeGen_PyTorch()
Halide::Internal::CodeGen_PyTorch::CodeGen_PyTorch (std::ostream & dest, Target target, std::string name)
~CodeGen_PyTorch()
Halide::Internal::CodeGen_PyTorch::~CodeGen_PyTorch () default
Member Function Documentation
compile() [1/2]
void Halide::Internal::CodeGen_PyTorch::compile (const Module & module)
Emit the PyTorch C++ wrapper for the Halide pipeline.
Referenced by get_target().
get_target()
const Target& Halide::Internal::CodeGen_PyTorch::get_target () const inline
The target we're generating code for.
Definition at line 38 of file CodeGen_PyTorch.h.
References compile(), target, and test().
test()
static void Halide::Internal::CodeGen_PyTorch::test () static
Referenced by get_target().
compile() [2/2]
virtual void Halide::Internal::CodeGen_PyTorch::compile (const LoweredFunc & func, bool is_cuda) protected virtual
Member Data Documentation
target
Target Halide::Internal::CodeGen_PyTorch::target protected
The target being generated for.
Definition at line 46 of file CodeGen_PyTorch.h.
Referenced by get_target().
cpp_header
std::string Halide::Internal::CodeGen_PyTorch::cpp_header protected
Definition at line 48 of file CodeGen_PyTorch.h.
The documentation for this class was generated from the following file:
CodeGen_PyTorch.h