Halide: Halide::Derivative Class Reference
Halide::Derivative Class Reference
Helper structure storing the adjoints Func.
#include <Derivative.h>
Public Types
using FuncKey = std::pair< std::string, int >
Public Member Functions
Derivative (const std::map< FuncKey, Func > &adjoints_in)
Derivative (std::map< FuncKey, Func > &&adjoints_in)
Func operator() (const Func &func, int update_id=-1) const
Func operator() (const Buffer<> &buffer) const
Func operator() (const Param<> &param) const
Detailed Description
Helper structure storing the adjoints Func.
Use d(func) or d(buffer) to obtain the derivative Func.
Definition at line 22 of file Derivative.h.
Member Typedef Documentation
using Halide::Derivative::FuncKey = std::pair<std::string, int>
Definition at line 25 of file Derivative.h.
Constructor & Destructor Documentation
Halide::Derivative::Derivative (const std::map< FuncKey, Func > & adjoints_in) inline explicit
Definition at line 27 of file Derivative.h.
Halide::Derivative::Derivative (std::map< FuncKey, Func > && adjoints_in) inline explicit
Definition at line 30 of file Derivative.h.
References operator()(), and Halide::propagate_adjoints().
Member Function Documentation
Func Halide::Derivative::operator() (const Func & func, int update_id = -1) const
Referenced by Derivative().
Func Halide::Derivative::operator() (const Buffer<> & buffer) const
Func Halide::Derivative::operator() (const Param<> & param) const
The documentation for this class was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Derivative.h