Halide: Halide::Internal::CodeGen_C Class Reference
Halide::Internal::CodeGen_C Class Reference
This class emits C++ code equivalent to a halide Stmt.
#include <CodeGen_C.h>
Inherits Halide::Internal::IRPrinter.
Inherited by Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_GLSLBase, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
Classes
struct Allocation
Public Types
enum OutputKind { CHeader, CPlusPlusHeader, CImplementation, CPlusPlusImplementation }
Public Member Functions
CodeGen_C (std::ostream &dest, Target target, OutputKind output_kind=CImplementation, const std::string &include_guard="")
Initialize a C code generator pointing at a particular output stream (e.g.
~CodeGen_C () override
void compile (const Module &module)
Emit the declarations contained in the module as C code.
const Target & get_target () const
The target we're generating code for.
void add_common_macros (std::ostream &dest)
Add common macros to be shared across all backends.
Public Member Functions inherited from Halide::Internal::IRPrinter
virtual ~IRPrinter ()
IRPrinter (std::ostream &)
Construct an IRPrinter pointed at a given output stream (e.g.
void print (Expr)
emit an expression on the output stream
void print (Stmt)
emit a statement on the output stream
void print_list (const std::vector< Expr > &exprs)
emit a comma delimited list of exprs, without any leading or trailing punctuation.
Public Member Functions inherited from Halide::Internal::IRVisitor
IRVisitor ()
virtual ~IRVisitor ()
Static Public Member Functions
static void test ()
Static Public Member Functions inherited from Halide::Internal::IRPrinter
static void test ()
Protected Types
enum AppendSpaceIfNeeded { DoNotAppendSpace, AppendSpace }
Protected Member Functions
std::string print_expr (Expr)
Emit an expression as an assignment, then return the id of the resulting var.
std::string print_cast_expr (const Type &, Expr)
Like print_expr, but cast the Expr to the given Type.
void print_stmt (Stmt)
Emit a statement.
void create_assertion (const std::string &id_cond, const std::string &id_msg)
void create_assertion (const std::string &id_cond, Expr message)
void create_assertion (Expr cond, Expr message)
virtual std::string print_type (Type, AppendSpaceIfNeeded space_option=DoNotAppendSpace)
Emit the C name for a halide type.
virtual std::string print_reinterpret (Type, Expr)
Emit a statement to reinterpret an expression as another type.
virtual std::string print_name (const std::string &)
Emit a version of a string that is a valid identifier in C (.
virtual void add_vector_typedefs (const std::set< Type > &vector_types)
Add typedefs for vector types.
virtual std::string print_extern_call (const Call *op)
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
std::string print_scalarized_expr (Expr e)
Convert a vector Expr into a series of scalar Exprs, then reassemble into vector of original type.
virtual std::string print_assignment (Type t, const std::string &rhs)
Emit an SSA-style assignment, and set id to the freshly generated name.
bool is_header ()
Return true if only generating an interface, which may be extern "C" or C++.
bool is_c_plus_plus_interface ()
Return true if generating C++ linkage.
void open_scope ()
Open a new C scope (i.e.
void close_scope (const std::string &comment)
Close a C scope (i.e.
void forward_declare_type_if_needed (const Type &t)
If the Type is a handle type, emit a forward-declaration for it if we haven't already.
void set_name_mangling_mode (NameMangling mode)
void visit (const Variable *) override
void visit (const IntImm *) override
void visit (const UIntImm *) override
void visit (const StringImm *) override
void visit (const FloatImm *) override
void visit (const Cast *) override
void visit (const Add *) override
void visit (const Sub *) override
void visit (const Mul *) override
void visit (const Div *) override
void visit (const Mod *) override
void visit (const Max *) override
void visit (const Min *) override
void visit (const EQ *) override
void visit (const NE *) override
void visit (const LT *) override
void visit (const LE *) override
void visit (const GT *) override
void visit (const GE *) override
void visit (const And *) override
void visit (const Or *) override
void visit (const Not *) override
void visit (const Call *) override
void visit (const Select *) override
void visit (const Load *) override
void visit (const Store *) override
void visit (const Let *) override
void visit (const LetStmt *) override
void visit (const AssertStmt *) override
void visit (const ProducerConsumer *) override
void visit (const For *) override
void visit (const Ramp *) override
void visit (const Broadcast *) override
void visit (const Provide *) override
void visit (const Allocate *) override
void visit (const Free *) override
void visit (const Realize *) override
void visit (const IfThenElse *) override
void visit (const Evaluate *) override
void visit (const Shuffle *) override
void visit (const Prefetch *) override
void visit (const Fork *) override
void visit (const Acquire *) override
void visit_binop (Type t, Expr a, Expr b, const char *op)
virtual void compile (const LoweredFunc &func)
Emit a declaration.
virtual void compile (const Buffer<> &buffer)
Emit a declaration.
Protected Member Functions inherited from Halide::Internal::IRPrinter
void do_indent ()
Emit spaces according to the current indentation level.
void visit (const IntImm *) override
void visit (const UIntImm *) override
void visit (const FloatImm *) override
void visit (const StringImm *) override
void visit (const Cast *) override
void visit (const Variable *) override
void visit (const Add *) override
void visit (const Sub *) override
void visit (const Mul *) override
void visit (const Div *) override
void visit (const Mod *) override
void visit (const Min *) override
void visit (const Max *) override
void visit (const EQ *) override
void visit (const NE *) override
void visit (const LT *) override
void visit (const LE *) override
void visit (const GT *) override
void visit (const GE *) override
void visit (const And *) override
void visit (const Or *) override
void visit (const Not *) override
void visit (const Select *) override
void visit (const Load *) override
void visit (const Ramp *) override
void visit (const Broadcast *) override
void visit (const Call *) override
void visit (const Let *) override
void visit (const LetStmt *) override
void visit (const AssertStmt *) override
void visit (const ProducerConsumer *) override
void visit (const For *) override
void visit (const Acquire *) override
void visit (const Store *) override
void visit (const Provide *) override
void visit (const Allocate *) override
void visit (const Free *) override
void visit (const Realize *) override
void visit (const Block *) override
void visit (const Fork *) override
void visit (const IfThenElse *) override
void visit (const Evaluate *) override
void visit (const Shuffle *) override
void visit (const Prefetch *) override
Static Protected Member Functions
template<typename T >
static std::string with_sep (const std::vector< T > &v, const std::string &sep)
template<typename T >
static std::string with_commas (const std::vector< T > &v)
Protected Attributes
std::string id
An ID for the most recently generated ssa variable.
Target target
The target being generated for.
OutputKind output_kind
Controls whether this instance is generating declarations or definitions and whether the interface us extern "C" or C++.
std::map< std::string, std::string > cache
A cache of generated values in scope.
Scope< Allocation > allocations
Track the types of allocations to avoid unnecessary casts.
Scope heap_allocations
Track which allocations actually went on the heap.
bool have_user_context
True if there is a void * __user_context parameter in the arguments.
bool extern_c_open
Track current calling convention scope.
bool uses_gpu_for_loops
True if at least one gpu-based for loop is used.
std::set< const halide_handle_cplusplus_type * > forward_declared
Track which handle types have been forward-declared already.
Protected Attributes inherited from Halide::Internal::IRPrinter
std::ostream & stream
The stream we're outputting on.
int indent
The current indentation level, useful for pretty-printing statements.
Detailed Description
This class emits C++ code equivalent to a halide Stmt.
It's mostly the same as an IRPrinter, but it's wrapped in a function definition, and some things are handled differently to be valid C++.
Definition at line 24 of file CodeGen_C.h.
Member Enumeration Documentation
OutputKind
enum Halide::Internal::CodeGen_C::OutputKind
Enumerator
CHeader
CPlusPlusHeader
CImplementation
CPlusPlusImplementation
Definition at line 26 of file CodeGen_C.h.
AppendSpaceIfNeeded
enum Halide::Internal::CodeGen_C::AppendSpaceIfNeeded protected
Enumerator
DoNotAppendSpace
AppendSpace
Definition at line 86 of file CodeGen_C.h.
Constructor & Destructor Documentation
CodeGen_C()
Halide::Internal::CodeGen_C::CodeGen_C (std::ostream & dest, Target target, OutputKind output_kind = CImplementation, const std::string & include_guard = "")
Initialize a C code generator pointing at a particular output stream (e.g.
a file, or std::cout)
~CodeGen_C()
Halide::Internal::CodeGen_C::~CodeGen_C () override
Member Function Documentation
compile() [1/3]
void Halide::Internal::CodeGen_C::compile (const Module & module)
Emit the declarations contained in the module as C code.
Referenced by get_target().
get_target()
const Target& Halide::Internal::CodeGen_C::get_target () const inline
The target we're generating code for.
Definition at line 45 of file CodeGen_C.h.
References add_common_macros(), compile(), target, and test().
test()
static void Halide::Internal::CodeGen_C::test () static
Referenced by get_target().
add_common_macros()
void Halide::Internal::CodeGen_C::add_common_macros (std::ostream & dest)
Add common macros to be shared across all backends.
Referenced by get_target().
compile() [2/3]
virtual void Halide::Internal::CodeGen_C::compile (const LoweredFunc & func) protected virtual
Emit a declaration.
compile() [3/3]
virtual void Halide::Internal::CodeGen_C::compile (const Buffer<> & buffer) protected virtual
Emit a declaration.
print_expr()
std::string Halide::Internal::CodeGen_C::print_expr (Expr) protected
Emit an expression as an assignment, then return the id of the resulting var.
print_cast_expr()
std::string Halide::Internal::CodeGen_C::print_cast_expr (const Type & , Expr) protected
Like print_expr, but cast the Expr to the given Type.
print_stmt()
void Halide::Internal::CodeGen_C::print_stmt (Stmt) protected
Emit a statement.
create_assertion() [1/3]
void Halide::Internal::CodeGen_C::create_assertion (const std::string & id_cond, const std::string & id_msg) protected
create_assertion() [2/3]
void Halide::Internal::CodeGen_C::create_assertion (const std::string & id_cond, Expr message) protected
create_assertion() [3/3]
void Halide::Internal::CodeGen_C::create_assertion (Expr cond, Expr message) protected
print_type()
virtual std::string Halide::Internal::CodeGen_C::print_type (Type , AppendSpaceIfNeeded space_option = DoNotAppendSpace) protected virtual
Emit the C name for a halide type.
If space_option is AppendSpace, and there should be a space between the type and the next token, one is appended. (This allows both "int foo" and "Foo *foo" to be formatted correctly. Otherwise the latter is "Foo * foo".)
Reimplemented in Halide::Internal::CodeGen_GLSLBase, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
print_reinterpret()
virtual std::string Halide::Internal::CodeGen_C::print_reinterpret (Type , Expr) protected virtual
Emit a statement to reinterpret an expression as another type.
Reimplemented in Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
print_name()
virtual std::string Halide::Internal::CodeGen_C::print_name (const std::string &) protected virtual
Emit a version of a string that is a valid identifier in C (.
is replaced with _)
Reimplemented in Halide::Internal::CodeGen_GLSLBase.
add_vector_typedefs()
virtual void Halide::Internal::CodeGen_C::add_vector_typedefs (const std::set< Type > & vector_types) protected virtual
Add typedefs for vector types.
Not needed for OpenCL, might use different syntax for other C-like languages.
Reimplemented in Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
print_extern_call()
virtual std::string Halide::Internal::CodeGen_C::print_extern_call (const Call * op) protected virtual
Bottleneck to allow customization of calls to generic Extern/PureExtern calls.
Reimplemented in Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
print_scalarized_expr()
std::string Halide::Internal::CodeGen_C::print_scalarized_expr (Expr e) protected
Convert a vector Expr into a series of scalar Exprs, then reassemble into vector of original type.
print_assignment()
virtual std::string Halide::Internal::CodeGen_C::print_assignment (Type t, const std::string & rhs) protected virtual
Emit an SSA-style assignment, and set id to the freshly generated name.
Return id.
Reimplemented in Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C.
is_header()
bool Halide::Internal::CodeGen_C::is_header () inline protected
Return true if only generating an interface, which may be extern "C" or C++.
Definition at line 118 of file CodeGen_C.h.
References CHeader, and CPlusPlusHeader.
is_c_plus_plus_interface()
bool Halide::Internal::CodeGen_C::is_c_plus_plus_interface () inline protected
Return true if generating C++ linkage.
Definition at line 124 of file CodeGen_C.h.
References close_scope(), CPlusPlusHeader, CPlusPlusImplementation, and open_scope().
open_scope()
void Halide::Internal::CodeGen_C::open_scope () protected
Open a new C scope (i.e.
throw in a brace, increase the indent)
Referenced by is_c_plus_plus_interface().
close_scope()
void Halide::Internal::CodeGen_C::close_scope (const std::string & comment) protected
Close a C scope (i.e.
throw in an end brace, decrease the indent)
Referenced by is_c_plus_plus_interface().
forward_declare_type_if_needed()
void Halide::Internal::CodeGen_C::forward_declare_type_if_needed (const Type & t) protected
If the Type is a handle type, emit a forward-declaration for it if we haven't already.
set_name_mangling_mode()
void Halide::Internal::CodeGen_C::set_name_mangling_mode (NameMangling mode) protected
visit() [1/43]
void Halide::Internal::CodeGen_C::visit (const Variable *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Referenced by Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C::CodeGen_D3D12Compute_C(), Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C::CodeGen_Metal_C(), and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C::CodeGen_OpenCL_C().
visit() [2/43]
void Halide::Internal::CodeGen_C::visit (const IntImm *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C, and Halide::Internal::CodeGen_GLSLBase.
visit() [3/43]
void Halide::Internal::CodeGen_C::visit (const UIntImm *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase.
visit() [4/43]
void Halide::Internal::CodeGen_C::visit (const StringImm *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [5/43]
void Halide::Internal::CodeGen_C::visit (const FloatImm *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase.
visit() [6/43]
void Halide::Internal::CodeGen_C::visit (const Cast *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [7/43]
void Halide::Internal::CodeGen_C::visit (const Add *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [8/43]
void Halide::Internal::CodeGen_C::visit (const Sub *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [9/43]
void Halide::Internal::CodeGen_C::visit (const Mul *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [10/43]
void Halide::Internal::CodeGen_C::visit (const Div *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_GLSLBase.
visit() [11/43]
void Halide::Internal::CodeGen_C::visit (const Mod *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_GLSLBase.
visit() [12/43]
void Halide::Internal::CodeGen_C::visit (const Max *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_GLSLBase.
visit() [13/43]
void Halide::Internal::CodeGen_C::visit (const Min *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_GLSLBase.
visit() [14/43]
void Halide::Internal::CodeGen_C::visit (const EQ *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [15/43]
void Halide::Internal::CodeGen_C::visit (const NE *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [16/43]
void Halide::Internal::CodeGen_C::visit (const LT *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [17/43]
void Halide::Internal::CodeGen_C::visit (const LE *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [18/43]
void Halide::Internal::CodeGen_C::visit (const GT *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [19/43]
void Halide::Internal::CodeGen_C::visit (const GE *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [20/43]
void Halide::Internal::CodeGen_C::visit (const And *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [21/43]
void Halide::Internal::CodeGen_C::visit (const Or *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [22/43]
void Halide::Internal::CodeGen_C::visit (const Not *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [23/43]
void Halide::Internal::CodeGen_C::visit (const Call *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_GLSLBase, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [24/43]
void Halide::Internal::CodeGen_C::visit (const Select *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [25/43]
void Halide::Internal::CodeGen_C::visit (const Load *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [26/43]
void Halide::Internal::CodeGen_C::visit (const Store *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [27/43]
void Halide::Internal::CodeGen_C::visit (const Let *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL.
visit() [28/43]
void Halide::Internal::CodeGen_C::visit (const LetStmt *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [29/43]
void Halide::Internal::CodeGen_C::visit (const AssertStmt *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [30/43]
void Halide::Internal::CodeGen_C::visit (const ProducerConsumer *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [31/43]
void Halide::Internal::CodeGen_C::visit (const For *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [32/43]
void Halide::Internal::CodeGen_C::visit (const Ramp *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [33/43]
void Halide::Internal::CodeGen_C::visit (const Broadcast *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [34/43]
void Halide::Internal::CodeGen_C::visit (const Provide *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [35/43]
void Halide::Internal::CodeGen_C::visit (const Allocate *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [36/43]
void Halide::Internal::CodeGen_C::visit (const Free *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_Metal_Dev::CodeGen_Metal_C, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [37/43]
void Halide::Internal::CodeGen_C::visit (const Realize *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [38/43]
void Halide::Internal::CodeGen_C::visit (const IfThenElse *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [39/43]
void Halide::Internal::CodeGen_C::visit (const Evaluate *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSL, Halide::Internal::CodeGen_D3D12Compute_Dev::CodeGen_D3D12Compute_C, and Halide::Internal::CodeGen_OpenGLCompute_Dev::CodeGen_OpenGLCompute_C.
visit() [40/43]
void Halide::Internal::CodeGen_C::visit (const Shuffle *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
Reimplemented in Halide::Internal::CodeGen_GLSLBase, and Halide::Internal::CodeGen_OpenCL_Dev::CodeGen_OpenCL_C.
visit() [41/43]
void Halide::Internal::CodeGen_C::visit (const Prefetch *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [42/43]
void Halide::Internal::CodeGen_C::visit (const Fork *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit() [43/43]
void Halide::Internal::CodeGen_C::visit (const Acquire *) override protected virtual
Reimplemented from Halide::Internal::IRVisitor.
visit_binop()
void Halide::Internal::CodeGen_C::visit_binop (Type t, Expr a, Expr b, const char * op) protected
with_sep()
template<typename T > static std::string Halide::Internal::CodeGen_C::with_sep (const std::vector< T > & v, const std::string & sep) inline static protected
Definition at line 212 of file CodeGen_C.h.
with_commas()
template<typename T > static std::string Halide::Internal::CodeGen_C::with_commas (const std::vector< T > & v) inline static protected
Definition at line 224 of file CodeGen_C.h.
Member Data Documentation
id
std::string Halide::Internal::CodeGen_C::id protected
An ID for the most recently generated ssa variable.
Definition at line 60 of file CodeGen_C.h.
target
Target Halide::Internal::CodeGen_C::target protected
The target being generated for.
Definition at line 63 of file CodeGen_C.h.
Referenced by get_target().
output_kind
OutputKind Halide::Internal::CodeGen_C::output_kind protected
Controls whether this instance is generating declarations or definitions and whether the interface us extern "C" or C++.
Definition at line 67 of file CodeGen_C.h.
cache
std::map<std::string, std::string> Halide::Internal::CodeGen_C::cache protected
A cache of generated values in scope.
Definition at line 70 of file CodeGen_C.h.
allocations
Scope<Allocation> Halide::Internal::CodeGen_C::allocations protected
Track the types of allocations to avoid unnecessary casts.
Definition at line 140 of file CodeGen_C.h.
heap_allocations
Scope Halide::Internal::CodeGen_C::heap_allocations protected
Track which allocations actually went on the heap.
Definition at line 143 of file CodeGen_C.h.
have_user_context
bool Halide::Internal::CodeGen_C::have_user_context protected
True if there is a void * __user_context parameter in the arguments.
Definition at line 146 of file CodeGen_C.h.
extern_c_open
bool Halide::Internal::CodeGen_C::extern_c_open protected
Track current calling convention scope.
Definition at line 149 of file CodeGen_C.h.
uses_gpu_for_loops
bool Halide::Internal::CodeGen_C::uses_gpu_for_loops protected
True if at least one gpu-based for loop is used.
Definition at line 152 of file CodeGen_C.h.
forward_declared
std::set<const halide_handle_cplusplus_type *> Halide::Internal::CodeGen_C::forward_declared protected
Track which handle types have been forward-declared already.
Definition at line 155 of file CodeGen_C.h.
The documentation for this class was generated from the following file:
CodeGen_C.h