Halide: Halide::ScheduleHandle Class Reference
Halide::ScheduleHandle Class Reference
A temporary wrapper around a schedule used for common schedule manipulations.
#include <Func.h>
Public Member Functions
ScheduleHandle (Internal::Schedule s)
EXPORT ScheduleHandle & cuda_threads (VarOrRVar thread_x)
EXPORT ScheduleHandle & cuda_threads (VarOrRVar thread_x, VarOrRVar thread_y)
EXPORT ScheduleHandle & cuda_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z)
EXPORT ScheduleHandle & cuda_blocks (VarOrRVar block_x)
EXPORT ScheduleHandle & cuda_blocks (VarOrRVar block_x, VarOrRVar block_y)
EXPORT ScheduleHandle & cuda_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z)
EXPORT ScheduleHandle & cuda (VarOrRVar block_x, VarOrRVar thread_x)
EXPORT ScheduleHandle & cuda (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y)
EXPORT ScheduleHandle & cuda (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z)
EXPORT ScheduleHandle & cuda_tile (VarOrRVar x, int x_size)
EXPORT ScheduleHandle & cuda_tile (VarOrRVar x, VarOrRVar y, int x_size, int y_size)
EXPORT ScheduleHandle & cuda_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, int x_size, int y_size, int z_size)
EXPORT ScheduleHandle & split (VarOrRVar old, VarOrRVar outer, VarOrRVar inner, Expr factor)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & fuse (VarOrRVar inner, VarOrRVar outer, VarOrRVar fused)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & serial (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & parallel (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & vectorize (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & unroll (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & parallel (VarOrRVar var, Expr task_size)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & vectorize (VarOrRVar var, int factor)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & unroll (VarOrRVar var, int factor)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & tile (VarOrRVar x, VarOrRVar y, VarOrRVar xo, VarOrRVar yo, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & tile (VarOrRVar x, VarOrRVar y, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (const std::vector< VarOrRVar > &vars)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4, VarOrRVar t5)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4, VarOrRVar t5, VarOrRVar t6)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & rename (VarOrRVar old_name, VarOrRVar new_name)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle specialize (Expr condition)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_threads (VarOrRVar thread_x, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_single_thread (GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_blocks (VarOrRVar block_x, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu (VarOrRVar block_x, VarOrRVar thread_x, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_tile (VarOrRVar x, Expr x_size, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_tile (VarOrRVar x, VarOrRVar y, Expr x_size, Expr y_size, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, Expr x_size, Expr y_size, Expr z_size, GPUAPI gpu_api=GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
EXPORT ScheduleHandle & allow_race_conditions ()
Scheduling calls that control how the domain of this stage is traversed.
Detailed Description
A temporary wrapper around a schedule used for common schedule manipulations.
Definition at line 203 of file Func.h.
Constructor & Destructor Documentation
Halide::ScheduleHandle::ScheduleHandle (Internal::Schedule s) [inline]
Definition at line 209 of file Func.h.
References Halide::Internal::Schedule::touched().
Member Function Documentation
EXPORT ScheduleHandle& Halide::ScheduleHandle::split (VarOrRVar old, VarOrRVar outer, VarOrRVar inner, Expr factor)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::fuse (VarOrRVar inner, VarOrRVar outer, VarOrRVar fused)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::serial (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::parallel (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::vectorize (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
Examples:
tutorial/lesson_09_update_definitions.cpp.
EXPORT ScheduleHandle& Halide::ScheduleHandle::unroll (VarOrRVar var)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::parallel (VarOrRVar var, Expr task_size)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::vectorize (VarOrRVar var, int factor)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::unroll (VarOrRVar var, int factor)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::tile (VarOrRVar x, VarOrRVar y, VarOrRVar xo, VarOrRVar yo, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::tile (VarOrRVar x, VarOrRVar y, VarOrRVar xi, VarOrRVar yi, Expr xfactor, Expr yfactor)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (const std::vector< VarOrRVar > & vars)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4, VarOrRVar t5)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::reorder (VarOrRVar x, VarOrRVar y, VarOrRVar z, VarOrRVar w, VarOrRVar t1, VarOrRVar t2, VarOrRVar t3, VarOrRVar t4, VarOrRVar t5, VarOrRVar t6)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::rename (VarOrRVar old_name, VarOrRVar new_name)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle Halide::ScheduleHandle::specialize (Expr condition)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_threads (VarOrRVar thread_x, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
Referenced by cuda_threads().
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_single_thread (GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_blocks (VarOrRVar block_x, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
Referenced by cuda_blocks().
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu (VarOrRVar block_x, VarOrRVar thread_x, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
Referenced by cuda().
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_tile (VarOrRVar x, Expr x_size, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
Referenced by cuda_tile().
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_tile (VarOrRVar x, VarOrRVar y, Expr x_size, Expr y_size, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::gpu_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, Expr x_size, Expr y_size, Expr z_size, GPUAPI gpu_api = GPU_Default)
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::allow_race_conditions ()
Scheduling calls that control how the domain of this stage is traversed.
See the documentation for Func for the meanings.
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_threads (VarOrRVar thread_x) [inline]
Definition at line 282 of file Func.h.
References gpu_threads().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_threads (VarOrRVar thread_x, VarOrRVar thread_y) [inline]
Definition at line 285 of file Func.h.
References gpu_threads().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_threads (VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z) [inline]
Definition at line 288 of file Func.h.
References gpu_threads().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_blocks (VarOrRVar block_x) [inline]
Definition at line 292 of file Func.h.
References gpu_blocks().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_blocks (VarOrRVar block_x, VarOrRVar block_y) [inline]
Definition at line 295 of file Func.h.
References gpu_blocks().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_blocks (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z) [inline]
Definition at line 298 of file Func.h.
References gpu_blocks().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda (VarOrRVar block_x, VarOrRVar thread_x) [inline]
Definition at line 302 of file Func.h.
References gpu().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar thread_x, VarOrRVar thread_y) [inline]
Definition at line 305 of file Func.h.
References gpu().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda (VarOrRVar block_x, VarOrRVar block_y, VarOrRVar block_z, VarOrRVar thread_x, VarOrRVar thread_y, VarOrRVar thread_z) [inline]
Definition at line 309 of file Func.h.
References gpu().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_tile (VarOrRVar x, int x_size) [inline]
Definition at line 313 of file Func.h.
References gpu_tile().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_tile (VarOrRVar x, VarOrRVar y, int x_size, int y_size) [inline]
Definition at line 316 of file Func.h.
References gpu_tile().
EXPORT ScheduleHandle& Halide::ScheduleHandle::cuda_tile (VarOrRVar x, VarOrRVar y, VarOrRVar z, int x_size, int y_size, int z_size) [inline]
Definition at line 319 of file Func.h.
References gpu_tile().
The documentation for this class was generated from the following file:
Func.h