Halide: Halide::RVar Class Reference
Halide::RVar Class Reference
A reduction variable represents a single dimension of a reduction domain (RDom).
#include <RDom.h>
Public Member Functions
RVar ()
An empty reduction variable.
RVar (const std::string &n)
Construct an RVar with the given name.
RVar (Internal::ReductionDomain domain, int index)
Construct a reduction variable with the given name and bounds.
Expr min () const
The minimum value that this variable will take on.
Expr extent () const
The number that this variable will take on.
Internal::ReductionDomain domain () const
The reduction domain this is associated with.
const std::string & name () const
The name of this reduction variable.
operator Expr () const
Reduction variables can be used as expressions.
Detailed Description
A reduction variable represents a single dimension of a reduction domain (RDom).
Don't construct them directly, instead construct an RDom, and use RDom::operator[] to get at the variables. For single-dimensional reduction domains, you can just cast a single-dimensional RDom to an RVar.
Definition at line 29 of file RDom.h.
Constructor & Destructor Documentation
Halide::RVar::RVar () inline
An empty reduction variable.
Definition at line 40 of file RDom.h.
Referenced by Halide::RDom::same_as().
Halide::RVar::RVar (const std::string & n) inline explicit
Construct an RVar with the given name.
Definition at line 45 of file RDom.h.
Halide::RVar::RVar (Internal::ReductionDomain domain, int index) inline
Construct a reduction variable with the given name and bounds.
Must be a member of the given reduction domain.
Definition at line 51 of file RDom.h.
References extent(), and min().
Member Function Documentation
Expr Halide::RVar::min () const
The minimum value that this variable will take on.
Referenced by RVar().
Expr Halide::RVar::extent () const
The number that this variable will take on.
The maximum value of this variable will be min() + extent() - 1
Referenced by RVar().
Internal::ReductionDomain Halide::RVar::domain () const inline
The reduction domain this is associated with.
Definition at line 63 of file RDom.h.
References name().
const std::string& Halide::RVar::name () const
The name of this reduction variable.
Referenced by domain(), and Halide::VarOrRVar::name().
Halide::RVar::operator Expr () const
Reduction variables can be used as expressions.
The documentation for this class was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/RDom.h