Halide: PipelineContext Class Reference
PipelineContext Class Reference
#include <pipeline_context.h>
Public Member Functions
PipelineContext (int stack_alignment, int stack_size)
~PipelineContext ()
void set_priority (int priority)
int run (pipeline_argv_t function, void **args)
Detailed Description
Definition at line 14 of file pipeline_context.h.
Constructor & Destructor Documentation
PipelineContext()
PipelineContext::PipelineContext (int stack_alignment, int stack_size) inline
Definition at line 45 of file pipeline_context.h.
References qurt_cond_init(), and qurt_mutex_init().
~PipelineContext()
PipelineContext::~PipelineContext () inline
Definition at line 62 of file pipeline_context.h.
References free(), qurt_cond_destroy(), qurt_cond_signal(), qurt_mutex_destroy(), qurt_mutex_lock(), qurt_mutex_unlock(), and qurt_thread_join().
Member Function Documentation
set_priority()
void PipelineContext::set_priority (int priority) inline
Definition at line 79 of file pipeline_context.h.
References qurt_thread_set_priority().
run()
int PipelineContext::run (pipeline_argv_t function, void ** args) inline
Definition at line 88 of file pipeline_context.h.
References NULL, qurt_cond_signal(), qurt_cond_wait(), qurt_mutex_lock(), and qurt_mutex_unlock().
The documentation for this class was generated from the following file:
pipeline_context.h