Halide: Halide::Image< T > Class Template Reference
Halide::Image< T > Class Template Reference
A reference-counted handle on a dense multidimensional array containing scalar values of type T.
#include <Image.h>
Public Member Functions
Image ()
Construct an undefined image handle.
Image (const Buffer &buf)
Wrap a buffer in an Image object, so that we can directly access its pixels in a type-safe way.
Image (const Realization &r)
Wrap a single-element realization in an Image object.
Image (const buffer_t *b, const std::string &name="")
Wrap a buffer_t in an Image object, so that we can access its pixels.
void copy_to_host ()
Manually copy-back data to the host, if it's on a device.
void set_host_dirty (bool dirty=true)
Mark the buffer as dirty-on-host.
bool defined () const
Check if this image handle points to actual data.
int dimensions () const
Get the dimensionality of the data.
int extent (int dim) const
Get the size of a dimension.
int min (int dim) const
Get the min coordinate of a dimension.
void set_min (int m0, int m1=0, int m2=0, int m3=0)
Set the min coordinates of a dimension.
int stride (int dim) const
Get the number of elements in the buffer between two adjacent elements in the given dimension.
int width () const
Get the extent of dimension 0, which by convention we use as the width of the image.
int height () const
Get the extent of dimension 1, which by convention we use as the height of the image.
int channels () const
Get the extent of dimension 2, which by convention we use as the number of color channels (often 3).
int left () const
Get the minimum coordinate in dimension 0, which by convention is the coordinate of the left edge of the image.
int right () const
Get the maximum coordinate in dimension 0, which by convention is the coordinate of the right edge of the image.
int top () const
Get the minimum coordinate in dimension 1, which by convention is the top of the image.
int bottom () const
Get the maximum coordinate in dimension 1, which by convention is the bottom of the image.
T * data () const
Get a pointer to the element at the min location.
T operator() (int x) const
Assuming this image is one-dimensional, get the value of the element at position x.
T operator() (int x, int y) const
Assuming this image is two-dimensional, get the value of the element at position (x, y)
T operator() (int x, int y, int z) const
Assuming this image is three-dimensional, get the value of the element at position (x, y, z)
T operator() (int x, int y, int z, int w) const
Assuming this image is four-dimensional, get the value of the element at position (x, y, z, w)
T & operator() (int x)
Assuming this image is one-dimensional, get a reference to the element at position x.
T & operator() (int x, int y)
Assuming this image is two-dimensional, get a reference to the element at position (x, y)
T & operator() (int x, int y, int z)
Assuming this image is three-dimensional, get a reference to the element at position (x, y, z)
T & operator() (int x, int y, int z, int w)
Assuming this image is four-dimensional, get a reference to the element at position (x, y, z, w)
Expr operator() () const
Construct an expression which loads from this image.
buffer_t * raw_buffer () const
Get a pointer to the raw buffer_t that this image holds.
operator Buffer () const
Get a handle on the Buffer that this image holds.
operator Argument () const
Convert this image to an argument to a halide pipeline.
operator ExternFuncArgument () const
Convert this image to an argument to an extern stage.
operator Expr () const
Treating the image as an Expr is equivalent to call it with no arguments.
Image (int x, int y=0, int z=0, int w=0, const std::string &name="")
Allocate an image with the given dimensions.
Image (int x, int y, int z, const std::string &name)
Allocate an image with the given dimensions.
Image (int x, int y, const std::string &name)
Allocate an image with the given dimensions.
Image (int x, const std::string &name)
Allocate an image with the given dimensions.
Expr operator() (Expr x) const
Construct an expression which loads from this image.
Expr operator() (Expr x, Expr y) const
Construct an expression which loads from this image.
Expr operator() (Expr x, Expr y, Expr z) const
Construct an expression which loads from this image.
Expr operator() (Expr x, Expr y, Expr z, Expr w) const
Construct an expression which loads from this image.
Detailed Description
template<typename T>
class Halide::Image< T >
A reference-counted handle on a dense multidimensional array containing scalar values of type T.
Can be directly accessed and modified. May have up to four dimensions. Color images are represented as three-dimensional, with the third dimension being the color channel. In general we store color images in color-planes, as opposed to packed RGB, because this tends to vectorize more cleanly.
Examples:
tutorial/lesson_01_basics.cpp, tutorial/lesson_02_input_image.cpp, tutorial/lesson_03_debugging_1.cpp, tutorial/lesson_04_debugging_2.cpp, and tutorial/lesson_05_scheduling_1.cpp.
Definition at line 21 of file Image.h.
Constructor & Destructor Documentation
template<typename T> Halide::Image< T >::Image () [inline]
Construct an undefined image handle.
Definition at line 103 of file Image.h.
template<typename T> Halide::Image< T >::Image (int x, int y = 0, int z = 0, int w = 0, const std::string & name = "") [inline]
Allocate an image with the given dimensions.
Definition at line 107 of file Image.h.
template<typename T> Halide::Image< T >::Image (int x, int y, int z, const std::string & name) [inline]
Allocate an image with the given dimensions.
Definition at line 112 of file Image.h.
template<typename T> Halide::Image< T >::Image (int x, int y, const std::string & name) [inline]
Allocate an image with the given dimensions.
Definition at line 117 of file Image.h.
template<typename T> Halide::Image< T >::Image (int x, const std::string & name) [inline]
Allocate an image with the given dimensions.
Definition at line 122 of file Image.h.
template<typename T> Halide::Image< T >::Image (const Buffer & buf) [inline]
Wrap a buffer in an Image object, so that we can directly access its pixels in a type-safe way.
Definition at line 130 of file Image.h.
References Halide::Buffer::type().
template<typename T> Halide::Image< T >::Image (const Realization & r) [inline]
Wrap a single-element realization in an Image object.
Definition at line 140 of file Image.h.
References Halide::Buffer::type().
template<typename T> Halide::Image< T >::Image (const buffer_t * b, const std::string & name = "") [inline]
Wrap a buffer_t in an Image object, so that we can access its pixels.
Definition at line 151 of file Image.h.
Member Function Documentation
template<typename T> void Halide::Image< T >::copy_to_host () [inline]
Manually copy-back data to the host, if it's on a device.
This is done for you if you construct an image from a buffer, but you might need to call this if you realize a gpu kernel into an existing image
Definition at line 159 of file Image.h.
References Halide::Buffer::copy_to_host().
template<typename T> void Halide::Image< T >::set_host_dirty (bool dirty = true) [inline]
Mark the buffer as dirty-on-host.
is done for you if you construct an image from a buffer, but you might need to call this if you realize a gpu kernel into an existing image, or modify the data via some other back-door.
Definition at line 167 of file Image.h.
References Halide::Buffer::set_host_dirty().
template<typename T> bool Halide::Image< T >::defined () const [inline]
Check if this image handle points to actual data.
Definition at line 172 of file Image.h.
References Halide::Buffer::defined().
Referenced by Halide::Image< T >::data(), Halide::Image< T >::extent(), Halide::Image< T >::min(), Halide::Image< T >::set_min(), and Halide::Image< T >::stride().
template<typename T> int Halide::Image< T >::dimensions () const [inline]
Get the dimensionality of the data.
Typically two for grayscale images, and three for color images.
Definition at line 177 of file Image.h.
Referenced by Halide::Image< T >::bottom(), Halide::Image< T >::channels(), Halide::Image< T >::height(), Halide::Image< T >::left(), Halide::Image< T >::right(), Halide::Image< T >::top(), and Halide::Image< T >::width().
template<typename T> int Halide::Image< T >::extent (int dim) const [inline]
Get the size of a dimension.
Definition at line 182 of file Image.h.
References Halide::Image< T >::defined(), and Halide::Buffer::extent().
Referenced by Halide::Image< T >::bottom(), Halide::Image< T >::channels(), Halide::Image< T >::height(), Halide::Image< T >::right(), and Halide::Image< T >::width().
template<typename T> int Halide::Image< T >::min (int dim) const [inline]
Get the min coordinate of a dimension.
The top left of the image represents this point in a function that was realized into this image.
Definition at line 191 of file Image.h.
References Halide::Image< T >::defined(), and Halide::Buffer::min().
Referenced by Halide::Image< T >::bottom(), Halide::Image< T >::data(), Halide::Image< T >::left(), Halide::Image< T >::right(), and Halide::Image< T >::top().
template<typename T> void Halide::Image< T >::set_min (int m0, int m1 = 0, int m2 = 0, int m3 = 0) [inline]
Set the min coordinates of a dimension.
Definition at line 198 of file Image.h.
References Halide::Image< T >::defined(), and Halide::Buffer::set_min().
template<typename T> int Halide::Image< T >::stride (int dim) const [inline]
Get the number of elements in the buffer between two adjacent elements in the given dimension.
For example, the stride in dimension 0 is usually 1, and the stride in dimension 1 is usually the extent of dimension 0. This is not necessarily true though.
Definition at line 210 of file Image.h.
References Halide::Image< T >::defined(), and Halide::Buffer::stride().
Referenced by Halide::Image< T >::data().
template<typename T> int Halide::Image< T >::width () const [inline]
Get the extent of dimension 0, which by convention we use as the width of the image.
Unlike extent(0), returns one if the buffer is zero-dimensional.
Definition at line 219 of file Image.h.
References Halide::Image< T >::dimensions(), and Halide::Image< T >::extent().
template<typename T> int Halide::Image< T >::height () const [inline]
Get the extent of dimension 1, which by convention we use as the height of the image.
Unlike extent(1), returns one if the buffer has fewer than two dimensions.
Definition at line 227 of file Image.h.
References Halide::Image< T >::dimensions(), and Halide::Image< T >::extent().
template<typename T> int Halide::Image< T >::channels () const [inline]
Get the extent of dimension 2, which by convention we use as the number of color channels (often 3).
Unlike extent(2), returns one if the buffer has fewer than three dimensions.
Definition at line 235 of file Image.h.
References Halide::Image< T >::dimensions(), and Halide::Image< T >::extent().
template<typename T> int Halide::Image< T >::left () const [inline]
Get the minimum coordinate in dimension 0, which by convention is the coordinate of the left edge of the image.
Returns zero for zero-dimensional images.
Definition at line 243 of file Image.h.
References Halide::Image< T >::dimensions(), and Halide::Image< T >::min().
template<typename T> int Halide::Image< T >::right () const [inline]
Get the maximum coordinate in dimension 0, which by convention is the coordinate of the right edge of the image.
Returns zero for zero-dimensional images.
Definition at line 251 of file Image.h.
References Halide::Image< T >::dimensions(), Halide::Image< T >::extent(), and Halide::Image< T >::min().
template<typename T> int Halide::Image< T >::top () const [inline]
Get the minimum coordinate in dimension 1, which by convention is the top of the image.
Returns zero for zero- or one-dimensional images.
Definition at line 259 of file Image.h.
References Halide::Image< T >::dimensions(), and Halide::Image< T >::min().
template<typename T> int Halide::Image< T >::bottom () const [inline]
Get the maximum coordinate in dimension 1, which by convention is the bottom of the image.
Returns zero for zero- or one-dimensional images.
Definition at line 267 of file Image.h.
References Halide::Image< T >::dimensions(), Halide::Image< T >::extent(), and Halide::Image< T >::min().
template<typename T> T* Halide::Image< T >::data () const [inline]
Get a pointer to the element at the min location.
Definition at line 273 of file Image.h.
References Halide::Image< T >::defined(), Halide::Image< T >::min(), and Halide::Image< T >::stride().
template<typename T> T Halide::Image< T >::operator() (int x) const [inline]
Assuming this image is one-dimensional, get the value of the element at position x.
Definition at line 284 of file Image.h.
template<typename T> T Halide::Image< T >::operator() (int x, int y) const [inline]
Assuming this image is two-dimensional, get the value of the element at position (x, y)
Definition at line 290 of file Image.h.
template<typename T> T Halide::Image< T >::operator() (int x, int y, int z) const [inline]
Assuming this image is three-dimensional, get the value of the element at position (x, y, z)
Definition at line 296 of file Image.h.
template<typename T> T Halide::Image< T >::operator() (int x, int y, int z, int w) const [inline]
Assuming this image is four-dimensional, get the value of the element at position (x, y, z, w)
Definition at line 302 of file Image.h.
template<typename T> T& Halide::Image< T >::operator() (int x) [inline]
Assuming this image is one-dimensional, get a reference to the element at position x.
Definition at line 308 of file Image.h.
template<typename T> T& Halide::Image< T >::operator() (int x, int y) [inline]
Assuming this image is two-dimensional, get a reference to the element at position (x, y)
Definition at line 314 of file Image.h.
template<typename T> T& Halide::Image< T >::operator() (int x, int y, int z) [inline]
Assuming this image is three-dimensional, get a reference to the element at position (x, y, z)
Definition at line 320 of file Image.h.
template<typename T> T& Halide::Image< T >::operator() (int x, int y, int z, int w) [inline]
Assuming this image is four-dimensional, get a reference to the element at position (x, y, z, w)
Definition at line 326 of file Image.h.
template<typename T> Expr Halide::Image< T >::operator() () const [inline]
Construct an expression which loads from this image.
The location is composed of enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 333 of file Image.h.
References Halide::Internal::Call::make().
template<typename T> Expr Halide::Image< T >::operator() (Expr x) const [inline]
Construct an expression which loads from this image.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 343 of file Image.h.
References Halide::ImageParam::check_arg_types(), Halide::Internal::Call::make(), and Halide::Buffer::name().
template<typename T> Expr Halide::Image< T >::operator() (Expr x, Expr y) const [inline]
Construct an expression which loads from this image.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 355 of file Image.h.
References Halide::ImageParam::check_arg_types(), Halide::Internal::Call::make(), and Halide::Buffer::name().
template<typename T> Expr Halide::Image< T >::operator() (Expr x, Expr y, Expr z) const [inline]
Construct an expression which loads from this image.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 368 of file Image.h.
References Halide::ImageParam::check_arg_types(), Halide::Internal::Call::make(), and Halide::Buffer::name().
template<typename T> Expr Halide::Image< T >::operator() (Expr x, Expr y, Expr z, Expr w) const [inline]
Construct an expression which loads from this image.
The location is extended with enough implicit variables to match the dimensionality of the image (see Var::implicit)
Definition at line 382 of file Image.h.
References Halide::ImageParam::check_arg_types(), Halide::Internal::Call::make(), and Halide::Buffer::name().
template<typename T> buffer_t* Halide::Image< T >::raw_buffer () const [inline]
Get a pointer to the raw buffer_t that this image holds.
Definition at line 399 of file Image.h.
References Halide::Buffer::raw_buffer().
template<typename T> Halide::Image< T >::operator Buffer () const [inline]
Get a handle on the Buffer that this image holds.
Definition at line 402 of file Image.h.
template<typename T> Halide::Image< T >::operator Argument () const [inline]
Convert this image to an argument to a halide pipeline.
Definition at line 405 of file Image.h.
template<typename T> Halide::Image< T >::operator ExternFuncArgument () const [inline]
Convert this image to an argument to an extern stage.
Definition at line 410 of file Image.h.
template<typename T> Halide::Image< T >::operator Expr () const [inline]
Treating the image as an Expr is equivalent to call it with no arguments.
For example, you can say:
     Image im(10, 10);
     Func f;
     f = im*2;
This will define f as a two-dimensional function with value at position (x, y) equal to twice the value of the image at the same location.
Definition at line 427 of file Image.h.
References Halide::_.
The documentation for this class was generated from the following file:
Image.h