Halide: Halide::Runtime::Internal::MemoryArena Class Reference
Halide::Runtime::Internal::MemoryArena Class Reference
#include <memory_arena.h>
Classes
struct Config
Public Member Functions
MemoryArena (const MemoryArena &)=delete
MemoryArena & operator= (const MemoryArena &)=delete
MemoryArena (void *user_context, const Config &config=default_config(), const SystemMemoryAllocatorFns &allocator=default_allocator())
~MemoryArena ()
void initialize (void *user_context, const Config &config, const SystemMemoryAllocatorFns &allocator=default_allocator())
void * reserve (void *user_context, bool initialize=false)
void reclaim (void *user_context, void *ptr)
bool collect (void *user_context)
void destroy (void *user_context)
const Config & current_config () const
const SystemMemoryAllocatorFns & current_allocator () const
Static Public Member Functions
static MemoryArena * create (void *user_context, const Config &config, const SystemMemoryAllocatorFns &allocator=default_allocator())
static void destroy (void *user_context, MemoryArena *arena)
static const Config & default_config ()
static const SystemMemoryAllocatorFns & default_allocator ()
Static Public Attributes
static constexpr uint32_t default_capacity = uint32_t(32)
Detailed Description
Definition at line 16 of file memory_arena.h.
Constructor & Destructor Documentation
MemoryArena() [1/2]
Halide::Runtime::Internal::MemoryArena::MemoryArena (const MemoryArena &) delete
MemoryArena() [2/2]
Halide::Runtime::Internal::MemoryArena::MemoryArena (void * user_context, const Config & config = default_config(), const SystemMemoryAllocatorFns & allocator = default_allocator())
Definition at line 88 of file memory_arena.h.
~MemoryArena()
Halide::Runtime::Internal::MemoryArena::~MemoryArena ()
Definition at line 96 of file memory_arena.h.
References destroy().
Member Function Documentation
operator=()
MemoryArena & Halide::Runtime::Internal::MemoryArena::operator= (const MemoryArena &) delete
create()
MemoryArena * Halide::Runtime::Internal::MemoryArena::create (void * user_context, const Config & config, const SystemMemoryAllocatorFns & allocator = default_allocator()) static
Definition at line 100 of file memory_arena.h.
References Halide::Runtime::Internal::SystemMemoryAllocatorFns::allocate, halide_abort_if_false, halide_error(), and initialize().
Referenced by Halide::Runtime::Internal::LinkedList::initialize(), and Halide::Runtime::Internal::LinkedList::LinkedList().
destroy() [1/2]
void Halide::Runtime::Internal::MemoryArena::destroy (void * user_context, MemoryArena * arena) static
Definition at line 114 of file memory_arena.h.
References Halide::Runtime::Internal::BlockStorage::current_allocator(), Halide::Runtime::Internal::SystemMemoryAllocatorFns::deallocate, destroy(), and halide_abort_if_false.
Referenced by Halide::Runtime::Internal::LinkedList::destroy(), Halide::Runtime::Internal::RegionAllocator::destroy(), destroy(), and ~MemoryArena().
initialize()
void Halide::Runtime::Internal::MemoryArena::initialize (void * user_context, const Config & config, const SystemMemoryAllocatorFns & allocator = default_allocator())
Definition at line 122 of file memory_arena.h.
References halide_debug_assert, Halide::Runtime::Internal::BlockStorage::initialize(), and Halide::Runtime::Internal::MemoryArena::Config::minimum_block_capacity.
Referenced by create(), and reserve().
reserve()
void * Halide::Runtime::Internal::MemoryArena::reserve (void * user_context, bool initialize = false)
Definition at line 154 of file memory_arena.h.
References Halide::Runtime::Internal::MemoryArena::Config::entry_size, halide_abort_if_false, halide_error(), initialize(), Halide::Runtime::Internal::MemoryArena::Config::maximum_block_count, memset(), and Halide::Runtime::Internal::BlockStorage::size().
reclaim()
void Halide::Runtime::Internal::MemoryArena::reclaim (void * user_context, void * ptr)
Definition at line 181 of file memory_arena.h.
References Halide::Runtime::Internal::MemoryArena::Config::entry_size, halide_abort_if_false, halide_error(), Halide::Runtime::Internal::offset_address(), and Halide::Runtime::Internal::BlockStorage::size().
collect()
bool Halide::Runtime::Internal::MemoryArena::collect (void * user_context)
Definition at line 141 of file memory_arena.h.
References halide_abort_if_false, Halide::Runtime::Internal::BlockStorage::remove(), and Halide::Runtime::Internal::BlockStorage::size().
destroy() [2/2]
void Halide::Runtime::Internal::MemoryArena::destroy (void * user_context)
Definition at line 130 of file memory_arena.h.
References Halide::Runtime::Internal::BlockStorage::destroy(), Halide::Runtime::Internal::BlockStorage::empty(), halide_abort_if_false, and Halide::Runtime::Internal::BlockStorage::size().
current_config()
const MemoryArena::Config & Halide::Runtime::Internal::MemoryArena::current_config () const
Definition at line 286 of file memory_arena.h.
Referenced by Halide::Runtime::Internal::LinkedList::append(), Halide::Runtime::Internal::LinkedList::insert_after(), Halide::Runtime::Internal::LinkedList::insert_before(), and Halide::Runtime::Internal::LinkedList::prepend().
default_config()
const MemoryArena::Config & Halide::Runtime::Internal::MemoryArena::default_config () static
Definition at line 291 of file memory_arena.h.
current_allocator()
const SystemMemoryAllocatorFns & Halide::Runtime::Internal::MemoryArena::current_allocator () const
Definition at line 297 of file memory_arena.h.
References Halide::Runtime::Internal::BlockStorage::current_allocator().
Referenced by Halide::Runtime::Internal::LinkedList::current_allocator().
default_allocator()
const SystemMemoryAllocatorFns & Halide::Runtime::Internal::MemoryArena::default_allocator () static
Definition at line 302 of file memory_arena.h.
References Halide::Runtime::Internal::BlockStorage::default_allocator().
Referenced by Halide::Runtime::Internal::LinkedList::default_allocator().
Member Data Documentation
default_capacity
constexpr uint32_t Halide::Runtime::Internal::MemoryArena::default_capacity = uint32_t(32) static constexpr
Definition at line 23 of file memory_arena.h.
Referenced by Halide::Runtime::Internal::LinkedList::initialize(), and Halide::Runtime::Internal::LinkedList::LinkedList().
The documentation for this class was generated from the following file:
src/runtime/internal/memory_arena.h