Halide: Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension Class Reference
Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension Class Reference
Read-only access to the shape.
#include <HalideBuffer.h>
Classes
struct iterator
An iterator class, so that you can iterate over coordinates in a dimensions using a range-based for loop.
Public Member Functions
HALIDE_ALWAYS_INLINE int min () const
The lowest coordinate in this dimension.
HALIDE_ALWAYS_INLINE int stride () const
The number of elements in memory you have to step over to increment this coordinate by one.
HALIDE_ALWAYS_INLINE int extent () const
The extent of the image along this dimension.
HALIDE_ALWAYS_INLINE int max () const
The highest coordinate in this dimension.
HALIDE_ALWAYS_INLINE iterator begin () const
An iterator that points to the min coordinate.
HALIDE_ALWAYS_INLINE iterator end () const
An iterator that points to one past the max coordinate.
Dimension (const halide_dimension_t &dim)
Detailed Description
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))>
class Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension
Read-only access to the shape.
Definition at line 574 of file HalideBuffer.h.
Constructor & Destructor Documentation
Dimension()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::Dimension (const halide_dimension_t & dim) inline explicit
Definition at line 625 of file HalideBuffer.h.
Member Function Documentation
min()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::min () const inline
The lowest coordinate in this dimension.
Definition at line 579 of file HalideBuffer.h.
References halide_dimension_t::min.
Referenced by Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::begin(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::copy_from(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::end(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::left(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::max(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::min(), and Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::top().
stride()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::stride () const inline
The number of elements in memory you have to step over to increment this coordinate by one.
Definition at line 585 of file HalideBuffer.h.
References halide_dimension_t::stride.
Referenced by Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::stride().
extent()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::extent () const inline
The extent of the image along this dimension.
Definition at line 590 of file HalideBuffer.h.
References halide_dimension_t::extent.
Referenced by Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::channels(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::check_overflow(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::end(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::extent(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::height(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::max(), and Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::width().
max()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE int Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::max () const inline
The highest coordinate in this dimension.
Definition at line 595 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::extent(), and Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::min().
Referenced by Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::bottom(), Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::copy_from(), and Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::right().
begin()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE iterator Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::begin () const inline
An iterator that points to the min coordinate.
Definition at line 616 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::min().
end()
template<typename T = void, int Dims = AnyDims, int InClassDimStorage = (Dims == AnyDims ? 4 : std::max(Dims, 1))> HALIDE_ALWAYS_INLINE iterator Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::end () const inline
An iterator that points to one past the max coordinate.
Definition at line 621 of file HalideBuffer.h.
References Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::extent(), and Halide::Runtime::Buffer< T, Dims, InClassDimStorage >::Dimension::min().
The documentation for this class was generated from the following file:
src/runtime/HalideBuffer.h