Halide: d3d12_abi_patch_64.h File Reference
d3d12_abi_patch_64.h File Reference
Functions
void Call_ID3D12DescriptorHeap_GetDesc (ID3D12DescriptorHeap *descriptorheap, D3D12_DESCRIPTOR_HEAP_DESC *desc)
void Call_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart (ID3D12DescriptorHeap *descriptorheap, D3D12_CPU_DESCRIPTOR_HANDLE *cpuHandle)
void Call_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart (ID3D12DescriptorHeap *descriptorheap, D3D12_GPU_DESCRIPTOR_HANDLE *gpuHandle)
void Call_ID3D12GraphicsCommandList_SetComputeRootDescriptorTable (ID3D12GraphicsCommandList *commandList, UINT RootParameterIndex, D3D12_GPU_DESCRIPTOR_HANDLE *pBaseDescriptor)
void Call_ID3D12Device_CreateConstantBufferView (ID3D12Device *device, D3D12_CONSTANT_BUFFER_VIEW_DESC *pDesc, D3D12_CPU_DESCRIPTOR_HANDLE *pDestDescriptor)
void Call_ID3D12Device_CreateShaderResourceView (ID3D12Device *device, ID3D12Resource *pResource, const D3D12_SHADER_RESOURCE_VIEW_DESC *pDesc, D3D12_CPU_DESCRIPTOR_HANDLE *pDestDescriptor)
__attribute__ ((optnone)) __attribute__((noinline)) D3D12_DESCRIPTOR_HEAP_DESC Call_ID3D12DescriptorHeap_GetDesc(ID3D12DescriptorHeap *descriptorheap)
Variables
UINT RootParameterIndex
UINT D3D12_GPU_DESCRIPTOR_HANDLE BaseDescriptor
D3D12_CONSTANT_BUFFER_VIEW_DESC * pDesc
D3D12_CONSTANT_BUFFER_VIEW_DESC D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor
ID3D12Resource * pResource
Function Documentation
Call_ID3D12DescriptorHeap_GetDesc()
void Call_ID3D12DescriptorHeap_GetDesc (ID3D12DescriptorHeap * descriptorheap, D3D12_DESCRIPTOR_HEAP_DESC * desc)
Referenced by __attribute__().
Call_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart()
void Call_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart (ID3D12DescriptorHeap * descriptorheap, D3D12_CPU_DESCRIPTOR_HANDLE * cpuHandle)
Referenced by __attribute__().
Call_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart()
void Call_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart (ID3D12DescriptorHeap * descriptorheap, D3D12_GPU_DESCRIPTOR_HANDLE * gpuHandle)
Referenced by __attribute__().
Call_ID3D12GraphicsCommandList_SetComputeRootDescriptorTable()
void Call_ID3D12GraphicsCommandList_SetComputeRootDescriptorTable (ID3D12GraphicsCommandList * commandList, UINT RootParameterIndex, D3D12_GPU_DESCRIPTOR_HANDLE * pBaseDescriptor)
Call_ID3D12Device_CreateConstantBufferView()
void Call_ID3D12Device_CreateConstantBufferView (ID3D12Device * device, D3D12_CONSTANT_BUFFER_VIEW_DESC * pDesc, D3D12_CPU_DESCRIPTOR_HANDLE * pDestDescriptor)
Call_ID3D12Device_CreateShaderResourceView()
void Call_ID3D12Device_CreateShaderResourceView (ID3D12Device * device, ID3D12Resource * pResource, const D3D12_SHADER_RESOURCE_VIEW_DESC * pDesc, D3D12_CPU_DESCRIPTOR_HANDLE * pDestDescriptor)
__attribute__()
__attribute__ ((optnone))
Definition at line 39 of file d3d12_abi_patch_64.h.
References Call_ID3D12DescriptorHeap_GetCPUDescriptorHandleForHeapStart(), Call_ID3D12DescriptorHeap_GetDesc(), and Call_ID3D12DescriptorHeap_GetGPUDescriptorHandleForHeapStart().
Referenced by Halide::Runtime::Internal::__attribute__().
Variable Documentation
RootParameterIndex
UINT RootParameterIndex
Definition at line 80 of file d3d12_abi_patch_64.h.
BaseDescriptor
UINT D3D12_GPU_DESCRIPTOR_HANDLE BaseDescriptor
Initial value:
{
    commandList->SetComputeRootDescriptorTable(RootParameterIndex, BaseDescriptor)
Definition at line 81 of file d3d12_abi_patch_64.h.
pDesc
ID3D12Resource D3D12_SHADER_RESOURCE_VIEW_DESC * pDesc
Definition at line 91 of file d3d12_abi_patch_64.h.
DestDescriptor
ID3D12Resource D3D12_SHADER_RESOURCE_VIEW_DESC D3D12_CPU_DESCRIPTOR_HANDLE DestDescriptor
Initial value:
{
    device->CreateConstantBufferView(pDesc, DestDescriptor)
Definition at line 92 of file d3d12_abi_patch_64.h.
pResource
ID3D12Resource* pResource
Definition at line 102 of file d3d12_abi_patch_64.h.