Halide: mini_qurt.h File Reference
mini_qurt.h File Reference
#include "runtime_internal.h"
#include "HalideRuntime.h"
#include "printer.h"
Classes
struct _qurt_thread_attr
Thread attributes.
union qurt_mutex_aligned8
QuRT mutex type.
union qurt_cond_t
QuRT condition variable type.
Namespaces
Halide
Defines methods for manipulating and analyzing boolean expressions.
Halide::Runtime
Halide::Runtime::Internal
Halide::Runtime::Internal::Qurt
Macros
#define QURT_HTHREAD_L1I_PREFETCH 0x1
Enables hardware L1 instruction cache prefetching.
#define QURT_HTHREAD_L1D_PREFETCH 0x2
Enables hardware L1 data cache prefetching.
#define QURT_HTHREAD_L2I_PREFETCH 0x4
Enables hardware L2 instruction cache prefetching.
#define QURT_HTHREAD_L2D_PREFETCH 0x8
Enables hardware L2 data cache prefetching.
#define QURT_HTHREAD_DCFETCH 0x10
Enables DC fetch to the provided virtual address.
#define QURT_THREAD_ATTR_NAME_MAXLEN 16
#define QURT_THREAD_ATTR_TCB_PARTITION_RAM 0
Creates threads in RAM/DDR.
#define QURT_THREAD_ATTR_TCB_PARTITION_TCM 1
Creates threads in TCM.
#define QURT_THREAD_ATTR_TCB_PARTITION_DEFAULT QURT_THREAD_ATTR_TCB_PARTITION_RAM
Backward compatibility.
#define QURT_THREAD_ATTR_PRIORITY_DEFAULT 255
#define QURT_THREAD_ATTR_ASID_DEFAULT 0
#define QURT_THREAD_ATTR_AFFINITY_DEFAULT (-1)
#define QURT_THREAD_ATTR_BUS_PRIO_DEFAULT 255
#define QURT_THREAD_ATTR_TIMETEST_ID_DEFAULT (-2)
Typedefs
typedef unsigned int qurt_thread_t
typedef struct _qurt_thread_attr qurt_thread_attr_t
Thread attributes.
typedef union qurt_mutex_aligned8 qurt_mutex_t
QuRT mutex type.
typedef unsigned int qurt_size_t
typedef unsigned int qurt_mem_pool_t
Enumerations
enum { Halide::Runtime::Internal::Qurt::QURT_EOK = 0 }
enum qurt_hvx_mode_t { QURT_HVX_MODE_64B = 0, QURT_HVX_MODE_128B = 1 }
Functions
int qurt_thread_set_priority (qurt_thread_t threadid, unsigned short newprio)
int qurt_thread_create (qurt_thread_t *thread_id, qurt_thread_attr_t *attr, void(*entrypoint)(void *), void *arg)
int qurt_thread_join (unsigned int tid, int *status)
Waits for a specified thread to finish.
void qurt_mutex_init (qurt_mutex_t *lock)
void qurt_mutex_destroy (qurt_mutex_t *lock)
void qurt_mutex_lock (qurt_mutex_t *lock)
void qurt_mutex_unlock (qurt_mutex_t *lock)
void qurt_cond_init (qurt_cond_t *cond)
void qurt_cond_destroy (qurt_cond_t *cond)
void qurt_cond_signal (qurt_cond_t *cond)
void qurt_cond_wait (qurt_cond_t *cond, qurt_mutex_t *mutex)
int qurt_hvx_lock (qurt_hvx_mode_t lock_mode)
int qurt_hvx_unlock (void)
int qurt_hvx_get_mode (void)
Macro Definition Documentation
QURT_HTHREAD_L1I_PREFETCH
#define QURT_HTHREAD_L1I_PREFETCH 0x1
Enables hardware L1 instruction cache prefetching.
Definition at line 18 of file mini_qurt.h.
QURT_HTHREAD_L1D_PREFETCH
#define QURT_HTHREAD_L1D_PREFETCH 0x2
Enables hardware L1 data cache prefetching.
Definition at line 19 of file mini_qurt.h.
QURT_HTHREAD_L2I_PREFETCH
#define QURT_HTHREAD_L2I_PREFETCH 0x4
Enables hardware L2 instruction cache prefetching.
Definition at line 20 of file mini_qurt.h.
QURT_HTHREAD_L2D_PREFETCH
#define QURT_HTHREAD_L2D_PREFETCH 0x8
Enables hardware L2 data cache prefetching.
Definition at line 21 of file mini_qurt.h.
QURT_HTHREAD_DCFETCH
#define QURT_HTHREAD_DCFETCH 0x10
Enables DC fetch to the provided virtual address.
DC fetch instructs the hardware that a data memory access is likely. Instructions are dropped in the case of high bus utilization.
Definition at line 22 of file mini_qurt.h.
QURT_THREAD_ATTR_NAME_MAXLEN
#define QURT_THREAD_ATTR_NAME_MAXLEN 16
Definition at line 30 of file mini_qurt.h.
QURT_THREAD_ATTR_TCB_PARTITION_RAM
#define QURT_THREAD_ATTR_TCB_PARTITION_RAM 0
Creates threads in RAM/DDR.
Definition at line 31 of file mini_qurt.h.
QURT_THREAD_ATTR_TCB_PARTITION_TCM
#define QURT_THREAD_ATTR_TCB_PARTITION_TCM 1
Creates threads in TCM.
Definition at line 32 of file mini_qurt.h.
QURT_THREAD_ATTR_TCB_PARTITION_DEFAULT
#define QURT_THREAD_ATTR_TCB_PARTITION_DEFAULT QURT_THREAD_ATTR_TCB_PARTITION_RAM
Backward compatibility.
Definition at line 33 of file mini_qurt.h.
QURT_THREAD_ATTR_PRIORITY_DEFAULT
#define QURT_THREAD_ATTR_PRIORITY_DEFAULT 255
Definition at line 34 of file mini_qurt.h.
QURT_THREAD_ATTR_ASID_DEFAULT
#define QURT_THREAD_ATTR_ASID_DEFAULT 0
Definition at line 35 of file mini_qurt.h.
QURT_THREAD_ATTR_AFFINITY_DEFAULT
#define QURT_THREAD_ATTR_AFFINITY_DEFAULT (-1)
Definition at line 36 of file mini_qurt.h.
QURT_THREAD_ATTR_BUS_PRIO_DEFAULT
#define QURT_THREAD_ATTR_BUS_PRIO_DEFAULT 255
Definition at line 37 of file mini_qurt.h.
QURT_THREAD_ATTR_TIMETEST_ID_DEFAULT
#define QURT_THREAD_ATTR_TIMETEST_ID_DEFAULT (-2)
Definition at line 38 of file mini_qurt.h.
Typedef Documentation
qurt_thread_t
typedef unsigned int qurt_thread_t
Definition at line 12 of file mini_qurt.h.
qurt_thread_attr_t
typedef struct _qurt_thread_attr qurt_thread_attr_t
Thread attributes.
qurt_mutex_t
typedef union qurt_mutex_aligned8 qurt_mutex_t
QuRT mutex type.
Both non-recursive mutex lock/unlock and recursive mutex lock/unlock can be applied to this type.
qurt_size_t
typedef unsigned int qurt_size_t
Definition at line 240 of file mini_qurt.h.
qurt_mem_pool_t
typedef unsigned int qurt_mem_pool_t
Definition at line 241 of file mini_qurt.h.
Enumeration Type Documentation
qurt_hvx_mode_t
enum qurt_hvx_mode_t
Enumerator
QURT_HVX_MODE_64B
HVX mode of 64 bytes.
QURT_HVX_MODE_128B
HVX mode of 128 bytes.
Definition at line 231 of file mini_qurt.h.
Function Documentation
qurt_thread_set_priority()
int qurt_thread_set_priority (qurt_thread_t threadid, unsigned short newprio)
Referenced by PipelineContext::set_priority().
qurt_thread_create()
int qurt_thread_create (qurt_thread_t * thread_id, qurt_thread_attr_t * attr, void(*)(void *) entrypoint, void * arg)
qurt_thread_join()
int qurt_thread_join (unsigned int tid, int * status)
Waits for a specified thread to finish.
The specified thread should be another thread within the same process. The caller thread is suspended until the specified thread exits. When this happens the caller thread is awakened.
Note
If the specified thread has already exited, this function returns immediately with the result value QURT_ENOTHREAD.
Note
Two threads cannot call qurt_thread_join to wait for the same thread to finish. If this happens QuRT generates an exception.
Parameters
[in] tid Thread identifier.
[out] status Destination variable for thread exit status. Returns an application-defined value indicating the termination status of the specified thread.
Returns
QURT_ENOTHREAD – Thread has already exited.
QURT_EOK – Thread successfully joined with valid status value.
Referenced by PipelineContext::~PipelineContext().
qurt_mutex_init()
void qurt_mutex_init (qurt_mutex_t * lock)
Referenced by PipelineContext::PipelineContext().
qurt_mutex_destroy()
void qurt_mutex_destroy (qurt_mutex_t * lock)
Referenced by PipelineContext::~PipelineContext().
qurt_mutex_lock()
void qurt_mutex_lock (qurt_mutex_t * lock)
Referenced by PipelineContext::run(), and PipelineContext::~PipelineContext().
qurt_mutex_unlock()
void qurt_mutex_unlock (qurt_mutex_t * lock)
Referenced by PipelineContext::run(), and PipelineContext::~PipelineContext().
qurt_cond_init()
void qurt_cond_init (qurt_cond_t * cond)
Referenced by PipelineContext::PipelineContext().
qurt_cond_destroy()
void qurt_cond_destroy (qurt_cond_t * cond)
Referenced by PipelineContext::~PipelineContext().
qurt_cond_signal()
void qurt_cond_signal (qurt_cond_t * cond)
Referenced by PipelineContext::run(), and PipelineContext::~PipelineContext().
qurt_cond_wait()
void qurt_cond_wait (qurt_cond_t * cond, qurt_mutex_t * mutex)
Referenced by PipelineContext::run().
qurt_hvx_lock()
int qurt_hvx_lock (qurt_hvx_mode_t lock_mode)
qurt_hvx_unlock()
int qurt_hvx_unlock (void)
qurt_hvx_get_mode()
int qurt_hvx_get_mode (void)