Halide: Halide::BoundaryConditions Namespace Reference
Halide::BoundaryConditions Namespace Reference
namespace to hold functions for imposing boundary conditions on Halide Funcs.
Namespaces
namespace Internal
Functions
EXPORT Func constant_exterior (const Func &source, Expr value, const std::vector< std::pair< Expr, Expr > > &bounds)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
template<typename T >
NO_INLINE Func constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
EXPORT Func repeat_edge (const Func &source, const std::vector< std::pair< Expr, Expr > > &bounds)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
template<typename T >
NO_INLINE Func repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
EXPORT Func repeat_image (const Func &source, const std::vector< std::pair< Expr, Expr > > &bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
EXPORT Func mirror_image (const Func &source, const std::vector< std::pair< Expr, Expr > > &bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same.
template<typename T >
NO_INLINE Func mirror_image (T func_like)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
template<typename T >
NO_INLINE Func mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
EXPORT Func mirror_interior (const Func &source, const std::vector< std::pair< Expr, Expr > > &bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
template<typename T >
NO_INLINE Func mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
Detailed Description
namespace to hold functions for imposing boundary conditions on Halide Funcs.
All functions in this namespace transform a source Func to a result Func where the result produces the values of the source within a given region and a different set of values outside the given region. A region is an N dimensional box specified by mins and extents.
Three areas are defined: The image is the entire set of values in the region. The edge is the set of pixels in the image but adjacent to coordinates that are not The interior is the image minus the edge (and is undefined if the extent of any region is 1 or less).
If the source Func has more dimensions than are specified, the extra ones are unmodified.
Numerous options for specifing the outside area are provided, including replacement with an expression, repeating the edge samples, mirroring over the edge, and repeating or mirroring the entire image.
TODO: Add support for passing Image<T> and ImageParam, and possibly other types directly to this functions.
Function Documentation
EXPORT Func Halide::BoundaryConditions::constant_exterior (const Func & source, Expr value, const std::vector< std::pair< Expr, Expr > > & bounds)
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Referenced by constant_exterior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 98 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 117 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 125 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 135 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 147 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 161 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::constant_exterior (T func_like, Expr value, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5) [inline]
Impose a boundary condition such that a given expression is returned everywhere outside the boundary.
Generally the expression will be a constant, though the code currently allows accessing the arguments of source.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_BORDER and putting value in the border of the texture.)
Definition at line 177 of file BoundaryConditions.h.
References constant_exterior(), and Halide::BoundaryConditions::Internal::func_like_to_func().
EXPORT Func Halide::BoundaryConditions::repeat_edge (const Func & source, const std::vector< std::pair< Expr, Expr > > & bounds)
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Referenced by repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 210 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 229 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 237 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 247 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 259 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 273 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_edge (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5) [inline]
Impose a boundary condition such that the nearest edge sample is returned everywhere outside the given region.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_CLAMP_TO_EDGE.)
Definition at line 289 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_edge().
EXPORT Func Halide::BoundaryConditions::repeat_image (const Func & source, const std::vector< std::pair< Expr, Expr > > & bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Referenced by repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 322 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 340 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 348 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 358 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 370 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 384 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::repeat_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 400 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and repeat_image().
EXPORT Func Halide::BoundaryConditions::mirror_image (const Func & source, const std::vector< std::pair< Expr, Expr > > & bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_MIRRORED_REPEAT.)
Referenced by mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 433 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 451 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 459 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 469 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 481 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 495 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_image (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other.
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(This is similar to setting GL_TEXTURE_WRAP_* to GL_REPEAT.)
Definition at line 511 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_image().
EXPORT Func Halide::BoundaryConditions::mirror_interior (const Func & source, const std::vector< std::pair< Expr, Expr > > & bounds)
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Referenced by mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 547 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 565 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 573 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 583 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 595 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 609 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().
template<typename T > NO_INLINE Func Halide::BoundaryConditions::mirror_interior (T func_like, Expr min0, Expr extent0, Expr min1, Expr extent1, Expr min2, Expr extent2, Expr min3, Expr extent3, Expr min4, Expr extent4, Expr min5, Expr extent5) [inline]
Impose a boundary condition such that the entire coordinate space is tiled with copies of the image abutted against each other, but mirror them such that adjacent edges are the same and then overlap the edges.
This produces an error if any extent is 1 or less. (TODO: check this.)
An ImageParam, Image<T>, or similar can be passed instead of a Func. If this is done and no bounds are given, the boundaries will be taken from the min and extent methods of the passed object.
(I do not believe there is a direct GL_TEXTURE_WRAP_* equivalent for this.)
Definition at line 625 of file BoundaryConditions.h.
References Halide::BoundaryConditions::Internal::func_like_to_func(), and mirror_interior().