Halide: Testing Namespace Reference
Testing Namespace Reference
Functions
template<typename T >
bool neq (T a, T b, T tol)
template<typename T , typename F >
auto check_result (const Halide::Buffer< T > &buf, T tol, F f) -> decltype(std::declval< F >()(0, 0, 0), bool())
template<typename T , typename Func >
bool check_result (const Halide::Buffer< T > &buf, Func f)
Function Documentation
neq()
template<typename T > bool Testing::neq (T a, T b, T tol)
Definition at line 13 of file testing.h.
References Halide::abs().
Referenced by check_result().
check_result() [1/2]
template<typename T , typename F > auto Testing::check_result (const Halide::Buffer< T > & buf, T tol, F f) -> decltype(std::declval<F>()(0, 0, 0), bool())
Definition at line 19 of file testing.h.
References buf, and neq().
check_result() [2/2]
template<typename T , typename Func > bool Testing::check_result (const Halide::Buffer< T > & buf, Func f)
Definition at line 81 of file testing.h.
References buf.