Halide: Halide::Internal::Div Struct Reference
Halide::Internal::Div Struct Reference
The ratio of two expressions.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Div >.
Static Public Member Functions
static Expr make (Expr a, Expr b)
Public Attributes
Expr a
Expr b
Detailed Description
The ratio of two expressions.
Definition at line 302 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::Div::make (Expr a, Expr b) [inline, static]
Definition at line 305 of file IR.h.
References a, b, Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::BaseExprNode::type, and Halide::Expr::type().
Referenced by Halide::operator/(), and Halide::operator/=().
Member Data Documentation
Expr Halide::Internal::Div::a
Definition at line 303 of file IR.h.
Referenced by make().
Expr Halide::Internal::Div::b
Definition at line 303 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h