Halide: Halide::Internal::IRMatcher::BinOp< Op, A, B > Struct Template Reference
Halide::Internal::IRMatcher::BinOp< Op, A, B > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename Op2 , typename A2 , typename B2 >
HALIDE_ALWAYS_INLINE bool match (const BinOp< Op2, A2, B2 > &op, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const noexcept
Public Attributes
A a
B b
Static Public Attributes
static constexpr uint32_t binds = bindings<A>::mask | bindings<B>::mask
static constexpr bool foldable = A::foldable && B::foldable
Detailed Description
template<typename Op, typename A, typename B>
struct Halide::Internal::IRMatcher::BinOp< Op, A, B >
Definition at line 594 of file IRMatch.h.
Member Function Documentation
match() [1/2]
template<typename Op, typename A, typename B> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::BinOp< Op, A, B >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 603 of file IRMatch.h.
References HALIDE_ALWAYS_INLINE.
match() [2/2]
template<typename Op, typename A, typename B> template<uint32_t bound, typename Op2 , typename A2 , typename B2 > HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::BinOp< Op, A, B >::match (const BinOp< Op2, A2, B2 > & op, MatcherState & state) const inline noexcept
Definition at line 614 of file IRMatch.h.
References Halide::Internal::IRMatcher::unwrap().
make_folded_const()
template<typename Op, typename A, typename B> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::BinOp< Op, A, B >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline noexcept
Definition at line 623 of file IRMatch.h.
References halide_scalar_value_t::f64, HALIDE_ALWAYS_INLINE, halide_type_bfloat, halide_type_float, halide_type_int, halide_type_uint, halide_scalar_value_t::i64, halide_scalar_value_t::u, and halide_scalar_value_t::u64.
make()
template<typename Op, typename A, typename B> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::BinOp< Op, A, B >::make (MatcherState & state, halide_type_t type_hint) const inline noexcept
Definition at line 666 of file IRMatch.h.
References Halide::Internal::IRMatcher::constant_fold_cmp_op(), Halide::Type::is_vector(), Halide::Type::lanes(), Halide::Internal::Broadcast::make(), and Halide::Expr::type().
Member Data Documentation
a
template<typename Op, typename A, typename B> A Halide::Internal::IRMatcher::BinOp< Op, A, B >::a
Definition at line 596 of file IRMatch.h.
b
template<typename Op, typename A, typename B> B Halide::Internal::IRMatcher::BinOp< Op, A, B >::b
Definition at line 597 of file IRMatch.h.
binds
template<typename Op, typename A, typename B> constexpr uint32_t Halide::Internal::IRMatcher::BinOp< Op, A, B >::binds = bindings<A>::mask | bindings<B>::mask static
Definition at line 599 of file IRMatch.h.
foldable
template<typename Op, typename A, typename B> constexpr bool Halide::Internal::IRMatcher::BinOp< Op, A, B >::foldable = A::foldable && B::foldable static
Definition at line 620 of file IRMatch.h.
The documentation for this struct was generated from the following file:
IRMatch.h