Halide: Halide::Pipeline::RealizationArg Struct Reference
Halide::Pipeline::RealizationArg Struct Reference
#include <Pipeline.h>
Public Member Functions
RealizationArg (Realization &r)
RealizationArg (Realization &&r)
RealizationArg (halide_buffer_t *buf)
template<typename T , int D>
RealizationArg (Runtime::Buffer< T, D > &dst)
template<typename T >
HALIDE_NO_USER_CODE_INLINE RealizationArg (Buffer< T > &dst)
template<typename T , typename... Args, typename = typename std::enable_if<Internal::all_are_convertible<Buffer<>, Args...>::value>::type>
RealizationArg (Buffer< T > &a, Args &&...args)
RealizationArg (RealizationArg &&from)=default
size_t size () const
Public Attributes
Realization * r {nullptr}
halide_buffer_t * buf {nullptr}
std::unique_ptr< std::vector< Buffer<> > > buffer_list
Detailed Description
Definition at line 99 of file Pipeline.h.
Constructor & Destructor Documentation
Halide::Pipeline::RealizationArg::RealizationArg (Realization & r) inline
Definition at line 105 of file Pipeline.h.
Halide::Pipeline::RealizationArg::RealizationArg (Realization && r) inline
Definition at line 108 of file Pipeline.h.
Halide::Pipeline::RealizationArg::RealizationArg (halide_buffer_t * buf) inline
Definition at line 111 of file Pipeline.h.
template<typename T , int D> Halide::Pipeline::RealizationArg::RealizationArg (Runtime::Buffer< T, D > & dst) inline
Definition at line 115 of file Pipeline.h.
template<typename T > HALIDE_NO_USER_CODE_INLINE Halide::Pipeline::RealizationArg::RealizationArg (Buffer< T > & dst) inline
Definition at line 119 of file Pipeline.h.
template<typename T , typename... Args, typename = typename std::enable_if<Internal::all_are_convertible<Buffer<>, Args...>::value>::type> Halide::Pipeline::RealizationArg::RealizationArg (Buffer< T > & a, Args &&... args) inline
Definition at line 124 of file Pipeline.h.
Halide::Pipeline::RealizationArg::RealizationArg (RealizationArg && from) default
Member Function Documentation
size_t Halide::Pipeline::RealizationArg::size () const inline
Definition at line 129 of file Pipeline.h.
References Halide::Runtime::Internal::custom_do_par_for, Halide::Runtime::Internal::custom_do_task, Halide::ExternalPlusMetadata, free(), Halide::MachineParams::generic(), Halide::get_jit_target_from_environment(), Halide::get_target_from_environment(), Halide::Internal::infer_arguments(), malloc(), Halide::Internal::print_loop_nest(), Halide::Text, and user_context.
Member Data Documentation
Realization* Halide::Pipeline::RealizationArg::r {nullptr}
Definition at line 101 of file Pipeline.h.
halide_buffer_t* Halide::Pipeline::RealizationArg::buf {nullptr}
Definition at line 102 of file Pipeline.h.
std::unique_ptr<std::vector<Buffer<> > > Halide::Pipeline::RealizationArg::buffer_list
Definition at line 103 of file Pipeline.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Pipeline.h