Halide: Halide::Derivative Struct Reference
Halide::Derivative Struct Reference
Helper structure storing the adjoints Func.
#include <Derivative.h>
Public Types
using FuncKey = std::pair< std::string, int >
Public Member Functions
Func get (const Func &func, int update_id=-1, bool bounded=true) const
Func operator() (const Func &func, int update_id=-1, bool bounded=true) const
Func get (const Buffer<> &buffer) const
Func operator() (const Buffer<> &buffer) const
Func get (const Param<> &param) const
Func operator() (const Param<> &param) const
std::vector< Func > funcs (const Func &func) const
Get the entire chain of new synthesized Funcs that compute the derivative of a given user-written Func for the purpose of scheduling.
Public Attributes
std::map< FuncKey, Func > adjoints
Detailed Description
Helper structure storing the adjoints Func.
Use d(func) or d(buffer) to obtain the derivative Func.
Definition at line 22 of file Derivative.h.
Member Typedef Documentation
FuncKey
using Halide::Derivative::FuncKey = std::pair<std::string, int>
Definition at line 24 of file Derivative.h.
Member Function Documentation
get() [1/3]
Func Halide::Derivative::get (const Func & func, int update_id = -1, bool bounded = true) const inline
Definition at line 28 of file Derivative.h.
References internal_assert, and Halide::Func::name().
operator()() [1/3]
Func Halide::Derivative::operator() (const Func & func, int update_id = -1, bool bounded = true) const inline
Definition at line 43 of file Derivative.h.
get() [2/3]
Func Halide::Derivative::get (const Buffer<> & buffer) const inline
Definition at line 47 of file Derivative.h.
References internal_assert.
operator()() [2/3]
Func Halide::Derivative::operator() (const Buffer<> & buffer) const inline
Definition at line 53 of file Derivative.h.
get() [3/3]
Func Halide::Derivative::get (const Param<> & param) const inline
Definition at line 57 of file Derivative.h.
References internal_assert.
operator()() [3/3]
Func Halide::Derivative::operator() (const Param<> & param) const inline
Definition at line 63 of file Derivative.h.
funcs()
std::vector<Func> Halide::Derivative::funcs (const Func & func) const inline
Get the entire chain of new synthesized Funcs that compute the derivative of a given user-written Func for the purpose of scheduling.
Definition at line 70 of file Derivative.h.
References internal_assert, Halide::Func::name(), Halide::Func::num_update_definitions(), and Halide::propagate_adjoints().
Member Data Documentation
adjoints
std::map<FuncKey, Func> Halide::Derivative::adjoints
Definition at line 26 of file Derivative.h.
The documentation for this struct was generated from the following file:
Derivative.h