Halide: Halide::Internal::Broadcast Struct Reference
Halide::Internal::Broadcast Struct Reference
A vector with 'width' elements, in which every element is 'value'.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Broadcast >.
Static Public Member Functions
static Expr make (Expr value, int width)
Public Attributes
Expr value
int width
Detailed Description
A vector with 'width' elements, in which every element is 'value'.
This is a special case of the ramp node above, in which the stride is zero.
Definition at line 623 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::Broadcast::make (Expr value, int width) [inline, static]
Definition at line 627 of file IR.h.
References Halide::Internal::IntrusivePtr< T >::defined(), internal_assert, Halide::Type::is_scalar(), Halide::Internal::BaseExprNode::type, Halide::Expr::type(), value, Halide::Type::vector_of(), and width.
Referenced by Halide::cast().
Member Data Documentation
Expr Halide::Internal::Broadcast::value
Definition at line 624 of file IR.h.
Referenced by make().
int Halide::Internal::Broadcast::width
Definition at line 625 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h