Halide: Halide::float16_t Struct Reference
Halide::float16_t Struct Reference
Class that provides a type that implements half precision floating point (IEEE754 2008 binary16) in software.
#include <Float16.h>
Public Member Functions
float16_t ()=default
Construct a float16_t with the bits initialised to 0.
operator float () const
Cast to float.
operator double () const
Cast to double.
operator int () const
Cast to int.
float16_t operator- () const
Return a new float16_t with a negated sign bit.
uint16_t to_bits () const
Returns the bits that represent this float16_t.
Constructors
float16_t (float value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
float16_t (double value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
float16_t (int value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
float16_t operator+ (float16_t rhs) const
Arithmetic operators.
float16_t operator- (float16_t rhs) const
Arithmetic operators.
float16_t operator* (float16_t rhs) const
Arithmetic operators.
float16_t operator/ (float16_t rhs) const
Arithmetic operators.
float16_t operator+= (float16_t rhs)
Arithmetic operators.
float16_t operator-= (float16_t rhs)
Arithmetic operators.
float16_t operator*= (float16_t rhs)
Arithmetic operators.
float16_t operator/= (float16_t rhs)
Arithmetic operators.
bool operator== (float16_t rhs) const
Comparison operators.
bool operator!= (float16_t rhs) const
Comparison operators.
bool operator> (float16_t rhs) const
Comparison operators.
bool operator< (float16_t rhs) const
Comparison operators.
bool operator>= (float16_t rhs) const
Comparison operators.
bool operator<= (float16_t rhs) const
Comparison operators.
bool is_nan () const
Properties.
bool is_infinity () const
Properties.
bool is_negative () const
Properties.
bool is_zero () const
Properties.
Static Public Member Functions
static float16_t make_from_bits (uint16_t bits)
Get a new float16_t with the given raw bits.
static float16_t make_zero ()
Get a new float16_t that represents a special value.
static float16_t make_negative_zero ()
Get a new float16_t that represents a special value.
static float16_t make_infinity ()
Get a new float16_t that represents a special value.
static float16_t make_negative_infinity ()
Get a new float16_t that represents a special value.
static float16_t make_nan ()
Get a new float16_t that represents a special value.
Static Public Attributes
static const int mantissa_bits = 10
static const uint16_t sign_mask = 0x8000
static const uint16_t exponent_mask = 0x7c00
static const uint16_t mantissa_mask = 0x03ff
Detailed Description
Class that provides a type that implements half precision floating point (IEEE754 2008 binary16) in software.
This type is enforced to be 16-bits wide and maintains no state other than the raw IEEE754 binary16 bits so that it can passed to code that checks a type's size and used for halide_buffer_t allocation.
Definition at line 17 of file Float16.h.
Constructor & Destructor Documentation
Halide::float16_t::float16_t (float value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::float16_t::float16_t (double value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::float16_t::float16_t (int value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::float16_t::float16_t () default
Construct a float16_t with the bits initialised to 0.
This represents positive zero.
Member Function Documentation
Halide::float16_t::operator float () const explicit
Cast to float.
Halide::float16_t::operator double () const explicit
Cast to double.
Halide::float16_t::operator int () const explicit
Cast to int.
static float16_t Halide::float16_t::make_zero () static
Get a new float16_t that represents a special value.
static float16_t Halide::float16_t::make_negative_zero () static
Get a new float16_t that represents a special value.
static float16_t Halide::float16_t::make_infinity () static
Get a new float16_t that represents a special value.
static float16_t Halide::float16_t::make_negative_infinity () static
Get a new float16_t that represents a special value.
static float16_t Halide::float16_t::make_nan () static
Get a new float16_t that represents a special value.
static float16_t Halide::float16_t::make_from_bits (uint16_t bits) static
Get a new float16_t with the given raw bits.
Parameters
bits The bits conformant to IEEE754 binary16
float16_t Halide::float16_t::operator- () const
Return a new float16_t with a negated sign bit.
float16_t Halide::float16_t::operator+ (float16_t rhs) const
Arithmetic operators.
float16_t Halide::float16_t::operator- (float16_t rhs) const
Arithmetic operators.
float16_t Halide::float16_t::operator* (float16_t rhs) const
Arithmetic operators.
float16_t Halide::float16_t::operator/ (float16_t rhs) const
Arithmetic operators.
float16_t Halide::float16_t::operator+= (float16_t rhs) inline
Arithmetic operators.
Definition at line 75 of file Float16.h.
float16_t Halide::float16_t::operator-= (float16_t rhs) inline
Arithmetic operators.
Definition at line 78 of file Float16.h.
float16_t Halide::float16_t::operator*= (float16_t rhs) inline
Arithmetic operators.
Definition at line 81 of file Float16.h.
float16_t Halide::float16_t::operator/= (float16_t rhs) inline
Arithmetic operators.
Definition at line 84 of file Float16.h.
References operator==().
bool Halide::float16_t::operator== (float16_t rhs) const
Comparison operators.
Referenced by operator/=(), and Halide::bfloat16_t::operator/=().
bool Halide::float16_t::operator!= (float16_t rhs) const inline
Comparison operators.
Definition at line 92 of file Float16.h.
References operator<(), and operator>().
bool Halide::float16_t::operator> (float16_t rhs) const
Comparison operators.
Referenced by operator!=(), and Halide::bfloat16_t::operator!=().
bool Halide::float16_t::operator< (float16_t rhs) const
Comparison operators.
Referenced by operator!=(), and Halide::bfloat16_t::operator!=().
bool Halide::float16_t::operator>= (float16_t rhs) const inline
Comparison operators.
Definition at line 97 of file Float16.h.
bool Halide::float16_t::operator<= (float16_t rhs) const inline
Comparison operators.
Definition at line 100 of file Float16.h.
References is_infinity(), is_nan(), is_negative(), is_zero(), and to_bits().
bool Halide::float16_t::is_nan () const
Properties.
Referenced by operator<=(), and Halide::bfloat16_t::operator<=().
bool Halide::float16_t::is_infinity () const
Properties.
Referenced by operator<=(), and Halide::bfloat16_t::operator<=().
bool Halide::float16_t::is_negative () const
Properties.
Referenced by operator<=(), and Halide::bfloat16_t::operator<=().
bool Halide::float16_t::is_zero () const
Properties.
Referenced by operator<=(), and Halide::bfloat16_t::operator<=().
uint16_t Halide::float16_t::to_bits () const
Returns the bits that represent this float16_t.
An alternative method to access the bits is to cast a pointer to this instance as a pointer to a uint16_t.
Referenced by operator<=(), and Halide::bfloat16_t::operator<=().
Member Data Documentation
const int Halide::float16_t::mantissa_bits = 10 static
Definition at line 19 of file Float16.h.
const uint16_t Halide::float16_t::sign_mask = 0x8000 static
Definition at line 20 of file Float16.h.
const uint16_t Halide::float16_t::exponent_mask = 0x7c00 static
Definition at line 21 of file Float16.h.
const uint16_t Halide::float16_t::mantissa_mask = 0x03ff static
Definition at line 22 of file Float16.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Float16.h