Halide: Halide::Internal::Weights Struct Reference
Halide::Internal::Weights Struct Reference
#include <Weights.h>
Public Member Functions
template<typename F >
void for_each_buffer (F f)
void randomize (uint32_t seed)
bool load (std::istream &i)
bool save (std::ostream &o) const
bool load_from_file (const std::string &filename)
bool save_to_file (const std::string &filename) const
bool load_from_dir (const std::string &dir)
bool save_to_dir (const std::string &dir) const
Public Attributes
uint32_t pipeline_features_version = PipelineFeatures::version()
uint32_t schedule_features_version = ScheduleFeatures::version()
Halide::Runtime::Buffer< float > head1_filter {head1_channels, head1_w, head1_h}
Halide::Runtime::Buffer< float > head1_bias {head1_channels}
Halide::Runtime::Buffer< float > head2_filter {head2_channels, head2_w}
Halide::Runtime::Buffer< float > head2_bias {head2_channels}
Halide::Runtime::Buffer< float > conv1_filter {conv1_channels, head1_channels + head2_channels}
Halide::Runtime::Buffer< float > conv1_bias {conv1_channels}
Detailed Description
Definition at line 15 of file Weights.h.
Member Function Documentation
template<typename F > void Halide::Internal::Weights::for_each_buffer (F f) inline
Definition at line 29 of file Weights.h.
References conv1_bias, conv1_filter, head1_bias, head1_filter, head2_bias, head2_filter, load(), load_from_dir(), load_from_file(), randomize(), save(), save_to_dir(), and save_to_file().
void Halide::Internal::Weights::randomize (uint32_t seed)
Referenced by for_each_buffer().
bool Halide::Internal::Weights::load (std::istream & i)
Referenced by for_each_buffer().
bool Halide::Internal::Weights::save (std::ostream & o) const
Referenced by for_each_buffer().
bool Halide::Internal::Weights::load_from_file (const std::string & filename)
Referenced by for_each_buffer().
bool Halide::Internal::Weights::save_to_file (const std::string & filename) const
Referenced by for_each_buffer().
bool Halide::Internal::Weights::load_from_dir (const std::string & dir)
Referenced by for_each_buffer().
bool Halide::Internal::Weights::save_to_dir (const std::string & dir) const
Referenced by for_each_buffer().
Member Data Documentation
uint32_t Halide::Internal::Weights::pipeline_features_version = PipelineFeatures::version()
Definition at line 16 of file Weights.h.
uint32_t Halide::Internal::Weights::schedule_features_version = ScheduleFeatures::version()
Definition at line 17 of file Weights.h.
Halide::Runtime::Buffer<float> Halide::Internal::Weights::head1_filter {head1_channels, head1_w, head1_h}
Definition at line 19 of file Weights.h.
Referenced by for_each_buffer().
Halide::Runtime::Buffer<float> Halide::Internal::Weights::head1_bias {head1_channels}
Definition at line 20 of file Weights.h.
Referenced by for_each_buffer().
Halide::Runtime::Buffer<float> Halide::Internal::Weights::head2_filter {head2_channels, head2_w}
Definition at line 22 of file Weights.h.
Referenced by for_each_buffer().
Halide::Runtime::Buffer<float> Halide::Internal::Weights::head2_bias {head2_channels}
Definition at line 23 of file Weights.h.
Referenced by for_each_buffer().
Halide::Runtime::Buffer<float> Halide::Internal::Weights::conv1_filter {conv1_channels, head1_channels + head2_channels}
Definition at line 25 of file Weights.h.
Referenced by for_each_buffer().
Halide::Runtime::Buffer<float> Halide::Internal::Weights::conv1_bias {conv1_channels}
Definition at line 26 of file Weights.h.
Referenced by for_each_buffer().
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/autoschedulers/adams2019/Weights.h