Halide: Halide::ParamMap::ParamMapping Struct Reference
Halide::ParamMap::ParamMapping Struct Reference
#include <ParamMap.h>
Public Member Functions
template<typename T >
ParamMapping (const Param< T > &p, const T &val)
ParamMapping (const ImageParam &p, Buffer<> &buf)
template<typename T >
ParamMapping (const ImageParam &p, Buffer< T > &buf)
ParamMapping (const ImageParam &p, Buffer<> *buf_ptr)
template<typename T >
ParamMapping (const ImageParam &p, Buffer< T > *buf_ptr)
Public Attributes
const Internal::Parameter * parameter {nullptr}
const ImageParam * image_param {nullptr}
halide_scalar_value_t value
Buffer buf
Buffer * buf_out_param
Detailed Description
Definition at line 19 of file ParamMap.h.
Constructor & Destructor Documentation
template<typename T > Halide::ParamMap::ParamMapping::ParamMapping (const Param< T > & p, const T & val) inline
Definition at line 27 of file ParamMap.h.
Halide::ParamMap::ParamMapping::ParamMapping (const ImageParam & p, Buffer<> & buf) inline
Definition at line 32 of file ParamMap.h.
template<typename T > Halide::ParamMap::ParamMapping::ParamMapping (const ImageParam & p, Buffer< T > & buf) inline
Definition at line 37 of file ParamMap.h.
Halide::ParamMap::ParamMapping::ParamMapping (const ImageParam & p, Buffer<> * buf_ptr) inline
Definition at line 41 of file ParamMap.h.
template<typename T > Halide::ParamMap::ParamMapping::ParamMapping (const ImageParam & p, Buffer< T > * buf_ptr) inline
Definition at line 46 of file ParamMap.h.
References buf, buf_out_param, Halide::Internal::Parameter::name(), parameter, Halide::Internal::Parameter::set_scalar(), Halide::Internal::Parameter::type(), and value.
Member Data Documentation
const Internal::Parameter* Halide::ParamMap::ParamMapping::parameter {nullptr}
Definition at line 20 of file ParamMap.h.
Referenced by ParamMapping().
const ImageParam* Halide::ParamMap::ParamMapping::image_param {nullptr}
Definition at line 21 of file ParamMap.h.
halide_scalar_value_t Halide::ParamMap::ParamMapping::value
Definition at line 22 of file ParamMap.h.
Referenced by ParamMapping().
Buffer Halide::ParamMap::ParamMapping::buf
Definition at line 23 of file ParamMap.h.
Referenced by ParamMapping(), and Halide::ParamMap::set().
Buffer* Halide::ParamMap::ParamMapping::buf_out_param
Definition at line 24 of file ParamMap.h.
Referenced by ParamMapping(), and Halide::ParamMap::size().
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/ParamMap.h