Halide: Halide::bfloat16_t Struct Reference
Halide::bfloat16_t Struct Reference
Class that provides a type that implements half precision floating point using the bfloat16 format.
#include <Float16.h>
Public Member Functions
bfloat16_t ()=default
Construct a bfloat16_t with the bits initialised to 0.
operator float () const
Cast to float.
operator double () const
Cast to double.
operator int () const
Cast to int.
bfloat16_t operator- () const
Return a new bfloat16_t with a negated sign bit.
uint16_t to_bits () const
Returns the bits that represent this bfloat16_t.
Constructors
bfloat16_t (float value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
bfloat16_t (double value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
bfloat16_t (int value)
Construct from a float, double, or int using round-to-nearest-ties-to-even.
bfloat16_t operator+ (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t operator- (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t operator* (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t operator/ (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t operator+= (bfloat16_t rhs)
Arithmetic operators.
bfloat16_t operator-= (bfloat16_t rhs)
Arithmetic operators.
bfloat16_t operator*= (bfloat16_t rhs)
Arithmetic operators.
bfloat16_t operator/= (bfloat16_t rhs)
Arithmetic operators.
bool operator== (bfloat16_t rhs) const
Comparison operators.
bool operator!= (bfloat16_t rhs) const
Comparison operators.
bool operator> (bfloat16_t rhs) const
Comparison operators.
bool operator< (bfloat16_t rhs) const
Comparison operators.
bool operator>= (bfloat16_t rhs) const
Comparison operators.
bool operator<= (bfloat16_t rhs) const
Comparison operators.
bool is_nan () const
Properties.
bool is_infinity () const
Properties.
bool is_negative () const
Properties.
bool is_zero () const
Properties.
Static Public Member Functions
static bfloat16_t make_from_bits (uint16_t bits)
Get a new bfloat16_t with the given raw bits.
static bfloat16_t make_zero ()
Get a new bfloat16_t that represents a special value.
static bfloat16_t make_negative_zero ()
Get a new bfloat16_t that represents a special value.
static bfloat16_t make_infinity ()
Get a new bfloat16_t that represents a special value.
static bfloat16_t make_negative_infinity ()
Get a new bfloat16_t that represents a special value.
static bfloat16_t make_nan ()
Get a new bfloat16_t that represents a special value.
Static Public Attributes
static const int mantissa_bits = 7
static const uint16_t sign_mask = 0x8000
static const uint16_t exponent_mask = 0x7f80
static const uint16_t mantissa_mask = 0x007f
static const bfloat16_t zero
static const bfloat16_t negative_zero
static const bfloat16_t infinity
static const bfloat16_t negative_infinity
static const bfloat16_t nan
Detailed Description
Class that provides a type that implements half precision floating point using the bfloat16 format.
This type is enforced to be 16-bits wide and maintains no state other than the raw bits so that it can passed to code that checks a type's size and used for halide_buffer_t allocation.
Definition at line 142 of file Float16.h.
Constructor & Destructor Documentation
Halide::bfloat16_t::bfloat16_t (float value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::bfloat16_t::bfloat16_t (double value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::bfloat16_t::bfloat16_t (int value) explicit
Construct from a float, double, or int using round-to-nearest-ties-to-even.
Out-of-range values become +/- infinity.
Halide::bfloat16_t::bfloat16_t () default
Construct a bfloat16_t with the bits initialised to 0.
This represents positive zero.
Member Function Documentation
Halide::bfloat16_t::operator float () const explicit
Cast to float.
Halide::bfloat16_t::operator double () const explicit
Cast to double.
Halide::bfloat16_t::operator int () const explicit
Cast to int.
static bfloat16_t Halide::bfloat16_t::make_zero () static
Get a new bfloat16_t that represents a special value.
static bfloat16_t Halide::bfloat16_t::make_negative_zero () static
Get a new bfloat16_t that represents a special value.
static bfloat16_t Halide::bfloat16_t::make_infinity () static
Get a new bfloat16_t that represents a special value.
static bfloat16_t Halide::bfloat16_t::make_negative_infinity () static
Get a new bfloat16_t that represents a special value.
static bfloat16_t Halide::bfloat16_t::make_nan () static
Get a new bfloat16_t that represents a special value.
static bfloat16_t Halide::bfloat16_t::make_from_bits (uint16_t bits) static
Get a new bfloat16_t with the given raw bits.
Parameters
bits The bits conformant to IEEE754 binary16
bfloat16_t Halide::bfloat16_t::operator- () const
Return a new bfloat16_t with a negated sign bit.
bfloat16_t Halide::bfloat16_t::operator+ (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t Halide::bfloat16_t::operator- (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t Halide::bfloat16_t::operator* (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t Halide::bfloat16_t::operator/ (bfloat16_t rhs) const
Arithmetic operators.
bfloat16_t Halide::bfloat16_t::operator+= (bfloat16_t rhs) inline
Arithmetic operators.
Definition at line 202 of file Float16.h.
bfloat16_t Halide::bfloat16_t::operator-= (bfloat16_t rhs) inline
Arithmetic operators.
Definition at line 205 of file Float16.h.
bfloat16_t Halide::bfloat16_t::operator*= (bfloat16_t rhs) inline
Arithmetic operators.
Definition at line 208 of file Float16.h.
bfloat16_t Halide::bfloat16_t::operator/= (bfloat16_t rhs) inline
Arithmetic operators.
Definition at line 211 of file Float16.h.
References Halide::float16_t::operator==().
bool Halide::bfloat16_t::operator== (bfloat16_t rhs) const
Comparison operators.
bool Halide::bfloat16_t::operator!= (bfloat16_t rhs) const inline
Comparison operators.
Definition at line 219 of file Float16.h.
References Halide::float16_t::operator<(), and Halide::float16_t::operator>().
bool Halide::bfloat16_t::operator> (bfloat16_t rhs) const
Comparison operators.
bool Halide::bfloat16_t::operator< (bfloat16_t rhs) const
Comparison operators.
bool Halide::bfloat16_t::operator>= (bfloat16_t rhs) const inline
Comparison operators.
Definition at line 224 of file Float16.h.
bool Halide::bfloat16_t::operator<= (bfloat16_t rhs) const inline
Comparison operators.
Definition at line 227 of file Float16.h.
References Halide::float16_t::is_infinity(), Halide::float16_t::is_nan(), Halide::float16_t::is_negative(), Halide::float16_t::is_zero(), and Halide::float16_t::to_bits().
bool Halide::bfloat16_t::is_nan () const
Properties.
bool Halide::bfloat16_t::is_infinity () const
Properties.
bool Halide::bfloat16_t::is_negative () const
Properties.
bool Halide::bfloat16_t::is_zero () const
Properties.
uint16_t Halide::bfloat16_t::to_bits () const
Returns the bits that represent this bfloat16_t.
An alternative method to access the bits is to cast a pointer to this instance as a pointer to a uint16_t.
Member Data Documentation
const int Halide::bfloat16_t::mantissa_bits = 7 static
Definition at line 144 of file Float16.h.
const uint16_t Halide::bfloat16_t::sign_mask = 0x8000 static
Definition at line 145 of file Float16.h.
const uint16_t Halide::bfloat16_t::exponent_mask = 0x7f80 static
Definition at line 146 of file Float16.h.
const uint16_t Halide::bfloat16_t::mantissa_mask = 0x007f static
Definition at line 147 of file Float16.h.
const bfloat16_t Halide::bfloat16_t::zero static
Definition at line 149 of file Float16.h.
const bfloat16_t Halide::bfloat16_t::negative_zero static
Definition at line 149 of file Float16.h.
const bfloat16_t Halide::bfloat16_t::infinity static
Definition at line 149 of file Float16.h.
const bfloat16_t Halide::bfloat16_t::negative_infinity static
Definition at line 149 of file Float16.h.
const bfloat16_t Halide::bfloat16_t::nan static
Definition at line 149 of file Float16.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Float16.h