Halide: Halide::Internal::AssociativePattern Struct Reference
Halide::Internal::AssociativePattern Struct Reference
Represent an associative op with its identity.
#include <AssociativeOpsTable.h>
Public Member Functions
AssociativePattern ()
AssociativePattern (size_t size)
AssociativePattern (const std::vector< Expr > &ops, const std::vector< Expr > &ids, bool is_commutative)
AssociativePattern (Expr op, Expr id, bool is_commutative)
identities ({id})
is_commutative (is_commutative)
bool operator== (const AssociativePattern &other) const
bool operator!= (const AssociativePattern &other) const
size_t size () const
bool commutative () const
Public Attributes
std::vector< Expr > ops
Contain the binary operators for each dimension of the associative op.
std::vector< Expr > identities
Contain the identities for each dimension of the associative op.
bool is_commutative
Indicate if the associative op is also commutative.
Detailed Description
Represent an associative op with its identity.
The op may be multi-dimensional, e.g. complex multiplication. 'is_commutative' is set to true if the op is also commutative in addition to being associative.
For example, complex multiplication is represented as:
AssociativePattern pattern(
   {x0 * y0 - x1 * y1, x1 * y0 + x0 * y1},
   {one, zero},
   true
);
Definition at line 31 of file AssociativeOpsTable.h.
Constructor & Destructor Documentation
Halide::Internal::AssociativePattern::AssociativePattern () inline
Definition at line 39 of file AssociativeOpsTable.h.
Halide::Internal::AssociativePattern::AssociativePattern (size_t size) inline
Definition at line 40 of file AssociativeOpsTable.h.
Halide::Internal::AssociativePattern::AssociativePattern (const std::vector< Expr > & ops, const std::vector< Expr > & ids, bool is_commutative) inline
Definition at line 41 of file AssociativeOpsTable.h.
Halide::Internal::AssociativePattern::AssociativePattern (Expr op, Expr id, bool is_commutative) inline
Definition at line 43 of file AssociativeOpsTable.h.
Member Function Documentation
Halide::Internal::AssociativePattern::identities ({id})
Halide::Internal::AssociativePattern::is_commutative (is_commutative) inline
Definition at line 44 of file AssociativeOpsTable.h.
bool Halide::Internal::AssociativePattern::operator== (const AssociativePattern & other) const inline
Definition at line 46 of file AssociativeOpsTable.h.
References Halide::Internal::equal(), identities, is_commutative, ops, and size().
bool Halide::Internal::AssociativePattern::operator!= (const AssociativePattern & other) const inline
Definition at line 57 of file AssociativeOpsTable.h.
size_t Halide::Internal::AssociativePattern::size () const inline
Definition at line 58 of file AssociativeOpsTable.h.
References ops.
Referenced by operator==(), and Halide::Internal::AssociativeOp::size().
bool Halide::Internal::AssociativePattern::commutative () const inline
Definition at line 59 of file AssociativeOpsTable.h.
References is_commutative.
Member Data Documentation
std::vector<Expr> Halide::Internal::AssociativePattern::ops
Contain the binary operators for each dimension of the associative op.
Definition at line 33 of file AssociativeOpsTable.h.
Referenced by operator==(), and size().
std::vector<Expr> Halide::Internal::AssociativePattern::identities
Contain the identities for each dimension of the associative op.
Definition at line 35 of file AssociativeOpsTable.h.
Referenced by operator==().
bool Halide::Internal::AssociativePattern::is_commutative
Indicate if the associative op is also commutative.
Definition at line 37 of file AssociativeOpsTable.h.
Referenced by commutative(), Halide::Internal::AssociativeOp::commutative(), and operator==().
The documentation for this struct was generated from the following file:
AssociativeOpsTable.h