Halide: Halide::ImplicitVar< N > Struct Template Reference
Halide::ImplicitVar< N > Struct Template Reference
#include <Var.h>
Public Member Functions
Var to_var () const
operator Var () const
operator Expr () const
Detailed Description
template<int N = -1>
struct Halide::ImplicitVar< N >
Definition at line 169 of file Var.h.
Member Function Documentation
template<int N = -1> Var Halide::ImplicitVar< N >::to_var () const inline
Definition at line 170 of file Var.h.
References Halide::Var::implicit(), and Halide::Var::Var().
template<int N = -1> Halide::ImplicitVar< N >::operator Var () const inline
Definition at line 178 of file Var.h.
template<int N = -1> Halide::ImplicitVar< N >::operator Expr () const inline
Definition at line 181 of file Var.h.
References Halide::Internal, and Halide::Internal::make_argument_list().
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Var.h