Halide: Halide::Internal::LoopLevel Struct Reference
Halide::Internal::LoopLevel Struct Reference
A reference to a site in a Halide statement at the top of the body of a particular for loop.
#include <Schedule.h>
Public Member Functions
LoopLevel (std::string f, std::string v)
Identify the loop nest corresponding to some dimension of some function.
LoopLevel ()
Construct an empty LoopLevel, which is interpreted as 'inline'.
bool is_inline () const
Test if a loop level corresponds to inlining the function.
bool is_root () const
Test if a loop level is 'root', which describes the site outside of all for loops.
bool match (const std::string &loop) const
Compare this loop level against the variable name of a for loop, to see if this loop level refers to the site immediately inside this loop.
bool match (const LoopLevel &other) const
bool operator== (const LoopLevel &other) const
Check if two loop levels are exactly the same.
Static Public Member Functions
static LoopLevel root ()
root is a special LoopLevel value which represents the location outside of all for loops
Public Attributes
std::string func
std::string var
Detailed Description
A reference to a site in a Halide statement at the top of the body of a particular for loop.
Evaluating a region of a halide function is done by generating a loop nest that spans its dimensions. We schedule the inputs to that function by recursively injecting realizations for them at particular sites in this loop nest. A LoopLevel identifies such a site.
Definition at line 21 of file Schedule.h.
Constructor & Destructor Documentation
Halide::Internal::LoopLevel::LoopLevel (std::string f, std::string v) inline
Identify the loop nest corresponding to some dimension of some function.
Definition at line 25 of file Schedule.h.
Halide::Internal::LoopLevel::LoopLevel () inline
Construct an empty LoopLevel, which is interpreted as 'inline'.
This is a special LoopLevel value that implies that a function should be inlined away
Definition at line 30 of file Schedule.h.
Referenced by root().
Member Function Documentation
bool Halide::Internal::LoopLevel::is_inline () const inline
Test if a loop level corresponds to inlining the function.
Definition at line 33 of file Schedule.h.
References var.
static LoopLevel Halide::Internal::LoopLevel::root () inline static
root is a special LoopLevel value which represents the location outside of all for loops
Definition at line 37 of file Schedule.h.
References LoopLevel().
bool Halide::Internal::LoopLevel::is_root () const inline
Test if a loop level is 'root', which describes the site outside of all for loops.
Definition at line 42 of file Schedule.h.
References var.
bool Halide::Internal::LoopLevel::match (const std::string & loop) const inline
Compare this loop level against the variable name of a for loop, to see if this loop level refers to the site immediately inside this loop.
Definition at line 47 of file Schedule.h.
References Halide::Internal::ends_with(), func, Halide::Internal::starts_with(), and var.
bool Halide::Internal::LoopLevel::match (const LoopLevel & other) const inline
Definition at line 51 of file Schedule.h.
References Halide::Internal::ends_with(), func, and var.
bool Halide::Internal::LoopLevel::operator== (const LoopLevel & other) const inline
Check if two loop levels are exactly the same.
Definition at line 59 of file Schedule.h.
References func, and var.
Member Data Documentation
std::string Halide::Internal::LoopLevel::func
Definition at line 22 of file Schedule.h.
Referenced by match(), and operator==().
std::string Halide::Internal::LoopLevel::var
Definition at line 22 of file Schedule.h.
Referenced by is_inline(), is_root(), match(), and operator==().
The documentation for this struct was generated from the following file:
Schedule.h