Halide: Halide::Internal::Variable Struct Reference
Halide::Internal::Variable Struct Reference
A named variable.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Variable >.
Static Public Member Functions
static Expr make (Type type, std::string name)
static Expr make (Type type, std::string name, Parameter param)
static Expr make (Type type, std::string name, ReductionDomain reduction_domain)
static Expr make (Type type, std::string name, Parameter param, ReductionDomain reduction_domain)
Public Attributes
std::string name
Parameter param
References to scalar parameters, or to the dimensions of buffer parameters hang onto those expressions.
ReductionDomain reduction_domain
Reduction variables hang onto their domains.
Detailed Description
A named variable.
Might be a loop variable, function argument, parameter, reduction variable, or something defined by a Let or LetStmt node.
Definition at line 1026 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::Variable::make (Type type, std::string name) [inline, static]
Definition at line 1036 of file IR.h.
Referenced by Halide::OutputImageParam::extent(), make(), Halide::Param< T >::operator Expr(), Halide::Var::operator Expr(), and Halide::OutputImageParam::stride().
static Expr Halide::Internal::Variable::make (Type type, std::string name, Parameter param) [inline, static]
Definition at line 1040 of file IR.h.
References make().
static Expr Halide::Internal::Variable::make (Type type, std::string name, ReductionDomain reduction_domain) [inline, static]
Definition at line 1044 of file IR.h.
References make().
static Expr Halide::Internal::Variable::make (Type type, std::string name, Parameter param, ReductionDomain reduction_domain) [inline, static]
Definition at line 1048 of file IR.h.
References name, param, reduction_domain, and Halide::Internal::BaseExprNode::type.
Member Data Documentation
std::string Halide::Internal::Variable::name
Definition at line 1027 of file IR.h.
Referenced by Halide::OutputImageParam::add_implicit_args_if_placeholder(), and make().
Parameter Halide::Internal::Variable::param
References to scalar parameters, or to the dimensions of buffer parameters hang onto those expressions.
Definition at line 1031 of file IR.h.
Referenced by make().
ReductionDomain Halide::Internal::Variable::reduction_domain
Reduction variables hang onto their domains.
Definition at line 1034 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h