Halide: Halide::Internal::Call Struct Reference
Halide::Internal::Call Struct Reference
A function call.
#include <IR.h>
Inherits Halide::Internal::ExprNode< Call >.
Public Types
enum CallType {
Image, Extern, ExternCPlusPlus, PureExtern,
Halide, Intrinsic, PureIntrinsic
}
typedef const char *const ConstString
Public Member Functions
bool is_pure () const
Check if a call node is pure within a pipeline, meaning that the same args always give the same result, and the calls can be reordered, duplicated, unified, etc without changing the meaning of anything.
bool is_intrinsic () const
bool is_intrinsic (ConstString intrin_name) const
bool is_extern () const
Public Member Functions inherited from Halide::Internal::ExprNode< Call >
EXPORT void accept (IRVisitor *v) const
We use the visitor pattern to traverse IR nodes throughout the compiler, so we have a virtual accept method which accepts visitors.
EXPORT Expr mutate_expr (IRMutator2 *v) const
ExprNode ()
virtual ~ExprNode ()
Public Member Functions inherited from Halide::Internal::BaseExprNode
BaseExprNode (IRNodeType t)
Public Member Functions inherited from Halide::Internal::IRNode
IRNode (IRNodeType t)
virtual ~IRNode ()
Static Public Member Functions
static EXPORT Expr make (Type type, const std::string &name, const std::vector< Expr > &args, CallType call_type, FunctionPtr func=FunctionPtr(), int value_index=0, Buffer<> image=Buffer<>(), Parameter param=Parameter())
static EXPORT Expr make (Function func, const std::vector< Expr > &args, int idx=0)
Convenience constructor for calls to other halide functions.
static Expr make (Buffer<> image, const std::vector< Expr > &args)
Convenience constructor for loads from concrete images.
static Expr make (Parameter param, const std::vector< Expr > &args)
Convenience constructor for loads from images parameters.
Public Attributes
std::string name
std::vector< Expr > args
CallType call_type
FunctionPtr func
int value_index
Buffer image
Parameter param
Public Attributes inherited from Halide::Internal::BaseExprNode
Type type
Public Attributes inherited from Halide::Internal::IRNode
RefCount ref_count
These classes are all managed with intrusive reference counting, so we also track a reference count.
IRNodeType node_type
Each IR node subclass has a unique identifier.
Static Public Attributes
static EXPORT ConstString debug_to_file
static EXPORT ConstString reinterpret
static EXPORT ConstString bitwise_and
static EXPORT ConstString bitwise_not
static EXPORT ConstString bitwise_xor
static EXPORT ConstString bitwise_or
static EXPORT ConstString shift_left
static EXPORT ConstString shift_right
static EXPORT ConstString abs
static EXPORT ConstString absd
static EXPORT ConstString rewrite_buffer
static EXPORT ConstString random
static EXPORT ConstString lerp
static EXPORT ConstString popcount
static EXPORT ConstString count_leading_zeros
static EXPORT ConstString count_trailing_zeros
static EXPORT ConstString undef
static EXPORT ConstString return_second
static EXPORT ConstString if_then_else
static EXPORT ConstString glsl_texture_load
static EXPORT ConstString glsl_texture_store
static EXPORT ConstString glsl_varying
static EXPORT ConstString image_load
static EXPORT ConstString image_store
static EXPORT ConstString make_struct
static EXPORT ConstString stringify
static EXPORT ConstString memoize_expr
static EXPORT ConstString alloca
static EXPORT ConstString likely
static EXPORT ConstString likely_if_innermost
static EXPORT ConstString register_destructor
static EXPORT ConstString div_round_to_zero
static EXPORT ConstString mod_round_to_zero
static EXPORT ConstString call_cached_indirect_function
static EXPORT ConstString prefetch
static EXPORT ConstString signed_integer_overflow
static EXPORT ConstString indeterminate_expression
static EXPORT ConstString bool_to_mask
static EXPORT ConstString cast_mask
static EXPORT ConstString select_mask
static EXPORT ConstString extract_mask_element
static EXPORT ConstString require
static EXPORT ConstString size_of_halide_buffer_t
static EXPORT ConstString buffer_get_min
static EXPORT ConstString buffer_get_extent
static EXPORT ConstString buffer_get_stride
static EXPORT ConstString buffer_get_max
static EXPORT ConstString buffer_get_host
static EXPORT ConstString buffer_get_device
static EXPORT ConstString buffer_get_device_interface
static EXPORT ConstString buffer_get_shape
static EXPORT ConstString buffer_get_host_dirty
static EXPORT ConstString buffer_get_device_dirty
static EXPORT ConstString buffer_get_type_code
static EXPORT ConstString buffer_get_type_bits
static EXPORT ConstString buffer_get_type_lanes
static EXPORT ConstString buffer_set_host_dirty
static EXPORT ConstString buffer_set_device_dirty
static EXPORT ConstString buffer_is_bounds_query
static EXPORT ConstString buffer_init
static EXPORT ConstString buffer_init_from_buffer
static EXPORT ConstString buffer_crop
static EXPORT ConstString buffer_set_bounds
static EXPORT ConstString trace
static const IRNodeType _node_type = IRNodeType::Call
Detailed Description
A function call.
This can represent a call to some extern function (like sin), but it's also our multi-dimensional version of a Load, so it can be a load from an input image, or a call to another halide function. These two types of call nodes don't survive all the way down to code generation - the lowering process converts them to Load nodes.
Definition at line 453 of file IR.h.
Member Typedef Documentation
ConstString
typedef const char* const Halide::Internal::Call::ConstString
Definition at line 472 of file IR.h.
Member Enumeration Documentation
CallType
enum Halide::Internal::Call::CallType
Enumerator
Image
A load from an input image.
Extern
A call to an external C-ABI function, possibly with side-effects.
ExternCPlusPlus
A call to an external C-ABI function, possibly with side-effects.
PureExtern
A call to a guaranteed-side-effect-free external function.
Halide
A call to a Func.
Intrinsic
A possibly-side-effecty compiler intrinsic, which has special handling during codegen.
PureIntrinsic
A side-effect-free version of the above.
Definition at line 456 of file IR.h.
Member Function Documentation
make() [1/4]
static EXPORT Expr Halide::Internal::Call::make (Type type, const std::string & name, const std::vector< Expr > & args, CallType call_type, FunctionPtr func = FunctionPtr(), int value_index = 0, Buffer<> image = Buffer<>(), Parameter param = Parameter()) static
Referenced by Halide::abs(), Halide::absd(), Halide::acos(), Halide::acosh(), Halide::asin(), Halide::asinh(), Halide::atan(), Halide::atan2(), Halide::atanh(), Halide::ceil(), Halide::cos(), Halide::cosh(), Halide::count_leading_zeros(), Halide::count_trailing_zeros(), Halide::div_round_to_zero(), Halide::exp(), Halide::fast_inverse(), Halide::fast_inverse_sqrt(), Halide::floor(), Halide::is_nan(), Halide::lerp(), Halide::likely(), Halide::likely_if_innermost(), Halide::log(), Halide::mod_round_to_zero(), Halide::operator &(), Halide::operator<<(), Halide::operator>>(), Halide::operator^(), Halide::operator|(), Halide::operator~(), Halide::popcount(), Halide::pow(), Halide::random_float(), Halide::random_uint(), Halide::reinterpret(), Halide::round(), Halide::sin(), Halide::sinh(), Halide::sqrt(), Halide::tan(), Halide::tanh(), Halide::trunc(), and Halide::undef().
make() [2/4]
static EXPORT Expr Halide::Internal::Call::make (Function func, const std::vector< Expr > & args, int idx = 0) static
Convenience constructor for calls to other halide functions.
make() [3/4]
static Expr Halide::Internal::Call::make (Buffer<> image, const std::vector< Expr > & args) inline static
Convenience constructor for loads from concrete images.
Definition at line 567 of file IR.h.
References Halide::Internal::Cast::make(), Halide::Buffer< T >::name(), and Halide::Buffer< T >::type().
make() [4/4]
static Expr Halide::Internal::Call::make (Parameter param, const std::vector< Expr > & args) inline static
Convenience constructor for loads from images parameters.
Definition at line 572 of file IR.h.
References Halide::Internal::Cast::make(), Halide::Internal::Parameter::name(), and Halide::Internal::Parameter::type().
is_pure()
bool Halide::Internal::Call::is_pure () const inline
Check if a call node is pure within a pipeline, meaning that the same args always give the same result, and the calls can be reordered, duplicated, unified, etc without changing the meaning of anything.
Not transitive - doesn't guarantee the args themselves are pure. An example of a pure Call node is sqrt. If in doubt, don't mark a Call node as pure.
Definition at line 582 of file IR.h.
is_intrinsic() [1/2]
bool Halide::Internal::Call::is_intrinsic () const inline
Definition at line 588 of file IR.h.
is_intrinsic() [2/2]
bool Halide::Internal::Call::is_intrinsic (ConstString intrin_name) const inline
Definition at line 593 of file IR.h.
is_extern()
bool Halide::Internal::Call::is_extern () const inline
Definition at line 597 of file IR.h.
Member Data Documentation
name
std::string Halide::Internal::Call::name
Definition at line 454 of file IR.h.
args
std::vector<Expr> Halide::Internal::Call::args
Definition at line 455 of file IR.h.
call_type
CallType Halide::Internal::Call::call_type
Definition at line 464 of file IR.h.
debug_to_file
EXPORT ConstString Halide::Internal::Call::debug_to_file static
Definition at line 473 of file IR.h.
reinterpret
EXPORT ConstString Halide::Internal::Call::reinterpret static
Definition at line 473 of file IR.h.
Referenced by Halide::reinterpret().
bitwise_and
EXPORT ConstString Halide::Internal::Call::bitwise_and static
Definition at line 473 of file IR.h.
Referenced by Halide::operator &().
bitwise_not
EXPORT ConstString Halide::Internal::Call::bitwise_not static
Definition at line 473 of file IR.h.
Referenced by Halide::operator~().
bitwise_xor
EXPORT ConstString Halide::Internal::Call::bitwise_xor static
Definition at line 473 of file IR.h.
Referenced by Halide::operator^().
bitwise_or
EXPORT ConstString Halide::Internal::Call::bitwise_or static
Definition at line 473 of file IR.h.
Referenced by Halide::operator|().
shift_left
EXPORT ConstString Halide::Internal::Call::shift_left static
Definition at line 473 of file IR.h.
Referenced by Halide::operator<<().
shift_right
EXPORT ConstString Halide::Internal::Call::shift_right static
Definition at line 473 of file IR.h.
Referenced by Halide::operator>>().
abs
EXPORT ConstString Halide::Internal::Call::abs static
Definition at line 473 of file IR.h.
Referenced by Halide::abs().
absd
EXPORT ConstString Halide::Internal::Call::absd static
Definition at line 473 of file IR.h.
Referenced by Halide::absd().
rewrite_buffer
EXPORT ConstString Halide::Internal::Call::rewrite_buffer static
Definition at line 473 of file IR.h.
random
EXPORT ConstString Halide::Internal::Call::random static
Definition at line 473 of file IR.h.
Referenced by Halide::random_float(), and Halide::random_uint().
lerp
EXPORT ConstString Halide::Internal::Call::lerp static
Definition at line 473 of file IR.h.
Referenced by Halide::lerp().
popcount
EXPORT ConstString Halide::Internal::Call::popcount static
Definition at line 473 of file IR.h.
Referenced by Halide::popcount().
count_leading_zeros
EXPORT ConstString Halide::Internal::Call::count_leading_zeros static
Definition at line 473 of file IR.h.
Referenced by Halide::count_leading_zeros().
count_trailing_zeros
EXPORT ConstString Halide::Internal::Call::count_trailing_zeros static
Definition at line 473 of file IR.h.
Referenced by Halide::count_trailing_zeros().
undef
EXPORT ConstString Halide::Internal::Call::undef static
Definition at line 473 of file IR.h.
Referenced by Halide::undef().
return_second
EXPORT ConstString Halide::Internal::Call::return_second static
Definition at line 473 of file IR.h.
if_then_else
EXPORT ConstString Halide::Internal::Call::if_then_else static
Definition at line 473 of file IR.h.
glsl_texture_load
EXPORT ConstString Halide::Internal::Call::glsl_texture_load static
Definition at line 473 of file IR.h.
glsl_texture_store
EXPORT ConstString Halide::Internal::Call::glsl_texture_store static
Definition at line 473 of file IR.h.
glsl_varying
EXPORT ConstString Halide::Internal::Call::glsl_varying static
Definition at line 473 of file IR.h.
image_load
EXPORT ConstString Halide::Internal::Call::image_load static
Definition at line 473 of file IR.h.
image_store
EXPORT ConstString Halide::Internal::Call::image_store static
Definition at line 473 of file IR.h.
make_struct
EXPORT ConstString Halide::Internal::Call::make_struct static
Definition at line 473 of file IR.h.
stringify
EXPORT ConstString Halide::Internal::Call::stringify static
Definition at line 473 of file IR.h.
memoize_expr
EXPORT ConstString Halide::Internal::Call::memoize_expr static
Definition at line 473 of file IR.h.
alloca
EXPORT ConstString Halide::Internal::Call::alloca static
Definition at line 473 of file IR.h.
likely
EXPORT ConstString Halide::Internal::Call::likely static
Definition at line 473 of file IR.h.
Referenced by Halide::likely().
likely_if_innermost
EXPORT ConstString Halide::Internal::Call::likely_if_innermost static
Definition at line 473 of file IR.h.
Referenced by Halide::likely_if_innermost().
register_destructor
EXPORT ConstString Halide::Internal::Call::register_destructor static
Definition at line 473 of file IR.h.
div_round_to_zero
EXPORT ConstString Halide::Internal::Call::div_round_to_zero static
Definition at line 473 of file IR.h.
Referenced by Halide::div_round_to_zero().
mod_round_to_zero
EXPORT ConstString Halide::Internal::Call::mod_round_to_zero static
Definition at line 473 of file IR.h.
Referenced by Halide::mod_round_to_zero().
call_cached_indirect_function
EXPORT ConstString Halide::Internal::Call::call_cached_indirect_function static
Definition at line 473 of file IR.h.
prefetch
EXPORT ConstString Halide::Internal::Call::prefetch static
Definition at line 473 of file IR.h.
signed_integer_overflow
EXPORT ConstString Halide::Internal::Call::signed_integer_overflow static
Definition at line 473 of file IR.h.
indeterminate_expression
EXPORT ConstString Halide::Internal::Call::indeterminate_expression static
Definition at line 473 of file IR.h.
bool_to_mask
EXPORT ConstString Halide::Internal::Call::bool_to_mask static
Definition at line 473 of file IR.h.
cast_mask
EXPORT ConstString Halide::Internal::Call::cast_mask static
Definition at line 473 of file IR.h.
select_mask
EXPORT ConstString Halide::Internal::Call::select_mask static
Definition at line 473 of file IR.h.
extract_mask_element
EXPORT ConstString Halide::Internal::Call::extract_mask_element static
Definition at line 473 of file IR.h.
require
EXPORT ConstString Halide::Internal::Call::require static
Definition at line 473 of file IR.h.
size_of_halide_buffer_t
EXPORT ConstString Halide::Internal::Call::size_of_halide_buffer_t static
Definition at line 473 of file IR.h.
buffer_get_min
EXPORT ConstString Halide::Internal::Call::buffer_get_min static
Definition at line 521 of file IR.h.
buffer_get_extent
EXPORT ConstString Halide::Internal::Call::buffer_get_extent static
Definition at line 521 of file IR.h.
buffer_get_stride
EXPORT ConstString Halide::Internal::Call::buffer_get_stride static
Definition at line 521 of file IR.h.
buffer_get_max
EXPORT ConstString Halide::Internal::Call::buffer_get_max static
Definition at line 521 of file IR.h.
buffer_get_host
EXPORT ConstString Halide::Internal::Call::buffer_get_host static
Definition at line 521 of file IR.h.
buffer_get_device
EXPORT ConstString Halide::Internal::Call::buffer_get_device static
Definition at line 521 of file IR.h.
buffer_get_device_interface
EXPORT ConstString Halide::Internal::Call::buffer_get_device_interface static
Definition at line 521 of file IR.h.
buffer_get_shape
EXPORT ConstString Halide::Internal::Call::buffer_get_shape static
Definition at line 521 of file IR.h.
buffer_get_host_dirty
EXPORT ConstString Halide::Internal::Call::buffer_get_host_dirty static
Definition at line 521 of file IR.h.
buffer_get_device_dirty
EXPORT ConstString Halide::Internal::Call::buffer_get_device_dirty static
Definition at line 521 of file IR.h.
buffer_get_type_code
EXPORT ConstString Halide::Internal::Call::buffer_get_type_code static
Definition at line 521 of file IR.h.
buffer_get_type_bits
EXPORT ConstString Halide::Internal::Call::buffer_get_type_bits static
Definition at line 521 of file IR.h.
buffer_get_type_lanes
EXPORT ConstString Halide::Internal::Call::buffer_get_type_lanes static
Definition at line 521 of file IR.h.
buffer_set_host_dirty
EXPORT ConstString Halide::Internal::Call::buffer_set_host_dirty static
Definition at line 521 of file IR.h.
buffer_set_device_dirty
EXPORT ConstString Halide::Internal::Call::buffer_set_device_dirty static
Definition at line 521 of file IR.h.
buffer_is_bounds_query
EXPORT ConstString Halide::Internal::Call::buffer_is_bounds_query static
Definition at line 521 of file IR.h.
buffer_init
EXPORT ConstString Halide::Internal::Call::buffer_init static
Definition at line 521 of file IR.h.
buffer_init_from_buffer
EXPORT ConstString Halide::Internal::Call::buffer_init_from_buffer static
Definition at line 521 of file IR.h.
buffer_crop
EXPORT ConstString Halide::Internal::Call::buffer_crop static
Definition at line 521 of file IR.h.
buffer_set_bounds
EXPORT ConstString Halide::Internal::Call::buffer_set_bounds static
Definition at line 521 of file IR.h.
trace
EXPORT ConstString Halide::Internal::Call::trace static
Definition at line 521 of file IR.h.
func
FunctionPtr Halide::Internal::Call::func
Definition at line 545 of file IR.h.
value_index
int Halide::Internal::Call::value_index
Definition at line 549 of file IR.h.
image
Buffer Halide::Internal::Call::image
Definition at line 553 of file IR.h.
param
Parameter Halide::Internal::Call::param
Definition at line 557 of file IR.h.
_node_type
const IRNodeType Halide::Internal::Call::_node_type = IRNodeType::Call static
Definition at line 603 of file IR.h.
The documentation for this struct was generated from the following file:
IR.h