Halide: Halide::Expr Struct Reference
Halide::Expr Struct Reference
A fragment of Halide syntax.
#include <Expr.h>
Inherits Halide::Internal::IRHandle.
Public Member Functions
HALIDE_ALWAYS_INLINE Expr ()=default
Make an undefined expression.
HALIDE_ALWAYS_INLINE Expr (const Internal::BaseExprNode *n)
Make an expression from a concrete expression node pointer (e.g.
Expr (const std::string &s)
Make an expression representing a const string (i.e.
HALIDE_ALWAYS_INLINE const Internal::BaseExprNode * get () const
Override get() to return a BaseExprNode * instead of an IRNode *.
HALIDE_ALWAYS_INLINE Type type () const
Get the type of this expression node.
Expr (int8_t x)
Make an expression representing numeric constants of various types.
Expr (int16_t x)
Make an expression representing numeric constants of various types.
Expr (int32_t x)
Make an expression representing numeric constants of various types.
Expr (int64_t x)
Make an expression representing numeric constants of various types.
Expr (uint8_t x)
Make an expression representing numeric constants of various types.
Expr (uint16_t x)
Make an expression representing numeric constants of various types.
Expr (uint32_t x)
Make an expression representing numeric constants of various types.
Expr (uint64_t x)
Make an expression representing numeric constants of various types.
Expr (float16_t x)
Make an expression representing numeric constants of various types.
Expr (bfloat16_t x)
Make an expression representing numeric constants of various types.
Expr (float x)
Make an expression representing numeric constants of various types.
Expr (double x)
Make an expression representing numeric constants of various types.
Public Member Functions inherited from Halide::Internal::IRHandle
HALIDE_ALWAYS_INLINE IRHandle ()=default
HALIDE_ALWAYS_INLINE IRHandle (const IRNode *p)
void accept (IRVisitor *v) const
Dispatch to the correct visitor method for this node.
template<typename T >
const T * as () const
Downcast this ir node to its actual type (e.g.
IRNodeType node_type () const
Public Member Functions inherited from Halide::Internal::IntrusivePtr< const IRNode >
~IntrusivePtr ()
HALIDE_ALWAYS_INLINE IntrusivePtr ()=default
HALIDE_ALWAYS_INLINE IntrusivePtr (const IRNode *p)
HALIDE_ALWAYS_INLINE IntrusivePtr (const IntrusivePtr< const IRNode > &other) noexcept
HALIDE_ALWAYS_INLINE IntrusivePtr (IntrusivePtr< const IRNode > &&other) noexcept
IntrusivePtr< const IRNode > & operator= (const IntrusivePtr< const IRNode > &other)
IntrusivePtr< const IRNode > & operator= (IntrusivePtr< const IRNode > &&other) noexcept
HALIDE_ALWAYS_INLINE bool defined () const
HALIDE_ALWAYS_INLINE bool same_as (const IntrusivePtr &other) const
HALIDE_ALWAYS_INLINE bool operator< (const IntrusivePtr< const IRNode > &other) const
const IRNode * get () const
Access the raw pointer in a variety of ways.
const IRNode & operator* () const
Access the raw pointer in a variety of ways.
const IRNode * operator-> () const
Access the raw pointer in a variety of ways.
Additional Inherited Members
Protected Attributes inherited from Halide::Internal::IntrusivePtr< const IRNode >
const IRNode * ptr
Detailed Description
A fragment of Halide syntax.
It's implemented as reference-counted handle to a concrete expression node, but it's immutable, so you can treat it as a value type.
Examples:
tutorial/lesson_01_basics.cpp, tutorial/lesson_02_input_image.cpp, tutorial/lesson_04_debugging_2.cpp, tutorial/lesson_07_multi_stage_pipelines.cpp, tutorial/lesson_09_update_definitions.cpp, tutorial/lesson_13_tuples.cpp, and tutorial/lesson_14_types.cpp.
Definition at line 256 of file Expr.h.
Constructor & Destructor Documentation
HALIDE_ALWAYS_INLINE Halide::Expr::Expr () default
Make an undefined expression.
HALIDE_ALWAYS_INLINE Halide::Expr::Expr (const Internal::BaseExprNode * n) inline
Make an expression from a concrete expression node pointer (e.g.
Add)
Definition at line 263 of file Expr.h.
Halide::Expr::Expr (int8_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 269 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (int16_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 272 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (int32_t x) inline
Make an expression representing numeric constants of various types.
Definition at line 275 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (int64_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 278 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (uint8_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 281 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (uint16_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 284 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (uint32_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 287 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (uint64_t x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 290 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (float16_t x) inline
Make an expression representing numeric constants of various types.
Definition at line 293 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (bfloat16_t x) inline
Make an expression representing numeric constants of various types.
Definition at line 296 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (float x) inline
Make an expression representing numeric constants of various types.
Definition at line 299 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (double x) inline explicit
Make an expression representing numeric constants of various types.
Definition at line 302 of file Expr.h.
References Halide::Internal.
Halide::Expr::Expr (const std::string & s) inline
Make an expression representing a const string (i.e.
a StringImm)
Definition at line 308 of file Expr.h.
References HALIDE_ALWAYS_INLINE, and Halide::Internal.
Member Function Documentation
HALIDE_ALWAYS_INLINE const Internal::BaseExprNode* Halide::Expr::get () const inline
Override get() to return a BaseExprNode * instead of an IRNode *.
Definition at line 314 of file Expr.h.
References HALIDE_ALWAYS_INLINE.
Referenced by Halide::Internal::VariadicVisitor< Simplify, Expr, Stmt >::dispatch(), Halide::Internal::IRMatcher::SpecificExpr::match(), Halide::Internal::IRMatcher::NotOp< A >::match(), Halide::Internal::IRMatcher::SelectOp< C, T, F >::match(), Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::match(), Halide::Internal::IRMatcher::RampOp< A, B, known_lanes >::match(), Halide::Internal::IRMatcher::VectorReduceOp< A, known_lanes, reduce_op >::match(), Halide::Internal::IRMatcher::NegateOp< A >::match(), Halide::Internal::IRMatcher::CastOp< A >::match(), Halide::ExprCompare::operator()(), and Halide::Internal::IRMatcher::unwrap().
HALIDE_ALWAYS_INLINE Type Halide::Expr::type () const inline
Get the type of this expression node.
Examples:
tutorial/lesson_14_types.cpp.
Definition at line 320 of file Expr.h.
Referenced by Halide::evaluate(), Halide::evaluate_may_gpu(), Halide::ConciseCasts::f32(), Halide::ConciseCasts::f64(), Halide::ConciseCasts::i16(), Halide::ConciseCasts::i16_sat(), Halide::ConciseCasts::i32(), Halide::ConciseCasts::i32_sat(), Halide::ConciseCasts::i64(), Halide::ConciseCasts::i64_sat(), Halide::ConciseCasts::i8(), Halide::ConciseCasts::i8_sat(), Halide::Internal::Simplify::ExprInfo::intersect(), Halide::Internal::HexagonAlignmentAnalyzer::is_aligned(), Halide::Internal::HexagonAlignmentAnalyzer::is_aligned_impl(), Halide::Internal::IRMatcher::BinOp< Op, A, B >::make(), Halide::Internal::IRMatcher::CmpOp< Op, A, B >::make(), Halide::Internal::IRMatcher::RampOp< A, B, known_lanes >::make(), Halide::Internal::IRMatcher::NegateOp< A >::make(), Halide::Internal::IRMatcher::CanProve< A, Prover >::make_folded_const(), Halide::Internal::Simplify::mutate(), Halide::Param< T >::set_max_value(), Halide::Param< T >::set_min_value(), Halide::ConciseCasts::u16(), Halide::ConciseCasts::u16_sat(), Halide::ConciseCasts::u32(), Halide::ConciseCasts::u32_sat(), Halide::ConciseCasts::u64(), Halide::ConciseCasts::u64_sat(), Halide::ConciseCasts::u8(), and Halide::ConciseCasts::u8_sat().
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Expr.h