Halide: Halide::Internal::IRMatcher::SelectOp< C, T, F > Struct Template Reference
Halide::Internal::IRMatcher::SelectOp< C, T, F > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename C2 , typename T2 , typename F2 >
HALIDE_ALWAYS_INLINE bool match (const SelectOp< C2, T2, F2 > &instance, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
template<typename C1 = C>
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const noexcept
Public Attributes
C c
T t
F f
Static Public Attributes
static constexpr uint32_t binds = bindings<C>::mask | bindings<T>::mask | bindings<F>::mask
static constexpr IRNodeType min_node_type = IRNodeType::Select
static constexpr IRNodeType max_node_type = IRNodeType::Select
static constexpr bool canonical = C::canonical && T::canonical && F::canonical
static constexpr bool foldable = C::foldable && T::foldable && F::foldable
Detailed Description
template<typename C, typename T, typename F>
struct Halide::Internal::IRMatcher::SelectOp< C, T, F >
Definition at line 1454 of file IRMatch.h.
Member Function Documentation
template<typename C, typename T, typename F> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::SelectOp< C, T, F >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1468 of file IRMatch.h.
References Halide::Internal::Select::_node_type, Halide::Internal::Select::condition, Halide::Internal::Select::false_value, Halide::Expr::get(), and Halide::Internal::Select::true_value.
template<typename C, typename T, typename F> template<uint32_t bound, typename C2 , typename T2 , typename F2 > HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::SelectOp< C, T, F >::match (const SelectOp< C2, T2, F2 > & instance, MatcherState & state) const inline noexcept
Definition at line 1478 of file IRMatch.h.
References HALIDE_ALWAYS_INLINE, and Halide::Internal::IRMatcher::unwrap().
template<typename C, typename T, typename F> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::SelectOp< C, T, F >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1485 of file IRMatch.h.
References Halide::Internal::Select::make().
template<typename C, typename T, typename F> template<typename C1 = C> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::SelectOp< C, T, F >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline noexcept
Definition at line 1492 of file IRMatch.h.
References halide_type_t::lanes, Halide::Internal::IRMatcher::MatcherState::special_values_mask, halide_scalar_value_t::u, and halide_scalar_value_t::u64.
Member Data Documentation
template<typename C, typename T, typename F> C Halide::Internal::IRMatcher::SelectOp< C, T, F >::c
Definition at line 1456 of file IRMatch.h.
template<typename C, typename T, typename F> T Halide::Internal::IRMatcher::SelectOp< C, T, F >::t
Definition at line 1457 of file IRMatch.h.
template<typename C, typename T, typename F> F Halide::Internal::IRMatcher::SelectOp< C, T, F >::f
Definition at line 1458 of file IRMatch.h.
template<typename C, typename T, typename F> constexpr uint32_t Halide::Internal::IRMatcher::SelectOp< C, T, F >::binds = bindings<C>::mask | bindings<T>::mask | bindings<F>::mask static
Definition at line 1460 of file IRMatch.h.
template<typename C, typename T, typename F> constexpr IRNodeType Halide::Internal::IRMatcher::SelectOp< C, T, F >::min_node_type = IRNodeType::Select static
Definition at line 1462 of file IRMatch.h.
template<typename C, typename T, typename F> constexpr IRNodeType Halide::Internal::IRMatcher::SelectOp< C, T, F >::max_node_type = IRNodeType::Select static
Definition at line 1463 of file IRMatch.h.
template<typename C, typename T, typename F> constexpr bool Halide::Internal::IRMatcher::SelectOp< C, T, F >::canonical = C::canonical && T::canonical && F::canonical static
Definition at line 1465 of file IRMatch.h.
template<typename C, typename T, typename F> constexpr bool Halide::Internal::IRMatcher::SelectOp< C, T, F >::foldable = C::foldable && T::foldable && F::foldable static
Definition at line 1489 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/IRMatch.h