Halide: Halide::OutputImageParam::Dimension Struct Reference
Halide::OutputImageParam::Dimension Struct Reference
#include <OutputImageParam.h>
Public Member Functions
EXPORT Expr min () const
Get an expression representing the minimum coordinates of this image parameter in the given dimension.
EXPORT Expr extent () const
Get an expression representing the extent of this image parameter in the given dimension.
EXPORT Expr max () const
Get an expression representing the maximum coordinates of this image parameter in the given dimension.
EXPORT Expr stride () const
Get an expression representing the stride of this image in the given dimension.
EXPORT Dimension set_min (Expr e)
Set the min in a given dimension to equal the given expression.
EXPORT Dimension set_extent (Expr e)
Set the extent in a given dimension to equal the given expression.
EXPORT Dimension set_stride (Expr e)
Set the stride in a given dimension to equal the given value.
EXPORT Dimension set_bounds (Expr min, Expr extent)
Set the min and extent in one call.
EXPORT Dimension dim (int i)
Get a different dimension of the same buffer.
EXPORT const Dimension dim (int i) const
Get a different dimension of the same buffer.
Detailed Description
Definition at line 30 of file OutputImageParam.h.
Member Function Documentation
EXPORT Expr Halide::OutputImageParam::Dimension::min () const
Get an expression representing the minimum coordinates of this image parameter in the given dimension.
Referenced by Halide::OutputImageParam::min().
EXPORT Expr Halide::OutputImageParam::Dimension::extent () const
Get an expression representing the extent of this image parameter in the given dimension.
Referenced by Halide::OutputImageParam::extent().
EXPORT Expr Halide::OutputImageParam::Dimension::max () const
Get an expression representing the maximum coordinates of this image parameter in the given dimension.
EXPORT Expr Halide::OutputImageParam::Dimension::stride () const
Get an expression representing the stride of this image in the given dimension.
Referenced by Halide::OutputImageParam::stride().
EXPORT Dimension Halide::OutputImageParam::Dimension::set_min (Expr e)
Set the min in a given dimension to equal the given expression.
Setting the mins to zero may simplify some addressing math.
Referenced by Halide::OutputImageParam::set_min().
EXPORT Dimension Halide::OutputImageParam::Dimension::set_extent (Expr e)
Set the extent in a given dimension to equal the given expression.
Images passed in that fail this check will generate a runtime error. Returns a reference to the ImageParam so that these calls may be chained.
This may help the compiler generate better code. E.g:
im.dim(0).set_extent(100);
tells the compiler that dimension zero must be of extent 100, which may result in simplification of boundary checks. The value can be an arbitrary expression:
im.dim(0).set_extent(im.dim(1).extent());
declares that im is a square image (of unknown size), whereas:
im.dim(0).set_extent((im.dim(0).extent()/32)*32);
tells the compiler that the extent is a multiple of 32.
Referenced by Halide::OutputImageParam::set_extent().
EXPORT Dimension Halide::OutputImageParam::Dimension::set_stride (Expr e)
Set the stride in a given dimension to equal the given value.
This is particularly helpful to set when vectorizing. Known strides for the vectorized dimension generate better code.
Referenced by Halide::OutputImageParam::set_stride().
EXPORT Dimension Halide::OutputImageParam::Dimension::set_bounds (Expr min, Expr extent)
Set the min and extent in one call.
Referenced by Halide::OutputImageParam::set_bounds().
EXPORT Dimension Halide::OutputImageParam::Dimension::dim (int i)
Get a different dimension of the same buffer.
EXPORT const Dimension Halide::OutputImageParam::Dimension::dim (int i) const
Get a different dimension of the same buffer.
The documentation for this struct was generated from the following file:
OutputImageParam.h