Halide: Halide::Internal::ScopedBinding< T > Struct Template Reference
Halide::Internal::ScopedBinding< T > Struct Template Reference
Helper class for pushing/popping Scope<> values, to allow for early-exit in Visitor/Mutators that preserves correctness.
#include <Scope.h>
Public Member Functions
ScopedBinding ()=default
ScopedBinding (Scope< T > &s, const std::string &n, T value)
ScopedBinding (bool condition, Scope< T > &s, const std::string &n, const T &value)
bool bound () const
~ScopedBinding ()
ScopedBinding (const ScopedBinding &that)=delete
ScopedBinding (ScopedBinding &&that) noexcept
void operator= (const ScopedBinding &that)=delete
void operator= (ScopedBinding &&that)=delete
Public Attributes
Scope< T > * scope = nullptr
std::string name
Detailed Description
template<typename T = void>
struct Halide::Internal::ScopedBinding< T >
Helper class for pushing/popping Scope<> values, to allow for early-exit in Visitor/Mutators that preserves correctness.
Note that this name can be a bit confusing, since there are two "scopes" involved here:
the Scope object itself
the lifetime of this helper object The "Scoped" in this class name refers to the latter, as it temporarily binds a name within the scope of this helper's lifetime.
Definition at line 273 of file Scope.h.
Constructor & Destructor Documentation
template<typename T = void> Halide::Internal::ScopedBinding< T >::ScopedBinding () default
template<typename T = void> Halide::Internal::ScopedBinding< T >::ScopedBinding (Scope< T > & s, const std::string & n, T value) inline
Definition at line 279 of file Scope.h.
References Halide::Internal::Scope< T >::push().
template<typename T = void> Halide::Internal::ScopedBinding< T >::ScopedBinding (bool condition, Scope< T > & s, const std::string & n, const T & value) inline
Definition at line 284 of file Scope.h.
References Halide::Internal::Scope< T >::push().
template<typename T = void> Halide::Internal::ScopedBinding< T >::~ScopedBinding () inline
Definition at line 295 of file Scope.h.
References Halide::Internal::Scope< T >::pop().
template<typename T = void> Halide::Internal::ScopedBinding< T >::ScopedBinding (const ScopedBinding< T > & that) delete
template<typename T = void> Halide::Internal::ScopedBinding< T >::ScopedBinding (ScopedBinding< T > && that) inline noexcept
Definition at line 303 of file Scope.h.
References Halide::Internal::ScopedBinding< T >::scope.
Member Function Documentation
template<typename T = void> bool Halide::Internal::ScopedBinding< T >::bound () const inline
Definition at line 291 of file Scope.h.
template<typename T = void> void Halide::Internal::ScopedBinding< T >::operator= (const ScopedBinding< T > & that) delete
template<typename T = void> void Halide::Internal::ScopedBinding< T >::operator= (ScopedBinding< T > && that) delete
Member Data Documentation
template<typename T = void> Scope<T>* Halide::Internal::ScopedBinding< T >::scope = nullptr
Definition at line 274 of file Scope.h.
Referenced by Halide::Internal::ScopedBinding< T >::ScopedBinding(), and Halide::Internal::ScopedBinding< void >::ScopedBinding().
template<typename T = void> std::string Halide::Internal::ScopedBinding< T >::name
Definition at line 275 of file Scope.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/Scope.h