Halide: elf_t Struct Reference
elf_t Struct Reference
#include <elf.h>
Public Member Functions
void parse_object_file (const unsigned char *b, size_t s, bool d=false)
void fail (int line)
void move_writeable_sections ()
void deinit ()
char * get_addr (elfaddr_t off)
int num_sections ()
section_header_t * get_section (int i)
char * get_section_start (section_header_t *sec)
elfaddr_t get_section_offset (section_header_t *sec)
int get_section_size (section_header_t *sec)
bool is_section_writeable (section_header_t *sec)
const char * get_section_name (section_header_t *sec)
section_header_t * find_section (const char *name)
int num_symbols ()
symbol_t * get_symbol (int i)
const char * get_symbol_name (symbol_t *sym)
section_header_t * get_symbol_section (symbol_t *sym)
bool symbol_is_defined (symbol_t *sym)
char * get_symbol_addr (symbol_t *sym)
symbol_t * find_symbol (const char *name)
int num_relas (section_header_t *sec_rela)
rela_t * get_rela (section_header_t *sec_rela, int i)
void do_reloc (char *addr, uint32_t mask, uintptr_t val, bool is_signed, bool verify)
void do_relocations_for_section (section_header_t *sec, section_header_t *sec_rela)
void do_relocations ()
void make_executable ()
void dump_as_base64 ()
Public Attributes
char * buf
size_t size
bool debug
int failed
elf_header_t * header
section_header_t * sec_symtab
section_header_t * sec_secnames
section_header_t * sec_text
section_header_t * sec_strtab
char * writeable_buf
size_t writeable_size
elfaddr_t * global_offset_table
int global_offset_table_entries
int max_global_offset_table_entries
Detailed Description
Definition at line 99 of file elf.h.
Member Function Documentation
void elf_t::parse_object_file (const unsigned char * b, size_t s, bool d = false) inline
Definition at line 131 of file elf.h.
References buf, debug, elf_header_t::e_shstrndx, fail(), failed, get_addr(), get_section(), get_section_name(), get_section_offset(), global_offset_table, global_offset_table_entries, header, log_printf(), max_global_offset_table_entries, memcpy(), memset(), NULL, num_sections(), sec_secnames, sec_strtab, sec_symtab, sec_text, section_header_t::sh_type, size, strncmp(), writeable_buf, and writeable_size.
Referenced by obj_dlopen_mem().
void elf_t::fail (int line) inline
Definition at line 190 of file elf.h.
References failed, and log_printf().
Referenced by do_reloc(), do_relocations(), do_relocations_for_section(), get_addr(), get_rela(), get_section(), get_section_name(), get_symbol(), get_symbol_name(), make_executable(), move_writeable_sections(), num_relas(), num_symbols(), and parse_object_file().
void elf_t::move_writeable_sections () inline
Definition at line 195 of file elf.h.
References buf, debug, end, fail(), failed, get_section(), get_section_name(), get_section_size(), get_section_start(), is_section_writeable(), log_printf(), memcpy(), NULL, num_sections(), section_header_t::sh_offset, size, writeable_buf, and writeable_size.
Referenced by obj_dlopen_mem().
void elf_t::deinit () inline
Definition at line 263 of file elf.h.
References buf, and size.
Referenced by obj_dlclose().
char* elf_t::get_addr (elfaddr_t off) inline
Definition at line 269 of file elf.h.
References buf, fail(), log_printf(), NULL, size, writeable_buf, and writeable_size.
Referenced by do_reloc(), do_relocations_for_section(), get_rela(), get_section(), get_section_name(), get_section_start(), get_symbol(), get_symbol_addr(), get_symbol_name(), and parse_object_file().
int elf_t::num_sections () inline
Definition at line 282 of file elf.h.
References elf_header_t::e_shnum, and header.
Referenced by do_relocations(), find_section(), move_writeable_sections(), and parse_object_file().
section_header_t* elf_t::get_section (int i) inline
Definition at line 287 of file elf.h.
References elf_header_t::e_shentsize, elf_header_t::e_shoff, fail(), get_addr(), header, NULL, and size.
Referenced by do_relocations(), find_section(), get_symbol_section(), move_writeable_sections(), and parse_object_file().
char* elf_t::get_section_start (section_header_t * sec) inline
Definition at line 301 of file elf.h.
References get_addr(), and section_header_t::sh_offset.
Referenced by move_writeable_sections().
elfaddr_t elf_t::get_section_offset (section_header_t * sec) inline
Definition at line 306 of file elf.h.
References section_header_t::sh_offset.
Referenced by do_reloc(), do_relocations_for_section(), get_rela(), get_section_name(), get_symbol(), get_symbol_addr(), get_symbol_name(), and parse_object_file().
int elf_t::get_section_size (section_header_t * sec) inline
Definition at line 311 of file elf.h.
References section_header_t::sh_size.
Referenced by move_writeable_sections(), num_relas(), and num_symbols().
bool elf_t::is_section_writeable (section_header_t * sec) inline
Definition at line 315 of file elf.h.
References section_header_t::sh_flags.
Referenced by move_writeable_sections().
const char* elf_t::get_section_name (section_header_t * sec) inline
Definition at line 322 of file elf.h.
References fail(), get_addr(), get_section_offset(), NULL, sec_secnames, and section_header_t::sh_name.
Referenced by do_relocations(), do_relocations_for_section(), find_section(), move_writeable_sections(), and parse_object_file().
section_header_t* elf_t::find_section (const char * name) inline
Definition at line 331 of file elf.h.
References get_section(), get_section_name(), NULL, num_sections(), strlen(), and strncmp().
Referenced by do_relocations().
int elf_t::num_symbols () inline
Definition at line 343 of file elf.h.
References fail(), get_section_size(), and sec_symtab.
Referenced by find_symbol().
symbol_t* elf_t::get_symbol (int i) inline
Definition at line 352 of file elf.h.
References fail(), get_addr(), get_section_offset(), and sec_symtab.
Referenced by do_relocations_for_section(), and find_symbol().
const char* elf_t::get_symbol_name (symbol_t * sym) inline
Definition at line 361 of file elf.h.
References fail(), get_addr(), get_section_offset(), NULL, sec_strtab, and symbol_t::st_name.
Referenced by do_relocations_for_section(), and find_symbol().
section_header_t* elf_t::get_symbol_section (symbol_t * sym) inline
Definition at line 370 of file elf.h.
References get_section(), NULL, and symbol_t::st_shndx.
Referenced by do_relocations_for_section(), get_symbol_addr(), and symbol_is_defined().
bool elf_t::symbol_is_defined (symbol_t * sym) inline
Definition at line 376 of file elf.h.
References get_symbol_section(), and NULL.
Referenced by do_relocations_for_section(), and obj_dlsym().
char* elf_t::get_symbol_addr (symbol_t * sym) inline
Definition at line 381 of file elf.h.
References get_addr(), get_section_offset(), get_symbol_section(), and symbol_t::st_value.
Referenced by do_relocations_for_section(), and obj_dlsym().
symbol_t* elf_t::find_symbol (const char * name) inline
Definition at line 386 of file elf.h.
References debug, get_symbol(), get_symbol_name(), log_printf(), NULL, num_symbols(), strlen(), and strncmp().
Referenced by obj_dlsym().
int elf_t::num_relas (section_header_t * sec_rela) inline
Definition at line 404 of file elf.h.
References fail(), and get_section_size().
Referenced by do_relocations_for_section().
rela_t* elf_t::get_rela (section_header_t * sec_rela, int i) inline
Definition at line 413 of file elf.h.
References fail(), get_addr(), get_section_offset(), and NULL.
Referenced by do_relocations_for_section().
void elf_t::do_reloc (char * addr, uint32_t mask, uintptr_t val, bool is_signed, bool verify) inline
Definition at line 421 of file elf.h.
References debug, fail(), get_addr(), get_section_offset(), log_printf(), and sec_text.
Referenced by do_relocations_for_section().
void elf_t::do_relocations_for_section (section_header_t * sec, section_header_t * sec_rela) inline
Definition at line 562 of file elf.h.
References debug, do_reloc(), fail(), get_addr(), get_rela(), get_section_name(), get_section_offset(), get_symbol(), get_symbol_addr(), get_symbol_name(), get_symbol_section(), global_offset_table, global_offset_table_entries, halide_get_symbol(), log_printf(), max_global_offset_table_entries, NULL, num_relas(), rela_t::r_addend, rela_t::r_offset, rela_t::r_sym(), rela_t::r_type(), strncmp(), and symbol_is_defined().
Referenced by do_relocations().
void elf_t::do_relocations () inline
Definition at line 787 of file elf.h.
References debug, do_relocations_for_section(), fail(), failed, find_section(), get_section(), get_section_name(), global_offset_table, global_offset_table_entries, log_printf(), num_sections(), and strncmp().
Referenced by obj_dlopen_mem().
void elf_t::make_executable () inline
Definition at line 815 of file elf.h.
References buf, fail(), log_printf(), and size.
Referenced by obj_dlopen_mem().
void elf_t::dump_as_base64 () inline
Definition at line 826 of file elf.h.
References Halide::Runtime::Internal::a, Halide::Runtime::Internal::b, buf, log_printf(), and size.
Member Data Documentation
char* elf_t::buf
Definition at line 101 of file elf.h.
Referenced by deinit(), dump_as_base64(), get_addr(), make_executable(), move_writeable_sections(), and parse_object_file().
size_t elf_t::size
Definition at line 102 of file elf.h.
Referenced by deinit(), dump_as_base64(), get_addr(), get_section(), make_executable(), move_writeable_sections(), and parse_object_file().
bool elf_t::debug
Definition at line 105 of file elf.h.
Referenced by do_reloc(), do_relocations(), do_relocations_for_section(), find_symbol(), move_writeable_sections(), and parse_object_file().
int elf_t::failed
Definition at line 108 of file elf.h.
Referenced by do_relocations(), fail(), move_writeable_sections(), and parse_object_file().
elf_header_t* elf_t::header
Definition at line 111 of file elf.h.
Referenced by get_section(), num_sections(), and parse_object_file().
section_header_t* elf_t::sec_symtab
Definition at line 115 of file elf.h.
Referenced by get_symbol(), num_symbols(), and parse_object_file().
section_header_t * elf_t::sec_secnames
Definition at line 115 of file elf.h.
Referenced by get_section_name(), and parse_object_file().
section_header_t * elf_t::sec_text
Definition at line 115 of file elf.h.
Referenced by do_reloc(), and parse_object_file().
section_header_t * elf_t::sec_strtab
Definition at line 115 of file elf.h.
Referenced by get_symbol_name(), and parse_object_file().
char* elf_t::writeable_buf
Definition at line 121 of file elf.h.
Referenced by get_addr(), move_writeable_sections(), and parse_object_file().
size_t elf_t::writeable_size
Definition at line 122 of file elf.h.
Referenced by get_addr(), move_writeable_sections(), and parse_object_file().
elfaddr_t* elf_t::global_offset_table
Definition at line 125 of file elf.h.
Referenced by do_relocations(), do_relocations_for_section(), and parse_object_file().
int elf_t::global_offset_table_entries
Definition at line 126 of file elf.h.
Referenced by do_relocations(), do_relocations_for_section(), and parse_object_file().
int elf_t::max_global_offset_table_entries
Definition at line 127 of file elf.h.
Referenced by do_relocations_for_section(), and parse_object_file().
The documentation for this struct was generated from the following file:
elf.h