Halide: Halide::Convert< FROM, TO > Struct Template Reference
Halide::Convert< FROM, TO > Struct Template Reference
#include <ScheduleParam.h>
Static Public Member Functions
template<typename TO2 = TO, typename std::enable_if<!std::is_same< TO2, bool >::value >::type * = nullptr>
static TO2 value (const FROM &from)
template<typename TO2 = TO, typename std::enable_if< std::is_same< TO2, bool >::value >::type * = nullptr>
static TO2 value (const FROM &from)
Detailed Description
template<typename FROM, typename TO>
struct Halide::Convert< FROM, TO >
Definition at line 92 of file ScheduleParam.h.
Member Function Documentation
value() [1/2]
template<typename FROM , typename TO > template<typename TO2 = TO, typename std::enable_if<!std::is_same< TO2, bool >::value >::type * = nullptr> static TO2 Halide::Convert< FROM, TO >::value (const FROM & from) inline static
Definition at line 94 of file ScheduleParam.h.
Referenced by Halide::Internal::GeneratorParamImpl< T >::set_impl(), and Halide::Convert< FROM, TO >::value().
value() [2/2]
template<typename FROM , typename TO > template<typename TO2 = TO, typename std::enable_if< std::is_same< TO2, bool >::value >::type * = nullptr> static TO2 Halide::Convert< FROM, TO >::value (const FROM & from) inline static
Definition at line 97 of file ScheduleParam.h.
References HALIDE_ALWAYS_INLINE, Halide::Handle(), Halide::LoopLevel::inlined(), Halide::Internal::ScheduleParamBase::is_looplevel_param(), Halide::Internal::ScheduleParamBase::loop_level, Halide::Internal::ScheduleParamBase::name(), NO_INLINE, Halide::LoopLevel::root(), Halide::Internal::ScheduleParamBase::scalar_parameter, Halide::Internal::ScheduleParamBase::ScheduleParamBase(), Halide::Internal::Parameter::set_scalar(), Halide::Internal::ScheduleParamBase::type, user_assert, user_error, and Halide::Convert< FROM, TO >::value().
The documentation for this struct was generated from the following file:
ScheduleParam.h