Halide: Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes > Struct Template Reference
Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes > Struct Template Reference
#include <IRMatch.h>
Classes
struct pattern_tag
Public Member Functions
template<uint32_t bound>
HALIDE_ALWAYS_INLINE bool match (const BaseExprNode &e, MatcherState &state) const noexcept
template<uint32_t bound, typename A2 , bool known_lanes_2>
HALIDE_ALWAYS_INLINE bool match (const BroadcastOp< A2, known_lanes_2 > &op, MatcherState &state) const noexcept
HALIDE_ALWAYS_INLINE Expr make (MatcherState &state, halide_type_t type_hint) const
template<typename A1 = A>
HALIDE_ALWAYS_INLINE void make_folded_const (halide_scalar_value_t &val, halide_type_t &ty, MatcherState &state) const noexcept
Public Attributes
A a
int lanes
Static Public Attributes
static constexpr uint32_t binds = bindings<A>::mask
static constexpr IRNodeType min_node_type = IRNodeType::Broadcast
static constexpr IRNodeType max_node_type = IRNodeType::Broadcast
static constexpr bool canonical = A::canonical
static constexpr bool foldable = false
Detailed Description
template<typename A, bool known_lanes>
struct Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >
Definition at line 1517 of file IRMatch.h.
Member Function Documentation
template<typename A, bool known_lanes> template<uint32_t bound> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::match (const BaseExprNode & e, MatcherState & state) const inline noexcept
Definition at line 1530 of file IRMatch.h.
References Halide::Internal::Broadcast::_node_type, Halide::Expr::get(), Halide::Internal::Broadcast::lanes, and Halide::Internal::Broadcast::value.
template<typename A, bool known_lanes> template<uint32_t bound, typename A2 , bool known_lanes_2> HALIDE_ALWAYS_INLINE bool Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::match (const BroadcastOp< A2, known_lanes_2 > & op, MatcherState & state) const inline noexcept
Definition at line 1542 of file IRMatch.h.
References HALIDE_ALWAYS_INLINE, and Halide::Internal::IRMatcher::unwrap().
template<typename A, bool known_lanes> HALIDE_ALWAYS_INLINE Expr Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::make (MatcherState & state, halide_type_t type_hint) const inline
Definition at line 1548 of file IRMatch.h.
References halide_type_t::lanes, and Halide::Internal::Broadcast::make().
template<typename A, bool known_lanes> template<typename A1 = A> HALIDE_ALWAYS_INLINE void Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::make_folded_const (halide_scalar_value_t & val, halide_type_t & ty, MatcherState & state) const inline noexcept
Definition at line 1562 of file IRMatch.h.
References Halide::Internal::IRMatcher::MatcherState::special_values_mask.
Member Data Documentation
template<typename A, bool known_lanes> A Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::a
Definition at line 1519 of file IRMatch.h.
template<typename A, bool known_lanes> int Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::lanes
Definition at line 1520 of file IRMatch.h.
template<typename A, bool known_lanes> constexpr uint32_t Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::binds = bindings<A>::mask static
Definition at line 1522 of file IRMatch.h.
template<typename A, bool known_lanes> constexpr IRNodeType Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::min_node_type = IRNodeType::Broadcast static
Definition at line 1524 of file IRMatch.h.
template<typename A, bool known_lanes> constexpr IRNodeType Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::max_node_type = IRNodeType::Broadcast static
Definition at line 1525 of file IRMatch.h.
template<typename A, bool known_lanes> constexpr bool Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::canonical = A::canonical static
Definition at line 1527 of file IRMatch.h.
template<typename A, bool known_lanes> constexpr bool Halide::Internal::IRMatcher::BroadcastOp< A, known_lanes >::foldable = false static
Definition at line 1559 of file IRMatch.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/IRMatch.h