Halide: Halide::Internal::GT Struct Reference
Halide::Internal::GT Struct Reference
Is the first expression greater than the second.
#include <IR.h>
Inherits Halide::Internal::ExprNode< GT >.
Static Public Member Functions
static Expr make (Expr a, Expr b)
Public Attributes
Expr a
Expr b
Detailed Description
Is the first expression greater than the second.
Definition at line 440 of file IR.h.
Member Function Documentation
static Expr Halide::Internal::GT::make (Expr a, Expr b) [inline, static]
Definition at line 443 of file IR.h.
References a, b, Halide::Bool(), Halide::Internal::IntrusivePtr< T >::defined(), Halide::Internal::BaseExprNode::type, Halide::Expr::type(), and Halide::Type::width.
Referenced by Halide::operator>().
Member Data Documentation
Expr Halide::Internal::GT::a
Definition at line 441 of file IR.h.
Referenced by make().
Expr Halide::Internal::GT::b
Definition at line 441 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h