Halide: Halide::Internal::For Struct Reference
Halide::Internal::For Struct Reference
A for loop.
#include <IR.h>
Inherits Halide::Internal::StmtNode< For >.
Public Types
enum ForType { Serial, Parallel, Vectorized, Unrolled }
Static Public Member Functions
static Stmt make (std::string name, Expr min, Expr extent, ForType for_type, Stmt body)
Public Attributes
std::string name
Expr min
Expr extent
ForType for_type
Stmt body
Detailed Description
A for loop.
Execute the 'body' statement for all values of the variable 'name' from 'min' to 'min + extent'. There are four types of For nodes. A 'Serial' for loop is a conventional one. In a 'Parallel' for loop, each iteration of the loop happens in parallel or in some unspecified order. In a 'Vectorized' for loop, each iteration maps to one SIMD lane, and the whole loop is executed in one shot. For this case, 'extent' must be some small integer constant (probably 4, 8, or 16). An 'Unrolled' for loop compiles to a completely unrolled version of the loop. Each iteration becomes its own statement. Again in this case, 'extent' should be a small integer constant.
Definition at line 735 of file IR.h.
Member Enumeration Documentation
enum Halide::Internal::For::ForType
Enumerator:
Serial
Parallel
Vectorized
Unrolled
Definition at line 738 of file IR.h.
Member Function Documentation
static Stmt Halide::Internal::For::make (std::string name, Expr min, Expr extent, ForType for_type, Stmt body) [inline, static]
Definition at line 742 of file IR.h.
References body, Halide::Internal::IntrusivePtr< T >::defined(), extent, for_type, internal_assert, Halide::Type::is_scalar(), min, name, and Halide::Expr::type().
Member Data Documentation
std::string Halide::Internal::For::name
Definition at line 736 of file IR.h.
Referenced by make().
Expr Halide::Internal::For::min
Definition at line 737 of file IR.h.
Referenced by make().
Expr Halide::Internal::For::extent
Definition at line 737 of file IR.h.
Referenced by make().
ForType Halide::Internal::For::for_type
Definition at line 739 of file IR.h.
Referenced by make().
Stmt Halide::Internal::For::body
Definition at line 740 of file IR.h.
Referenced by make().
The documentation for this struct was generated from the following file:
IR.h