Halide: Halide::Internal::IntrusivePtr< T > Struct Template Reference
Halide::Internal::IntrusivePtr< T > Struct Template Reference
Intrusive shared pointers have a reference count (a RefCount object) stored in the class itself.
#include <IntrusivePtr.h>
Public Member Functions
~IntrusivePtr ()
IntrusivePtr ()
IntrusivePtr (T *p)
IntrusivePtr (const IntrusivePtr< T > &other)
IntrusivePtr< T > & operator= (const IntrusivePtr< T > &other)
bool defined () const
bool same_as (const IntrusivePtr &other) const
Public Attributes
T * ptr
Detailed Description
template<typename T>
struct Halide::Internal::IntrusivePtr< T >
Intrusive shared pointers have a reference count (a RefCount object) stored in the class itself.
This is perhaps more efficient than storing it externally, but more importantly, it means it's possible to recover a reference-counted handle from the raw pointer, and it's impossible to have two different reference counts attached to the same raw object. Seeing as we pass around raw pointers to concrete IRNodes and Expr's interchangeably, this is a useful property.
Definition at line 56 of file IntrusivePtr.h.
Constructor & Destructor Documentation
template<typename T> Halide::Internal::IntrusivePtr< T >::~IntrusivePtr () [inline]
Definition at line 78 of file IntrusivePtr.h.
template<typename T> Halide::Internal::IntrusivePtr< T >::IntrusivePtr () [inline]
Definition at line 82 of file IntrusivePtr.h.
template<typename T> Halide::Internal::IntrusivePtr< T >::IntrusivePtr (T * p) [inline]
Definition at line 85 of file IntrusivePtr.h.
template<typename T> Halide::Internal::IntrusivePtr< T >::IntrusivePtr (const IntrusivePtr< T > & other) [inline]
Definition at line 89 of file IntrusivePtr.h.
Member Function Documentation
template<typename T> IntrusivePtr<T>& Halide::Internal::IntrusivePtr< T >::operator= (const IntrusivePtr< T > & other) [inline]
Definition at line 93 of file IntrusivePtr.h.
template<typename T> bool Halide::Internal::IntrusivePtr< T >::defined () const [inline]
Definition at line 105 of file IntrusivePtr.h.
Referenced by Halide::abs(), Halide::acos(), Halide::acosh(), Halide::asin(), Halide::asinh(), Halide::atan(), Halide::atan2(), Halide::atanh(), Halide::cast(), Halide::ceil(), Halide::clamp(), Halide::cos(), Halide::cosh(), Halide::count_leading_zeros(), Halide::count_trailing_zeros(), Halide::Internal::ReductionDomain::defined(), Halide::Internal::Parameter::defined(), Halide::Buffer::defined(), Halide::exp(), Halide::Internal::Parameter::extent_constraint(), Halide::floor(), Halide::Internal::Parameter::get_buffer(), Halide::Internal::Parameter::get_max_value(), Halide::Internal::Parameter::get_min_value(), Halide::Internal::Parameter::get_scalar(), Halide::Internal::Parameter::get_scalar_address(), Halide::Internal::Parameter::is_buffer(), Halide::lerp(), Halide::log(), Halide::Internal::Cast::make(), Halide::Internal::Add::make(), Halide::Internal::Sub::make(), Halide::Internal::Mul::make(), Halide::Internal::Div::make(), Halide::Internal::Mod::make(), Halide::Internal::Min::make(), Halide::Internal::Max::make(), Halide::Internal::EQ::make(), Halide::Internal::NE::make(), Halide::Internal::LT::make(), Halide::Internal::LE::make(), Halide::Internal::GT::make(), Halide::Internal::GE::make(), Halide::Internal::And::make(), Halide::Internal::Or::make(), Halide::Internal::Not::make(), Halide::Internal::Select::make(), Halide::Internal::Load::make(), Halide::Internal::Ramp::make(), Halide::Internal::Broadcast::make(), Halide::Internal::Let::make(), Halide::Internal::LetStmt::make(), Halide::Internal::AssertStmt::make(), Halide::Internal::Pipeline::make(), Halide::Internal::For::make(), Halide::Internal::Store::make(), Halide::Internal::Allocate::make(), Halide::Internal::Realize::make(), Halide::Internal::Block::make(), Halide::Internal::IfThenElse::make(), Halide::Internal::Evaluate::make(), Halide::max(), Halide::min(), Halide::Internal::Parameter::min_constraint(), Halide::Internal::Parameter::name(), Halide::operator!=(), Halide::operator%(), Halide::operator&(), Halide::operator*(), Halide::operator*=(), Halide::operator+(), Halide::operator+=(), Halide::operator-(), Halide::operator-=(), Halide::operator/(), Halide::operator/=(), Halide::operator<(), Halide::operator<<(), Halide::operator<=(), Halide::operator==(), Halide::operator>(), Halide::operator>=(), Halide::operator>>(), Halide::operator^(), Halide::operator|(), Halide::operator~(), Halide::popcount(), Halide::pow(), Halide::reinterpret(), Halide::round(), Halide::Internal::Parameter::set_buffer(), Halide::Internal::Parameter::set_extent_constraint(), Halide::Internal::Parameter::set_max_value(), Halide::Internal::Parameter::set_min_constraint(), Halide::Internal::Parameter::set_min_value(), Halide::Internal::Parameter::set_scalar(), Halide::Internal::Parameter::set_stride_constraint(), Halide::sin(), Halide::sinh(), Halide::sqrt(), Halide::Internal::Parameter::stride_constraint(), Halide::tan(), Halide::tanh(), and Halide::Internal::Parameter::type().
template<typename T> bool Halide::Internal::IntrusivePtr< T >::same_as (const IntrusivePtr< T > & other) const [inline]
Definition at line 111 of file IntrusivePtr.h.
Referenced by Halide::Internal::ReductionDomain::same_as(), Halide::Internal::Function::same_as(), and Halide::Buffer::same_as().
Member Data Documentation
template<typename T> T* Halide::Internal::IntrusivePtr< T >::ptr
Definition at line 76 of file IntrusivePtr.h.
Referenced by Halide::Internal::Function::args(), Halide::Buffer::copy_to_dev(), Halide::Buffer::copy_to_host(), Halide::Internal::Function::debug_file(), Halide::Internal::IntrusivePtr< JITModuleHolder >::defined(), Halide::Buffer::device_dirty(), Halide::Buffer::device_handle(), Halide::Internal::ReductionDomain::domain(), Halide::Buffer::extent(), Halide::Internal::Parameter::extent_constraint(), Halide::Internal::Function::extern_arguments(), Halide::Internal::Function::extern_function_name(), Halide::Buffer::free_dev_buffer(), Halide::Internal::Function::Function(), Halide::Internal::Parameter::get_buffer(), Halide::Internal::Parameter::get_max_value(), Halide::Internal::Parameter::get_min_value(), Halide::Internal::Parameter::get_scalar(), Halide::Internal::Parameter::get_scalar_address(), Halide::Internal::Function::has_extern_definition(), Halide::Internal::Function::has_pure_definition(), Halide::Internal::Function::has_reduction_definition(), Halide::Buffer::host_dirty(), Halide::Buffer::host_ptr(), Halide::Internal::IntrusivePtr< JITModuleHolder >::IntrusivePtr(), Halide::Internal::Parameter::is_buffer(), Halide::Internal::Function::is_tracing_loads(), Halide::Internal::Function::is_tracing_realizations(), Halide::Internal::Function::is_tracing_stores(), Halide::Buffer::min(), Halide::Internal::Parameter::min_constraint(), Halide::Internal::Parameter::name(), Halide::Internal::Function::name(), Halide::Buffer::name(), Halide::ExprCompare::operator()(), Halide::Internal::Stmt::Compare::operator()(), Halide::Internal::IntrusivePtr< JITModuleHolder >::operator=(), Halide::Internal::Function::output_buffers(), Halide::Internal::Function::output_types(), Halide::Buffer::raw_buffer(), Halide::Internal::Function::reduction_schedule(), Halide::Internal::ReductionDomain::ReductionDomain(), Halide::Internal::Function::reductions(), Halide::Internal::IntrusivePtr< JITModuleHolder >::same_as(), Halide::Internal::Parameter::same_as(), Halide::Internal::Function::schedule(), Halide::Internal::Parameter::set_buffer(), Halide::Buffer::set_device_dirty(), Halide::Internal::Parameter::set_extent_constraint(), Halide::Buffer::set_host_dirty(), Halide::Internal::Parameter::set_max_value(), Halide::Buffer::set_min(), Halide::Internal::Parameter::set_min_constraint(), Halide::Internal::Parameter::set_min_value(), Halide::Internal::Parameter::set_scalar(), Halide::Buffer::set_source_module(), Halide::Internal::Parameter::set_stride_constraint(), Halide::Buffer::source_module(), Halide::Buffer::stride(), Halide::Internal::Parameter::stride_constraint(), Halide::Internal::Function::trace_loads(), Halide::Internal::Function::trace_realizations(), Halide::Internal::Function::trace_stores(), Halide::Internal::Parameter::type(), Halide::Buffer::type(), Halide::Internal::Function::values(), and Halide::Internal::IntrusivePtr< JITModuleHolder >::~IntrusivePtr().
The documentation for this struct was generated from the following file:
IntrusivePtr.h