Halide: Halide::Internal::Cost Struct Reference
Halide::Internal::Cost Struct Reference
#include <RegionCosts.h>
Public Member Functions
Cost (int64_t arith, int64_t memory)
Cost (Expr arith, Expr memory)
Cost ()=default
bool defined () const
void simplify ()
Public Attributes
Expr arith
Expr memory
Friends
std::ostream & operator<< (std::ostream &stream, const Cost &c)
Detailed Description
Definition at line 20 of file RegionCosts.h.
Constructor & Destructor Documentation
Halide::Internal::Cost::Cost (int64_t arith, int64_t memory) inline
Definition at line 26 of file RegionCosts.h.
Halide::Internal::Cost::Cost (Expr arith, Expr memory) inline
Definition at line 29 of file RegionCosts.h.
References Cost().
Halide::Internal::Cost::Cost () default
Referenced by Cost().
Member Function Documentation
bool Halide::Internal::Cost::defined () const inline
Definition at line 34 of file RegionCosts.h.
References Halide::Internal::IntrusivePtr< T >::defined(), and simplify().
void Halide::Internal::Cost::simplify ()
Referenced by defined().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & stream, const Cost & c) friend
Definition at line 39 of file RegionCosts.h.
Member Data Documentation
Expr Halide::Internal::Cost::arith
Definition at line 22 of file RegionCosts.h.
Expr Halide::Internal::Cost::memory
Definition at line 24 of file RegionCosts.h.
The documentation for this struct was generated from the following file:
/home/halidenightly/build_bot/worker/x86-64-linux-1000-cmake/halide/src/RegionCosts.h