Halide: Halide::Internal::JITCompiledModule Struct Reference
Halide::Internal::JITCompiledModule Struct Reference
Function pointers into a compiled halide module.
#include <JITCompiledModule.h>
Public Types
typedef void(* ErrorHandler)(const char *)
The type of a halide runtime error handler function.
typedef int(* HalideTask)(int, uint8_t *)
Set a custom parallel for loop launcher.
typedef void(* TraceFn)(const char *, int, int, int, int, int, const void *, int, const int *)
Set a custom trace function.
Public Member Functions
JITCompiledModule ()
void compile_module (CodeGen *cg, llvm::Module *mod, const std::string &function_name)
Take an llvm module and compile it.
Public Attributes
void * function
A pointer to the raw halide function.
int(* wrapped_function)(const void **)
A slightly more type-safe wrapper around the raw halide module.
void(* set_error_handler)(ErrorHandler)
Set the runtime error handler for this module.
void(* set_custom_allocator)(void *(*malloc)(size_t), void(*free)(void *))
Set a custom malloc and free for this module to use.
void(* set_custom_do_par_for)(int(*custom_do_par_for)(HalideTask, int, int, uint8_t *))
void(* set_custom_do_task)(int(*custom_do_task)(HalideTask, int, uint8_t *))
Set a custom do parallel task.
void(* set_custom_trace)(TraceFn)
void(* shutdown_thread_pool)()
Shutdown the thread pool maintained by this JIT module.
void(* shutdown_trace)()
Close the tracing file this module may be writing to.
IntrusivePtr< JITModuleHolder > module
void(* copy_to_host)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
void(* copy_to_dev)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
void(* free_dev_buffer)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
Detailed Description
Function pointers into a compiled halide module.
These function pointers are meaningless once the last copy of a JITCompiledModule is deleted, so don't cache them.
Definition at line 23 of file JITCompiledModule.h.
Member Typedef Documentation
typedef void(* Halide::Internal::JITCompiledModule::ErrorHandler)(const char *)
The type of a halide runtime error handler function.
Definition at line 46 of file JITCompiledModule.h.
typedef int(* Halide::Internal::JITCompiledModule::HalideTask)(int, uint8_t *)
Set a custom parallel for loop launcher.
See Func::set_custom_do_par_for
Definition at line 57 of file JITCompiledModule.h.
typedef void(* Halide::Internal::JITCompiledModule::TraceFn)(const char *, int, int, int, int, int, const void *, int, const int *)
Set a custom trace function.
See Func::set_custom_trace.
Definition at line 65 of file JITCompiledModule.h.
Constructor & Destructor Documentation
Halide::Internal::JITCompiledModule::JITCompiledModule () [inline]
Definition at line 81 of file JITCompiledModule.h.
Member Function Documentation
void Halide::Internal::JITCompiledModule::compile_module (CodeGen * cg, llvm::Module * mod, const std::string & function_name)
Take an llvm module and compile it.
Populates the function pointer members above with the result.
Member Data Documentation
void* Halide::Internal::JITCompiledModule::function
A pointer to the raw halide function.
It's true type depends on the Argument vector passed to CodeGen::compile. Image parameters become (buffer_t *), and scalar parameters become pointers to the appropriate values. The final argument is a pointer to the buffer_t defining the output.
Definition at line 29 of file JITCompiledModule.h.
int(* Halide::Internal::JITCompiledModule::wrapped_function)(const void **)
A slightly more type-safe wrapper around the raw halide module.
Takes it arguments as an array of pointers that correspond to the arguments to function
Definition at line 34 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::copy_to_host)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
These pointers may be NULL if not compiling for a gpu-like target.
Definition at line 40 of file JITCompiledModule.h.
Referenced by Halide::Buffer::copy_to_host().
void(* Halide::Internal::JITCompiledModule::copy_to_dev)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
These pointers may be NULL if not compiling for a gpu-like target.
Definition at line 41 of file JITCompiledModule.h.
Referenced by Halide::Buffer::copy_to_dev().
void(* Halide::Internal::JITCompiledModule::free_dev_buffer)(struct buffer_t *)
JITed helpers to interact with device-mapped buffer_t objects.
These pointers may be NULL if not compiling for a gpu-like target.
Definition at line 42 of file JITCompiledModule.h.
Referenced by Halide::Buffer::free_dev_buffer().
void(* Halide::Internal::JITCompiledModule::set_error_handler)(ErrorHandler)
Set the runtime error handler for this module.
Definition at line 49 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::set_custom_allocator)(void *(*malloc)(size_t), void(*free)(void *))
Set a custom malloc and free for this module to use.
See Func::set_custom_allocator
Definition at line 53 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::set_custom_do_par_for)(int(*custom_do_par_for)(HalideTask, int, int, uint8_t *))
Definition at line 58 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::set_custom_do_task)(int(*custom_do_task)(HalideTask, int, uint8_t *))
Set a custom do parallel task.
See Func::set_custom_do_task
Definition at line 62 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::set_custom_trace)(TraceFn)
Definition at line 66 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::shutdown_thread_pool)()
Shutdown the thread pool maintained by this JIT module.
This is also done automatically when the last reference to this module is destroyed.
Definition at line 71 of file JITCompiledModule.h.
void(* Halide::Internal::JITCompiledModule::shutdown_trace)()
Close the tracing file this module may be writing to.
Also done automatically when the last reference to this module is destroyed.
Definition at line 76 of file JITCompiledModule.h.
IntrusivePtr<JITModuleHolder> Halide::Internal::JITCompiledModule::module
Definition at line 79 of file JITCompiledModule.h.
The documentation for this struct was generated from the following file:
JITCompiledModule.h