Halide: Halide::Internal::Interval Struct Reference
Halide::Internal::Interval Struct Reference
A class to represent ranges of Exprs.
#include <Interval.h>
Public Member Functions
Interval ()
A default-constructed Interval is everything.
Interval (Expr min, Expr max)
Construct an interval from a lower and upper bound.
bool is_empty () const
Is the interval the empty set.
bool is_everything () const
Is the interval the entire range.
bool is_single_point () const
Is the interval just a single value (min == max)
bool is_single_point (Expr e) const
Is the interval a particular single value.
bool has_upper_bound () const
Does the interval have a finite least upper bound.
bool has_lower_bound () const
Does the interval have a finite greatest lower bound.
bool is_bounded () const
Does the interval have a finite upper and lower bound.
bool same_as (const Interval &other)
Is the interval the same as another interval.
void include (const Interval &i)
Expand the interval to include another Interval.
void include (Expr e)
Expand the interval to include an Expr.
bool operator== (const Interval &other) const
Static Public Member Functions
static Expr pos_inf ()
Exprs to represent positive and negative infinity.
static Expr neg_inf ()
static Interval everything ()
The interval representing everything.
static Interval nothing ()
The interval representing nothing.
static Interval single_point (Expr e)
Construct an interval representing a single point.
static Interval make_union (const Interval &a, const Interval &b)
Construct the smallest interval containing two intervals.
static Interval make_intersection (const Interval &a, const Interval &b)
Construct the largest interval contained within two intervals.
static Expr make_max (const Expr &a, const Expr &b)
An eagerly-simplifying max of two Exprs that respects infinities.
static Expr make_min (const Expr &a, const Expr &b)
An eagerly-simplifying min of two Exprs that respects infinities.
Public Attributes
Expr min
The lower and upper bound of the interval.
Expr max
Detailed Description
A class to represent ranges of Exprs.
Can be unbounded above or below.
Definition at line 15 of file Interval.h.
Constructor & Destructor Documentation
Interval() [1/2]
Halide::Internal::Interval::Interval () inline
A default-constructed Interval is everything.
Definition at line 31 of file Interval.h.
Referenced by everything(), nothing(), and single_point().
Interval() [2/2]
Halide::Internal::Interval::Interval (Expr min, Expr max) inline
Construct an interval from a lower and upper bound.
Definition at line 34 of file Interval.h.
References Halide::Internal::IntrusivePtr< T >::defined(), and internal_assert.
Member Function Documentation
pos_inf()
static Expr Halide::Internal::Interval::pos_inf () inline static
Exprs to represent positive and negative infinity.
Definition at line 22 of file Interval.h.
Referenced by everything(), has_upper_bound(), is_empty(), is_everything(), and nothing().
neg_inf()
static Expr Halide::Internal::Interval::neg_inf () inline static
Definition at line 23 of file Interval.h.
Referenced by everything(), has_lower_bound(), is_empty(), is_everything(), and nothing().
everything()
static Interval Halide::Internal::Interval::everything () inline static
The interval representing everything.
Definition at line 39 of file Interval.h.
References Interval(), neg_inf(), and pos_inf().
nothing()
static Interval Halide::Internal::Interval::nothing () inline static
The interval representing nothing.
Definition at line 42 of file Interval.h.
References Interval(), neg_inf(), and pos_inf().
single_point()
static Interval Halide::Internal::Interval::single_point (Expr e) inline static
Construct an interval representing a single point.
Definition at line 45 of file Interval.h.
References Interval().
is_empty()
bool Halide::Internal::Interval::is_empty () const inline
Is the interval the empty set.
Definition at line 48 of file Interval.h.
References neg_inf(), pos_inf(), and Halide::Internal::IntrusivePtr< T >::same_as().
Referenced by has_lower_bound(), and has_upper_bound().
is_everything()
bool Halide::Internal::Interval::is_everything () const inline
Is the interval the entire range.
Definition at line 51 of file Interval.h.
References neg_inf(), pos_inf(), and Halide::Internal::IntrusivePtr< T >::same_as().
is_single_point() [1/2]
bool Halide::Internal::Interval::is_single_point () const inline
Is the interval just a single value (min == max)
Definition at line 54 of file Interval.h.
References Halide::Internal::IntrusivePtr< T >::same_as().
is_single_point() [2/2]
bool Halide::Internal::Interval::is_single_point (Expr e) const inline
Is the interval a particular single value.
Definition at line 57 of file Interval.h.
References Halide::Internal::IntrusivePtr< T >::same_as().
has_upper_bound()
bool Halide::Internal::Interval::has_upper_bound () const inline
Does the interval have a finite least upper bound.
Definition at line 60 of file Interval.h.
References is_empty(), pos_inf(), and Halide::Internal::IntrusivePtr< T >::same_as().
Referenced by is_bounded().
has_lower_bound()
bool Halide::Internal::Interval::has_lower_bound () const inline
Does the interval have a finite greatest lower bound.
Definition at line 63 of file Interval.h.
References is_empty(), neg_inf(), and Halide::Internal::IntrusivePtr< T >::same_as().
Referenced by is_bounded().
is_bounded()
bool Halide::Internal::Interval::is_bounded () const inline
Does the interval have a finite upper and lower bound.
Definition at line 66 of file Interval.h.
References has_lower_bound(), and has_upper_bound().
same_as()
bool Halide::Internal::Interval::same_as (const Interval & other) inline
Is the interval the same as another interval.
Definition at line 69 of file Interval.h.
References Halide::Runtime::Internal::a, Halide::Runtime::Internal::b, include(), make_intersection(), make_max(), make_min(), make_union(), max, min, and Halide::Internal::IntrusivePtr< T >::same_as().
include() [1/2]
void Halide::Internal::Interval::include (const Interval & i)
Expand the interval to include another Interval.
Referenced by same_as().
include() [2/2]
void Halide::Internal::Interval::include (Expr e)
Expand the interval to include an Expr.
make_union()
static Interval Halide::Internal::Interval::make_union (const Interval & a, const Interval & b) static
Construct the smallest interval containing two intervals.
Referenced by same_as().
make_intersection()
static Interval Halide::Internal::Interval::make_intersection (const Interval & a, const Interval & b) static
Construct the largest interval contained within two intervals.
Referenced by same_as().
make_max()
static Expr Halide::Internal::Interval::make_max (const Expr & a, const Expr & b) static
An eagerly-simplifying max of two Exprs that respects infinities.
Referenced by same_as().
make_min()
static Expr Halide::Internal::Interval::make_min (const Expr & a, const Expr & b) static
An eagerly-simplifying min of two Exprs that respects infinities.
Referenced by same_as().
operator==()
bool Halide::Internal::Interval::operator== (const Interval & other) const inline
Definition at line 89 of file Interval.h.
References max, min, and Halide::Internal::IntrusivePtr< T >::same_as().
Member Data Documentation
min
Expr Halide::Internal::Interval::min
The lower and upper bound of the interval.
They are included in the interval.
Definition at line 28 of file Interval.h.
Referenced by operator==(), and same_as().
max
Expr Halide::Internal::Interval::max
Definition at line 28 of file Interval.h.
Referenced by operator==(), and same_as().
The documentation for this struct was generated from the following file:
Interval.h