Halide: Halide::Argument Struct Reference
Halide::Argument Struct Reference
A struct representing an argument to a halide-generated function.
#include <Argument.h>
Public Types
enum Kind { InputScalar = halide_argument_kind_input_scalar, InputBuffer = halide_argument_kind_input_buffer, OutputBuffer = halide_argument_kind_output_buffer }
An argument is either a primitive type (for parameters), or a buffer pointer.
Public Member Functions
Argument ()
Argument (const std::string &_name, Kind _kind, const Type &_type, uint8_t _dimensions, Expr _def=Expr(), Expr _min=Expr(), Expr _max=Expr())
bool is_buffer () const
bool is_scalar () const
bool is_input () const
bool is_output () const
Public Attributes
std::string name
The name of the argument.
Kind kind
uint8_t dimensions
If kind == InputBuffer|OutputBuffer, this is the dimensionality of the buffer.
Type type
If this is a scalar parameter, then this is its type.
Expr def
If this is a scalar parameter, then these are its default, min, max values.
Expr min
Expr max
Detailed Description
A struct representing an argument to a halide-generated function.
Used for specifying the function signature of generated code.
Definition at line 22 of file Argument.h.
Member Enumeration Documentation
enum Halide::Argument::Kind
An argument is either a primitive type (for parameters), or a buffer pointer.
If kind == InputScalar, then type fully encodes the expected type of the scalar argument.
If kind == InputBuffer|OutputBuffer, then type.bytes() should be used to determine* elem_size of the buffer; additionally, type.code should reflect the expected interpretation of the buffer data (e.g. float vs int), but there is no runtime enforcement of this at present.
Enumerator
InputScalar
InputBuffer
OutputBuffer
Definition at line 37 of file Argument.h.
Constructor & Destructor Documentation
Halide::Argument::Argument () inline
Definition at line 60 of file Argument.h.
Halide::Argument::Argument (const std::string & _name, Kind _kind, const Type & _type, uint8_t _dimensions, Expr _def = Expr(), Expr _min = Expr(), Expr _max = Expr()) inline
Definition at line 61 of file Argument.h.
References def, Halide::Internal::IntrusivePtr< T >::defined(), dimensions, is_buffer(), is_scalar(), max, min, and user_assert.
Member Function Documentation
bool Halide::Argument::is_buffer () const inline
Definition at line 76 of file Argument.h.
References InputBuffer, kind, and OutputBuffer.
Referenced by Argument().
bool Halide::Argument::is_scalar () const inline
Definition at line 77 of file Argument.h.
References InputScalar, and kind.
Referenced by Argument().
bool Halide::Argument::is_input () const inline
Definition at line 79 of file Argument.h.
References InputBuffer, InputScalar, and kind.
bool Halide::Argument::is_output () const inline
Definition at line 80 of file Argument.h.
References kind, and OutputBuffer.
Member Data Documentation
std::string Halide::Argument::name
The name of the argument.
Definition at line 24 of file Argument.h.
Kind Halide::Argument::kind
Definition at line 42 of file Argument.h.
Referenced by is_buffer(), is_input(), is_output(), and is_scalar().
uint8_t Halide::Argument::dimensions
If kind == InputBuffer|OutputBuffer, this is the dimensionality of the buffer.
If kind == InputScalar, this value is ignored (and should always be set to zero)
Definition at line 46 of file Argument.h.
Referenced by Argument().
Type Halide::Argument::type
If this is a scalar parameter, then this is its type.
If this is a buffer parameter, this is used to determine elem_size of the buffer_t.
Note that type.width should always be 1 here.
Definition at line 54 of file Argument.h.
Expr Halide::Argument::def
If this is a scalar parameter, then these are its default, min, max values.
By default, they are left unset, implying "no default, no min, no max".
Definition at line 58 of file Argument.h.
Referenced by Argument().
Expr Halide::Argument::min
Definition at line 58 of file Argument.h.
Referenced by Argument().
Expr Halide::Argument::max
Definition at line 58 of file Argument.h.
Referenced by Argument().
The documentation for this struct was generated from the following file:
Argument.h